var f;var k;k||(k=typeof Module !== 'undefined' ? Module : {});k.Jd||(k.Jd=0,k.Re=0);k.Jd++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var e=b;c.total&&(e=c.total);if(c.loaded){d.vc?k.Lc[a].loaded=c.loaded:(d.vc=!0,k.Lc||(k.Lc={}),k.Lc[a]={loaded:c.loaded,total:e});var g=e=c=0,h;for(h in k.Lc){var n=k.Lc[h];c+=n.total;e+=n.loaded;g++}c=Math.ceil(c*k.Jd/g);k.setStatus&&k.setStatus("Downloading data... ("+e+"/"+c+")")}else!k.Lc&&k.setStatus&&k.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){k.Re++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.Ke=c;c=a.files;for(var d=
0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();k.removeRunDependency("datafile_R:/emsOut/MinSizeRel/wglChAoSP.data")}k.FS_createPath("/","Shaders",!0,!0);k.FS_createPath("/","ChaoticAttractors",!0,!0);k.FS_createPath("/","colorMaps",!0,!0);k.FS_createPath("/","Fonts",!0,!0);k.FS_createPath("/","startData",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;k.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.Ke.subarray(this.start,
this.end))},finish:function(a){k.FS_createDataFile(this.name,null,a,!0,!0,!0);k.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,e=0;e<d.length;++e)(new b(d[e].start,d[e].end,d[e].audio)).open("GET",d[e].filename);k.addRunDependency("datafile_R:/emsOut/MinSizeRel/wglChAoSP.data");k.qe||(k.qe={});k.qe["R:/emsOut/MinSizeRel/wglChAoSP.data"]={Ff:!1};n?(c(n),n=null):h=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof k.locateFilePackage||k.locateFile||(k.locateFile=k.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=k.locateFile?k.locateFile("wglChAoSP.data",""):"wglChAoSP.data",g=a.Of,h=null,n=k.getPreloadedPackage?k.getPreloadedPackage(e,g):null;n||b(e,g,function(a){h?(h(a),h=null):n=a},c);k.calledRun?d():(k.preRun||(k.preRun=[]),k.preRun.push(d))})({files:[{start:0,audio:0,end:12639,filename:"/Shaders/allParticles.0.frag"},{start:12639,audio:0,end:16723,filename:"/Shaders/allParticles.0.vert"},{start:16723,audio:0,end:29419,filename:"/Shaders/allParticles.1.frag"},{start:29419,audio:0,end:42382,filename:"/Shaders/allParticles.frag"},
{start:42382,audio:0,end:46468,filename:"/Shaders/allParticles.vert"},{start:46468,audio:0,end:54959,filename:"/Shaders/ambientOcclusionFrag.glsl"},{start:54959,audio:0,end:79837,filename:"/Shaders/bilateralVersions.glsl"},{start:79837,audio:0,end:80493,filename:"/Shaders/BillboardFrag.glsl"},{start:80493,audio:0,end:82531,filename:"/Shaders/BillboardGeom.glsl"},{start:82531,audio:0,end:83632,filename:"/Shaders/BillboardVert.glsl"},{start:83632,audio:0,end:85306,filename:"/Shaders/cmTexturedFrag.glsl"},
{start:85306,audio:0,end:90280,filename:"/Shaders/colorSpaces.glsl"},{start:90280,audio:0,end:94247,filename:"/Shaders/fxaaFrag.glsl"},{start:94247,audio:0,end:104324,filename:"/Shaders/lightModelsFrag.glsl"},{start:104324,audio:0,end:105242,filename:"/Shaders/MergedRenderingFrag.glsl"},{start:105242,audio:0,end:106154,filename:"/Shaders/mmFBO_all_vert.glsl"},{start:106154,audio:0,end:107252,filename:"/Shaders/MotionBlurFS.glsl"},{start:107252,audio:0,end:108952,filename:"/Shaders/oglAxesFrag.glsl"},
{start:108952,audio:0,end:111137,filename:"/Shaders/oglAxesVert.glsl"},{start:111137,audio:0,end:117039,filename:"/Shaders/ParticlesFrag.glsl"},{start:117039,audio:0,end:119913,filename:"/Shaders/ParticlesVert.glsl"},{start:119913,audio:0,end:120643,filename:"/Shaders/PointSpriteFragLight.glsl"},{start:120643,audio:0,end:122657,filename:"/Shaders/PointSpriteVert.glsl"},{start:122657,audio:0,end:139326,filename:"/Shaders/postRenderingFrag.glsl"},{start:139326,audio:0,end:141891,filename:"/Shaders/postRenderingVert.glsl"},
{start:141891,audio:0,end:155410,filename:"/Shaders/RadialBlur2PassFrag.glsl"},{start:155410,audio:0,end:156605,filename:"/Shaders/shadowFrag.glsl"},{start:156605,audio:0,end:182726,filename:"/ChaoticAttractors/0009e1.sca"},{start:182726,audio:0,end:207994,filename:"/ChaoticAttractors/Aizawa05.sca"},{start:207994,audio:0,end:233274,filename:"/ChaoticAttractors/Aizawa06.sca"},{start:233274,audio:0,end:258554,filename:"/ChaoticAttractors/Aizawa09.sca"},{start:258554,audio:0,end:283889,filename:"/ChaoticAttractors/Aizawa10.sca"},
{start:283889,audio:0,end:309221,filename:"/ChaoticAttractors/Aizawa11.sca"},{start:309221,audio:0,end:334586,filename:"/ChaoticAttractors/Aizawa12.sca"},{start:334586,audio:0,end:358661,filename:"/ChaoticAttractors/aliDrago01.sca"},{start:358661,audio:0,end:382737,filename:"/ChaoticAttractors/BicomplexJMod0_IIM1.sca"},{start:382737,audio:0,end:406408,filename:"/ChaoticAttractors/BicomplexJMod3_IIM4.sca"},{start:406408,audio:0,end:429891,filename:"/ChaoticAttractors/BicomplexJMod3_IIM6.sca"},{start:429891,
audio:0,end:453800,filename:"/ChaoticAttractors/BicomplexJMod5_IIM.sca"},{start:453800,audio:0,end:477691,filename:"/ChaoticAttractors/BicomplexJMod7_IIM.sca"},{start:477691,audio:0,end:501829,filename:"/ChaoticAttractors/BicomplexMod_IIM02.sca"},{start:501829,audio:0,end:526963,filename:"/ChaoticAttractors/biTorus_09o4a.sca"},{start:526963,audio:0,end:552093,filename:"/ChaoticAttractors/biTorus_09o5.sca"},{start:552093,audio:0,end:577239,filename:"/ChaoticAttractors/biTorus_09o8.sca"},{start:577239,
audio:0,end:603398,filename:"/ChaoticAttractors/dragon3b.sca"},{start:603398,audio:0,end:629466,filename:"/ChaoticAttractors/dragon4a.sca"},{start:629466,audio:0,end:659401,filename:"/ChaoticAttractors/dreamcatcher01.sca"},{start:659401,audio:0,end:684473,filename:"/ChaoticAttractors/flower_0009nc.sca"},{start:684473,audio:0,end:709547,filename:"/ChaoticAttractors/flower_0009nd.sca"},{start:709547,audio:0,end:735569,filename:"/ChaoticAttractors/flower_0009ng.sca"},{start:735569,audio:0,end:760837,
filename:"/ChaoticAttractors/Halvorsen01.sca"},{start:760837,audio:0,end:785392,filename:"/ChaoticAttractors/JuliaBulbN7_01.sca"},{start:785392,audio:0,end:809254,filename:"/ChaoticAttractors/juliaBulb_IIM02.sca"},{start:809254,audio:0,end:834338,filename:"/ChaoticAttractors/Magnetic_stright01.sca"},{start:834338,audio:0,end:859884,filename:"/ChaoticAttractors/Magnetic_stright01a.sca"},{start:859884,audio:0,end:885850,filename:"/ChaoticAttractors/Mag_0009e2b.sca"},{start:885850,audio:0,end:914026,
filename:"/ChaoticAttractors/Pn3D_o06_001.sca"},{start:914026,audio:0,end:937659,filename:"/ChaoticAttractors/quatJulia_01.sca"},{start:937659,audio:0,end:963001,filename:"/ChaoticAttractors/Rampe03a.sca"},{start:963001,audio:0,end:987017,filename:"/ChaoticAttractors/Rampe07old.sca"},{start:987017,audio:0,end:1010902,filename:"/ChaoticAttractors/Thomas01.sca"},{start:1010902,audio:0,end:1036800,filename:"/ChaoticAttractors/torus_0009j.sca"},{start:1036800,audio:0,end:1062012,filename:"/ChaoticAttractors/torus_0009k.sca"},
{start:1062012,audio:0,end:1087155,filename:"/ChaoticAttractors/torus_0009l.sca"},{start:1087155,audio:0,end:1112386,filename:"/ChaoticAttractors/torus_0009m1.sca"},{start:1112386,audio:0,end:1137618,filename:"/ChaoticAttractors/torus_0009m3.sca"},{start:1137618,audio:0,end:1162444,filename:"/ChaoticAttractors/torus_0009m4.sca"},{start:1162444,audio:0,end:1187685,filename:"/ChaoticAttractors/torus_0009nb.sca"},{start:1187685,audio:0,end:2172947,filename:"/colorMaps/palettes.json"},{start:2172947,
audio:0,end:2216859,filename:"/Fonts/Cousine-Regular.ttf"},{start:2216859,audio:0,end:2382407,filename:"/Fonts/fontawesome-webfont.ttf"},{start:2382407,audio:0,end:2382775,filename:"/Fonts/README.txt"},{start:2382775,audio:0,end:2408046,filename:"/startData/Aizawa.sca"},{start:2408046,audio:0,end:2433288,filename:"/startData/Arneodo.sca"},{start:2433288,audio:0,end:2458602,filename:"/startData/BicomplexJExplorer.sca"},{start:2458602,audio:0,end:2481752,filename:"/startData/BicomplexJMod0_IIM.sca"},
{start:2481752,audio:0,end:2507159,filename:"/startData/BicomplexJMod1_IIM.sca"},{start:2507159,audio:0,end:2531067,filename:"/startData/BicomplexJMod2_IIM.sca"},{start:2531067,audio:0,end:2554931,filename:"/startData/BicomplexJMod3_IIM.sca"},{start:2554931,audio:0,end:2578894,filename:"/startData/BicomplexJMod4_IIM.sca"},{start:2578894,audio:0,end:2604334,filename:"/startData/BicomplexJMod5_IIM.sca"},{start:2604334,audio:0,end:2628332,filename:"/startData/BicomplexJMod6_IIM.sca"},{start:2628332,
audio:0,end:2653718,filename:"/startData/BicomplexJMod7_IIM.sca"},{start:2653718,audio:0,end:2677640,filename:"/startData/BicomplexJ_IIM.sca"},{start:2677640,audio:0,end:2702971,filename:"/startData/Bouali.sca"},{start:2702971,audio:0,end:2728290,filename:"/startData/ChenLee.sca"},{start:2728290,audio:0,end:2753757,filename:"/startData/Coullet.sca"},{start:2753757,audio:0,end:2779193,filename:"/startData/Dadras.sca"},{start:2779193,audio:0,end:2804460,filename:"/startData/DequanLi.sca"},{start:2804460,
audio:0,end:2829826,filename:"/startData/dla3D.sca"},{start:2829826,audio:0,end:2854684,filename:"/startData/FourWing.sca"},{start:2854684,audio:0,end:2879992,filename:"/startData/FourWing2.sca"},{start:2879992,audio:0,end:2905285,filename:"/startData/FourWing3.sca"},{start:2905285,audio:0,end:2930707,filename:"/startData/GenesioTesi.sca"},{start:2930707,audio:0,end:2956145,filename:"/startData/Hadley.sca"},{start:2956145,audio:0,end:2980210,filename:"/startData/Halvorsen.sca"},{start:2980210,audio:0,
end:3005568,filename:"/startData/juliaBulb4th_IIM.sca"},{start:3005568,audio:0,end:3029503,filename:"/startData/juliaBulb_IIM.sca"},{start:3029503,audio:0,end:3054815,filename:"/startData/KingsDream.sca"},{start:3054815,audio:0,end:3080284,filename:"/startData/LiuChen.sca"},{start:3080284,audio:0,end:3104760,filename:"/startData/Lorenz.sca"},{start:3104760,audio:0,end:3129903,filename:"/startData/MagneticFull.sca"},{start:3129903,audio:0,end:3154998,filename:"/startData/MagneticLeft.sca"},{start:3154998,
audio:0,end:3181723,filename:"/startData/MagneticRight.sca"},{start:3181723,audio:0,end:3206386,filename:"/startData/MagneticStraight.sca"},{start:3206386,audio:0,end:3231738,filename:"/startData/Mira3D.sca"},{start:3231738,audio:0,end:3257021,filename:"/startData/MultiChuaII.sca"},{start:3257021,audio:0,end:3282419,filename:"/startData/NewtonLeipnik.sca"},{start:3282419,audio:0,end:3307581,filename:"/startData/NoseHoover.sca"},{start:3307581,audio:0,end:3330611,filename:"/startData/Pickover.sca"},
{start:3330611,audio:0,end:3356008,filename:"/startData/PolynomialA.sca"},{start:3356008,audio:0,end:3380237,filename:"/startData/PolynomialABS.sca"},{start:3380237,audio:0,end:3404689,filename:"/startData/PolynomialB.sca"},{start:3404689,audio:0,end:3430304,filename:"/startData/PolynomialC.sca"},{start:3430304,audio:0,end:3453623,filename:"/startData/PolynomialPow.sca"},{start:3453623,audio:0,end:3479669,filename:"/startData/PolynomialSin.sca"},{start:3479669,audio:0,end:3519437,filename:"/startData/PowerN3D.sca"},
{start:3519437,audio:0,end:3544852,filename:"/startData/quatJulia_IIM.sca"},{start:3544852,audio:0,end:3569166,filename:"/startData/Rampe01.sca"},{start:3569166,audio:0,end:3591117,filename:"/startData/Rampe02.sca"},{start:3591117,audio:0,end:3614893,filename:"/startData/Rampe03.sca"},{start:3614893,audio:0,end:3638736,filename:"/startData/Rampe03A.sca"},{start:3638736,audio:0,end:3662548,filename:"/startData/Rampe04.sca"},{start:3662548,audio:0,end:3685978,filename:"/startData/Rampe05.sca"},{start:3685978,
audio:0,end:3711374,filename:"/startData/Rampe06.sca"},{start:3711374,audio:0,end:3733706,filename:"/startData/Rampe07.sca"},{start:3733706,audio:0,end:3757522,filename:"/startData/Rampe08.sca"},{start:3757522,audio:0,end:3780913,filename:"/startData/Rampe09.sca"},{start:3780913,audio:0,end:3804679,filename:"/startData/Rampe10.sca"},{start:3804679,audio:0,end:3830101,filename:"/startData/RayleighBenard.sca"},{start:3830101,audio:0,end:3853958,filename:"/startData/Robinson.sca"},{start:3853958,audio:0,
end:3879113,filename:"/startData/Rossler.sca"},{start:3879113,audio:0,end:3905436,filename:"/startData/Rucklidge.sca"},{start:3905436,audio:0,end:3930960,filename:"/startData/Sakarya.sca"},{start:3930960,audio:0,end:3955494,filename:"/startData/SinCos.sca"},{start:3955494,audio:0,end:3980866,filename:"/startData/SprottLinzF.sca"},{start:3980866,audio:0,end:4006033,filename:"/startData/Thomas.sca"},{start:4006033,audio:0,end:4031299,filename:"/startData/TSUCS.sca"},{start:4031299,audio:0,end:4056553,
filename:"/startData/YuWang.sca"},{start:4056553,audio:0,end:4081890,filename:"/startData/ZhouChen.sca"}],remote_package_size:4081890,package_uuid:"72d6c08d-5f49-474b-9c04-bc2915113a17"});var aa={},ba;for(ba in k)k.hasOwnProperty(ba)&&(aa[ba]=k[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,m=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;m="function"===typeof importScripts;
ha=(ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!m;ja=!fa&&!ha&&!m;var ka="",la,ma,na;
if(ha){ka=__dirname+"/";var oa,pa;la=function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);a=oa.readFileSync(a);return b?a:a.toString()};na=function(a){a=la(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));ca=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=k);process.on("uncaughtException",function(a){if(!(a instanceof qa))throw a;});process.on("unhandledRejection",p);ea=function(a){process.exit(a)};
k.inspect=function(){return"[Emscripten Module object]"}}else if(ja)"undefined"!=typeof read&&(la=function(a){return read(a)}),na=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||m)m?ka=self.location.href:document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ma=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ra=k.print||console.log.bind(console),l=k.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(k[ba]=aa[ba]);aa=null;k.arguments&&(ca=k.arguments);k.thisProgram&&(da=k.thisProgram);k.quit&&(ea=k.quit);
function sa(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:if("*"===a[a.length-1])return 4;if("i"===a[0]){var b=parseInt(a.substr(1));assert(0===b%8,"getNativeTypeSize invalid bits "+b+", type "+a);return b/8}return 0}}function ta(a){ua||(ua={});ua[a]||(ua[a]=1,l(a))}var ua,va={"f64-rem":function(a,b){return a%b},"debugger":function(){}},wa;k.wasmBinary&&(wa=k.wasmBinary);
"object"!==typeof WebAssembly&&l("no native wasm support detected");
function q(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":v[a>>0]=b;break;case "i8":v[a>>0]=b;break;case "i16":xa[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":y=[b>>>0,(z=b,1<=+ya(z)?0<z?(za(+Aa(z/4294967296),4294967295)|0)>>>0:~~+Ba((z-+(~~z>>>0))/4294967296)>>>0:0)];w[a>>2]=y[0];w[a+4>>2]=y[1];break;case "float":A[a>>2]=b;break;case "double":Ca[a>>3]=b;break;default:p("invalid type for setValue: "+c)}}var Da,B=!1;
function assert(a,b){a||p("Assertion failed: "+b)}function Ea(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;var e="string"===typeof b?b:null;var g=Fa(Math.max(d,e?1:b.length));if(c){a=g;assert(0==(g&3));for(b=g+(d&-4);a<b;a+=4)w[a>>2]=0;for(b=g+d;a<b;)v[a++>>0]=0;return g}if("i8"===e)return a.subarray||a.slice?C.set(a,g):C.set(new Uint8Array(a),g),g;c=0;for(var h,n,r;c<d;){var t=a[c];h=e||b[c];0===h?c++:("i64"==h&&(h="i32"),q(g+c,t,h),r!==h&&(n=sa(h),r=h),c+=n)}return g}
function Ga(a){if(Ha)var b=Fa(a);else b=w[Ia>>2],a=b+a+15&-16,a>Ja()&&p(),w[Ia>>2]=a;return b}var Ka="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function La(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?La(C,a,b):""}
function Ma(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Oa(a){var b=Na(a)+1,c=Pa(b);Ma(a,v,c,b);return c}function Qa(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,v,C,xa,Ra,w,Sa,A,Ca;
function Ta(){k.HEAP8=v=new Int8Array(buffer);k.HEAP16=xa=new Int16Array(buffer);k.HEAP32=w=new Int32Array(buffer);k.HEAPU8=C=new Uint8Array(buffer);k.HEAPU16=Ra=new Uint16Array(buffer);k.HEAPU32=Sa=new Uint32Array(buffer);k.HEAPF32=A=new Float32Array(buffer);k.HEAPF64=Ca=new Float64Array(buffer)}var Ia=112688,Ua=k.TOTAL_MEMORY||16777216;k.wasmMemory?Da=k.wasmMemory:Da=new WebAssembly.Memory({initial:Ua/65536});Da&&(buffer=Da.buffer);Ua=buffer.byteLength;Ta();w[Ia>>2]=5355600;
function Va(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Cc;"number"===typeof c?void 0===b.Fc?k.dynCall_v(c):k.dynCall_vi(c,b.Fc):c(void 0===b.Fc?null:b.Fc)}}}var Wa=[],Xa=[],Ya=[],Za=[],$a=[],Ha=!1;function ab(){var a=k.preRun.shift();Wa.unshift(a)}var ya=Math.abs,Ba=Math.ceil,Aa=Math.floor,za=Math.min,bb=0,cb=null,db=null;function eb(){bb++;k.monitorRunDependencies&&k.monitorRunDependencies(bb)}
function fb(){bb--;k.monitorRunDependencies&&k.monitorRunDependencies(bb);if(0==bb&&(null!==cb&&(clearInterval(cb),cb=null),db)){var a=db;db=null;a()}}k.preloadedImages={};k.preloadedAudios={};function gb(){var a=hb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var hb="wglChAoSP.wasm";if(!gb()){var ib=hb;hb=k.locateFile?k.locateFile(ib,ka):ka+ib}
function jb(){try{if(wa)return new Uint8Array(wa);if(na)return na(hb);throw"both async and sync fetching of the wasm failed";}catch(a){p(a)}}function kb(){return wa||!fa&&!m||"function"!==typeof fetch?new Promise(function(a){a(jb())}):fetch(hb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+hb+"'";return a.arrayBuffer()}).catch(function(){return jb()})}
function lb(a){function b(a){k.asm=a.exports;fb("wasm-instantiate")}function c(a){b(a.instance)}function d(a){return kb().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){l("failed to asynchronously prepare wasm: "+a);p(a)})}var e={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:va};eb("wasm-instantiate");if(k.instantiateWasm)try{return k.instantiateWasm(e,b)}catch(g){return l("Module.instantiateWasm callback failed with error: "+g),!1}(function(){if(wa||
"function"!==typeof WebAssembly.instantiateStreaming||gb()||"function"!==typeof fetch)return d(c);fetch(hb,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,e).then(c,function(a){l("wasm streaming compile failed: "+a);l("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}k.asm=function(a,b){b.memory=Da;b.table=new WebAssembly.Table({initial:1383,maximum:1383,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return lb(b)};var z,y;Xa.push({Cc:function(){mb()}});
var F={};
function nb(a){if(nb.Me){var b=w[a>>2];var c=w[b>>2]}else nb.Me=!0,F.USER=F.LOGNAME="web_user",F.PATH="/",F.PWD="/",F.HOME="/home/web_user",F.LANG="C.UTF-8",F.LANG=("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",F._=da,c=Ga(1024),b=Ga(256),w[b>>2]=c,w[a>>2]=b;a=[];var d=0,e;for(e in F)if("string"===typeof F[e]){var g=e+"="+F[e];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<a.length;e++){d=g=
a[e];for(var h=c,n=0;n<d.length;++n)v[h++>>0]=d.charCodeAt(n);v[h>>0]=0;w[b+4*e>>2]=c;c+=g.length+1}w[b+4*a.length>>2]=0}function ob(a){k.___errno_location&&(w[k.___errno_location()>>2]=a);return a}function pb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function qb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=pb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function rb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function sb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function tb(){var a=Array.prototype.slice.call(arguments,0);return qb(a.join("/"))}function G(a,b){return qb(a+"/"+b)}function ub(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=pb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var vb=[];function wb(a,b){vb[a]={input:[],output:[],Qc:b};xb(a,yb)}
var yb={open:function(a){var b=vb[a.node.rdev];if(!b)throw new H(19);a.tty=b;a.seekable=!1},close:function(a){a.tty.Qc.flush(a.tty)},flush:function(a){a.tty.Qc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Qc.ge)throw new H(6);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Qc.ge(a.tty)}catch(n){throw new H(5);}if(void 0===h&&0===e)throw new H(11);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Qc.Pd)throw new H(6);
try{for(var e=0;e<d;e++)a.tty.Qc.Pd(a.tty,b[c+e])}catch(g){throw new H(5);}d&&(a.node.timestamp=Date.now());return e}},Bb={ge:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.vc?Buffer.vc(256):new Buffer(256),d=0,e=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{e=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(e,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(e);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=
typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=zb(b,!0)}return a.input.shift()},Pd:function(a,b){null===b||10===b?(ra(La(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ra(La(a.output,0)),a.output=[])}},Cb={Pd:function(a,b){null===b||10===b?(l(La(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(l(La(a.output,0)),a.output=[])}},I={Ac:null,yc:function(){return I.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(1);I.Ac||(I.Ac={dir:{node:{Bc:I.rc.Bc,wc:I.rc.wc,lookup:I.rc.lookup,Zc:I.rc.Zc,rename:I.rc.rename,unlink:I.rc.unlink,rmdir:I.rc.rmdir,readdir:I.rc.readdir,symlink:I.rc.symlink},stream:{Dc:I.sc.Dc}},file:{node:{Bc:I.rc.Bc,wc:I.rc.wc},stream:{Dc:I.sc.Dc,read:I.sc.read,write:I.sc.write,Td:I.sc.Td,me:I.sc.me,
wd:I.sc.wd}},link:{node:{Bc:I.rc.Bc,wc:I.rc.wc,readlink:I.rc.readlink},stream:{}},Yd:{node:{Bc:I.rc.Bc,wc:I.rc.wc},stream:Db}});c=Eb(a,b,c,d);J(c.mode)?(c.rc=I.Ac.dir.node,c.sc=I.Ac.dir.stream,c.qc={}):32768===(c.mode&61440)?(c.rc=I.Ac.file.node,c.sc=I.Ac.file.stream,c.uc=0,c.qc=null):40960===(c.mode&61440)?(c.rc=I.Ac.link.node,c.sc=I.Ac.link.stream):8192===(c.mode&61440)&&(c.rc=I.Ac.Yd.node,c.sc=I.Ac.Yd.stream);c.timestamp=Date.now();a&&(a.qc[b]=c);return c},Gf:function(a){if(a.qc&&a.qc.subarray){for(var b=
[],c=0;c<a.uc;++c)b.push(a.qc[c]);return b}return a.qc},Hf:function(a){return a.qc?a.qc.subarray?a.qc.subarray(0,a.uc):new Uint8Array(a.qc):new Uint8Array},ae:function(a,b){var c=a.qc?a.qc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.qc,a.qc=new Uint8Array(b),0<a.uc&&a.qc.set(c.subarray(0,a.uc),0))},ff:function(a,b){if(a.uc!=b)if(0==b)a.qc=null,a.uc=0;else{if(!a.qc||a.qc.subarray){var c=a.qc;a.qc=new Uint8Array(new ArrayBuffer(b));c&&a.qc.set(c.subarray(0,Math.min(b,
a.uc)))}else if(a.qc||(a.qc=[]),a.qc.length>b)a.qc.length=b;else for(;a.qc.length<b;)a.qc.push(0);a.uc=b}},rc:{Bc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.uc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Gc=4096;b.blocks=Math.ceil(b.size/b.Gc);return b},wc:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.ff(a,b.size)},lookup:function(){throw Fb[2];},Zc:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(J(a.mode)){try{var d=Gb(b,c)}catch(g){}if(d)for(var e in d.qc)throw new H(39);}delete a.parent.qc[a.name];a.name=c;b.qc[c]=a;a.parent=b},unlink:function(a,b){delete a.qc[b]},rmdir:function(a,b){var c=Gb(a,b),d;for(d in c.qc)throw new H(39);delete a.qc[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.qc)a.qc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(22);return a.link}},sc:{read:function(a,b,c,d,e){var g=a.node.qc;if(e>=a.node.uc)return 0;a=Math.min(a.node.uc-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.qc||a.qc.subarray)){if(g)return a.qc=b.subarray(c,c+d),a.uc=d;if(0===a.uc&&0===e)return a.qc=new Uint8Array(b.subarray(c,c+d)),a.uc=d;if(e+d<=a.uc)return a.qc.set(b.subarray(c,c+d),e),d}I.ae(a,e+d);if(a.qc.subarray&&b.subarray)a.qc.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.qc[e+g]=b[c+g];a.uc=Math.max(a.uc,e+d);return d},Dc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.uc);if(0>b)throw new H(22);return b},Td:function(a,b,c){I.ae(a.node,b+c);a.node.uc=
Math.max(a.node.uc,b+c)},me:function(a,b,c,d,e,g,h){if(32768!==(a.node.mode&61440))throw new H(19);c=a.node.qc;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.uc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==v.buffer;d=Fa(d);if(!d)throw new H(12);(e?v:b).set(c,d)}else a=!1,d=c.byteOffset;return{Nf:d,Fe:a}},wd:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(19);if(e&2)return 0;I.sc.write(a,b,0,d,c,!1);return 0}}},L={qd:!1,nf:function(){L.qd=
!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);L.be={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Ud:function(a){return Buffer.vc?Buffer.from(a):new Buffer(a)},yc:function(a){assert(ia);return L.createNode(null,"/",L.fe(a.Od.root),0)},createNode:function(a,b,c){if(!J(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new H(22);a=Eb(a,b,c);a.rc=L.rc;a.sc=L.sc;return a},fe:function(a){try{var b=fs.lstatSync(a);
L.qd&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new H(-c.tc);}return b.mode},zc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.yc.Od.root);b.reverse();return tb.apply(null,b)},Se:function(a){a&=-2656257;var b=0,c;for(c in L.be)a&c&&(b|=L.be[c],a^=c);if(a)throw new H(22);return b},rc:{Bc:function(a){a=L.zc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new H(-c.tc);}L.qd&&!b.Gc&&(b.Gc=4096);L.qd&&!b.blocks&&(b.blocks=(b.size+b.Gc-1)/
b.Gc|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Gc:b.Gc,blocks:b.blocks}},wc:function(a,b){var c=L.zc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new H(-d.tc);}},lookup:function(a,b){var c=G(L.zc(a),b);c=L.fe(c);return L.createNode(a,b,c)},Zc:function(a,b,c,d){a=L.createNode(a,b,c,d);b=L.zc(a);try{J(a.mode)?
fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new H(-e.tc);}return a},rename:function(a,b,c){a=L.zc(a);b=G(L.zc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new H(-d.tc);}},unlink:function(a,b){a=G(L.zc(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new H(-c.tc);}},rmdir:function(a,b){a=G(L.zc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new H(-c.tc);}},readdir:function(a){a=L.zc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;
throw new H(-b.tc);}},symlink:function(a,b,c){a=G(L.zc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new H(-d.tc);}},readlink:function(a){var b=L.zc(a);try{return b=fs.readlinkSync(b),b=Hb.relative(Hb.resolve(a.yc.Od.root),b)}catch(c){if(!c.code)throw c;throw new H(-c.tc);}}},sc:{open:function(a){var b=L.zc(a.node);try{32768===(a.node.mode&61440)&&(a.ad=fs.openSync(b,L.Se(a.flags)))}catch(c){if(!c.code)throw c;throw new H(-c.tc);}},close:function(a){try{32768===(a.node.mode&61440)&&
a.ad&&fs.closeSync(a.ad)}catch(b){if(!b.code)throw b;throw new H(-b.tc);}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.ad,L.Ud(b.buffer),c,d,e)}catch(g){throw new H(-g.tc);}},write:function(a,b,c,d,e){try{return fs.writeSync(a.ad,L.Ud(b.buffer),c,d,e)}catch(g){throw new H(-g.tc);}},Dc:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.ad).size}catch(d){throw new H(-d.tc);}if(0>b)throw new H(22);return b}}},Ib=null,Jb={},
Kb=[],Lb=1,Mb=null,Nb=!0,Ob={},H=null,Fb={};
function M(a,b){a=ub("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ce:!0,Qd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Qd)throw new H(40);a=pb(a.split("/").filter(function(a){return!!a}),!1);var e=Ib;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=Gb(e,a[d]);c=G(c,a[d]);e.$c&&(!g||g&&b.ce)&&(e=e.$c.root);if(!g||b.nd)for(g=0;40960===(e.mode&61440);)if(e=Pb(c),c=ub(rb(c),e),e=M(c,{Qd:b.Qd}).node,40<g++)throw new H(40);}return{path:c,node:e}}
function Qb(a){for(var b;;){if(a===a.parent)return a=a.yc.ne,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Rb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Mb.length}function Sb(a){var b=Rb(a.parent.id,a.name);a.Oc=Mb[b];Mb[b]=a}function Gb(a,b){var c;if(c=(c=Tb(a,"x"))?c:a.rc.lookup?0:13)throw new H(c,a);for(c=Mb[Rb(a.id,b)];c;c=c.Oc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.rc.lookup(a,b)}
function Eb(a,b,c,d){Ub||(Ub=function(a,b,c,d){a||(a=this);this.parent=a;this.yc=a.yc;this.$c=null;this.id=Lb++;this.name=b;this.mode=c;this.rc={};this.sc={};this.rdev=d},Ub.prototype={},Object.defineProperties(Ub.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},bf:{get:function(){return J(this.mode)}},af:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Ub(a,b,c,d);Sb(a);return a}function J(a){return 16384===(a&61440)}var Vb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Wb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Tb(a,b){if(Nb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}
function Xb(a,b){try{return Gb(a,b),17}catch(c){}return Tb(a,"wx")}function Yb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Kb[a])return a;throw new H(24);}function Zb(a,b){$b||($b=function(){},$b.prototype={},Object.defineProperties($b.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new $b,d;for(d in a)c[d]=a[d];a=c;b=Yb(b);a.fd=b;return Kb[b]=a}var Db={open:function(a){a.sc=Jb[a.node.rdev].sc;a.sc.open&&a.sc.open(a)},Dc:function(){throw new H(29);}};
function xb(a,b){Jb[a]={sc:b}}function ac(a,b){var c="/"===b,d=!b;if(c&&Ib)throw new H(16);if(!c&&!d){var e=M(b,{ce:!1});b=e.path;e=e.node;if(e.$c)throw new H(16);if(!J(e.mode))throw new H(20);}b={type:a,Od:{},ne:b,df:[]};a=a.yc(b);a.yc=b;b.root=a;c?Ib=a:e&&(e.$c=b,e.yc&&e.yc.df.push(b))}function bc(a,b,c){var d=M(a,{parent:!0}).node;a=sb(a);if(!a||"."===a||".."===a)throw new H(22);var e=Xb(d,a);if(e)throw new H(e);if(!d.rc.Zc)throw new H(1);return d.rc.Zc(d,a,b,c)}
function N(a,b){return bc(a,(void 0!==b?b:511)&1023|16384,0)}function cc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return bc(a,b|8192,c)}function dc(a,b){if(!ub(a))throw new H(2);var c=M(b,{parent:!0}).node;if(!c)throw new H(2);b=sb(b);var d=Xb(c,b);if(d)throw new H(d);if(!c.rc.symlink)throw new H(1);return c.rc.symlink(c,b,a)}
function ec(a){var b=M(a,{parent:!0}).node,c=sb(a),d=Gb(b,c);a:{try{var e=Gb(b,c)}catch(h){e=h.tc;break a}var g=Tb(b,"wx");e=g?g:J(e.mode)?21:0}if(e)throw new H(e);if(!b.rc.unlink)throw new H(1);if(d.$c)throw new H(16);try{Ob.willDeletePath&&Ob.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.rc.unlink(b,c);b=Rb(d.parent.id,d.name);if(Mb[b]===d)Mb[b]=d.Oc;else for(b=Mb[b];b;){if(b.Oc===d){b.Oc=d.Oc;break}b=b.Oc}try{if(Ob.onDeletePath)Ob.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Pb(a){a=M(a).node;if(!a)throw new H(2);if(!a.rc.readlink)throw new H(22);return ub(Qb(a.parent),a.rc.readlink(a))}function fc(a,b){var c;"string"===typeof a?c=M(a,{nd:!0}).node:c=a;if(!c.rc.wc)throw new H(1);c.rc.wc(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function hc(a,b,c,d){if(""===a)throw new H(2);if("string"===typeof b){var e=Vb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=qb(a);try{g=M(a,{nd:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(g){if(b&128)throw new H(17);}else g=bc(a,c,0),e=!0;if(!g)throw new H(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!J(g.mode))throw new H(20);if(!e&&(c=g?40960===(g.mode&61440)?40:J(g.mode)&&
("r"!==Wb(b)||b&512)?21:Tb(g,Wb(b)):2))throw new H(c);if(b&512){c=g;var h;"string"===typeof c?h=M(c,{nd:!0}).node:h=c;if(!h.rc.wc)throw new H(1);if(J(h.mode))throw new H(21);if(32768!==(h.mode&61440))throw new H(22);if(c=Tb(h,"w"))throw new H(c);h.rc.wc(h,{size:0,timestamp:Date.now()})}b&=-641;d=Zb({node:g,path:Qb(g),flags:b,seekable:!0,position:0,sc:g.sc,uf:[],error:!1},d);d.sc.open&&d.sc.open(d);!k.logReadFiles||b&1||(jc||(jc={}),a in jc||(jc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Ob.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Ob.onOpenFile(a,g))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function kc(a){if(null===a.fd)throw new H(9);a.Ic&&(a.Ic=null);try{a.sc.close&&a.sc.close(a)}catch(b){throw b;}finally{Kb[a.fd]=null}a.fd=null}
function lc(a,b,c){if(null===a.fd)throw new H(9);if(!a.seekable||!a.sc.Dc)throw new H(29);if(0!=c&&1!=c&&2!=c)throw new H(22);a.position=a.sc.Dc(a,b,c);a.uf=[];return a.position}
function mc(a,b,c,d,e,g){if(0>d||0>e)throw new H(22);if(null===a.fd)throw new H(9);if(0===(a.flags&2097155))throw new H(9);if(J(a.node.mode))throw new H(21);if(!a.sc.write)throw new H(22);a.flags&1024&&lc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H(29);b=a.sc.write(a,b,c,d,e,g);h||(a.position+=b);try{if(a.path&&Ob.onWriteToFile)Ob.onWriteToFile(a.path)}catch(n){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+n.message)}return b}
function nc(){H||(H=function(a,b){this.node=b;this.kf=function(a){this.tc=a};this.kf(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},H.prototype=Error(),H.prototype.constructor=H,[2].forEach(function(a){Fb[a]=new H(a);Fb[a].stack="<generic error, no stack>"}))}var oc;function pc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function qc(a,b,c,d){a=G("string"===typeof a?a:Qb(a),b);return N(a,pc(c,d))}
function rc(a,b){a="string"===typeof a?a:Qb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a,c);try{N(d)}catch(e){}a=d}}return d}function sc(a,b,c,d){a=G("string"===typeof a?a:Qb(a),b);c=pc(c,d);return bc(a,(void 0!==c?c:438)&4095|32768,0)}
function tc(a,b,c,d,e,g){a=b?G("string"===typeof a?a:Qb(a),b):a;d=pc(d,e);e=bc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}fc(e,d|146);a=hc(e,"w");mc(a,c,0,c.length,0,g);kc(a);fc(e,d)}return e}
function O(a,b,c,d){a=G("string"===typeof a?a:Qb(a),b);b=pc(!!c,!!d);O.ke||(O.ke=64);var e=O.ke++<<8|0;xb(e,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,e){for(var g=0,h=0;h<e;h++){try{var n=c()}catch(E){throw new H(5);}if(void 0===n&&0===g)throw new H(11);if(null===n||void 0===n)break;g++;b[d+h]=n}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,e){for(var g=0;g<e;g++)try{d(b[c+g])}catch(u){throw new H(5);}e&&(a.node.timestamp=
Date.now());return g}});return cc(a,b,e)}function uc(a,b,c){a=G("string"===typeof a?a:Qb(a),b);return dc(c,a)}
function vc(a){if(a.af||a.bf||a.link||a.qc)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(la)try{a.qc=zb(la(a.url),!0),a.uc=a.qc.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||ob(5);return b}
function wc(a,b,c,d,e){function g(){this.Md=!1;this.jd=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.he(a/this.chunkSize|0)[b]}};g.prototype.jf=function(a){this.he=a};g.prototype.Vd=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,e=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;e||(g=b);var h=this;h.jf(function(a){var d=a*g,e=(a+1)*g-1;e=Math.min(e,b-1);if("undefined"===typeof h.jd[a]){var x=h.jd;if(d>e)throw Error("invalid range ("+d+", "+e+") or no bytes requested!");if(e>b-1)throw Error("only "+b+" bytes available! programmer error!");var n=new XMLHttpRequest;n.open("GET",c,!1);b!==g&&n.setRequestHeader("Range","bytes="+d+"-"+e);"undefined"!=typeof Uint8Array&&(n.responseType="arraybuffer");
n.overrideMimeType&&n.overrideMimeType("text/plain; charset=x-user-defined");n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);d=void 0!==n.response?new Uint8Array(n.response||[]):zb(n.responseText||"",!0);x[a]=d}if("undefined"===typeof h.jd[a])throw Error("doXHR failed!");return h.jd[a]});if(a||!b)g=b=1,g=b=this.he(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ee=b;this.De=
g;this.Md=!0};if("undefined"!==typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.Md||this.Vd();return this.Ee}},chunkSize:{get:function(){this.Md||this.Vd();return this.De}}});var n=void 0}else n=c,h=void 0;var r=sc(a,b,d,e);h?r.qc=h:n&&(r.qc=null,r.url=n);Object.defineProperties(r,{uc:{get:function(){return this.qc.length}}});var t=
{};Object.keys(r.sc).forEach(function(a){var b=r.sc[a];t[a]=function(){if(!vc(r))throw new H(5);return b.apply(null,arguments)}});t.read=function(a,b,c,d,e){if(!vc(r))throw new H(5);a=a.node.qc;if(e>=a.length)return 0;d=Math.min(a.length-e,d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[e+g];else for(g=0;g<d;g++)b[c+g]=a.get(e+g);return d};r.sc=t;return r}
function xc(a,b,c,d,e,g,h,n,r,t){function u(c){function x(c){t&&t();n||tc(a,b,c,d,e,r);g&&g();fb(E)}var u=!1;k.preloadPlugins.forEach(function(a){!u&&a.canHandle(K)&&(a.handle(c,K,x,function(){h&&h();fb(E)}),u=!0)});u||x(c)}f.ie();var K=b?ub(G(a,b)):a,E="cp "+K;eb(E);"string"==typeof c?f.He(c,function(a){u(a)},h):u(c)}var yc={},Ub,$b,jc,zc={},P=0;function Q(){P+=4;return w[P-4>>2]}function Ac(){var a=Kb[Q()];if(!a)throw new H(9);return a}function Bc(){p()}function Ja(){return v.length}
f={pc:{Ec:null,method:"",Kc:0,Cc:null,Fc:0,Bd:0,Cd:0,Jc:0,se:[],pause:function(){f.pc.Ec=null;f.pc.Kc++},resume:function(){f.pc.Kc++;var a=f.pc.Bd,b=f.pc.Cd,c=f.pc.Cc;f.pc.Cc=null;Cc(c,0,!1,f.pc.Fc,!0);Dc(a,b);f.pc.Ec()},vf:function(){if(k.setStatus){var a=k.statusMessage||"Please wait...",b=f.pc.Rd,c=f.pc.Df;b?b<c?k.setStatus(a+" ("+(c-b)+"/"+c+")"):k.setStatus(a):k.setStatus("")}},gf:function(a){if(!(B||k.preMainLoop&&!1===k.preMainLoop())){try{a()}catch(b){if(b instanceof qa)return;b&&"object"===
typeof b&&b.stack&&l("exception thrown: "+[b,b.stack]);throw b;}k.postMainLoop&&k.postMainLoop()}}},Wc:!1,bd:!1,cf:[],workers:[],ie:function(){function a(){f.bd=document.pointerLockElement===k.canvas||document.mozPointerLockElement===k.canvas||document.webkitPointerLockElement===k.canvas||document.msPointerLockElement===k.canvas}k.preloadPlugins||(k.preloadPlugins=[]);if(!f.Ze){f.Ze=!0;try{f.od=!0}catch(c){f.od=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}f.BlobBuilder=
"undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:f.od?null:console.log("warning: no BlobBuilder");f.gd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;k.pe||"undefined"!==typeof f.gd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),k.pe=!0);k.preloadPlugins.push({canHandle:function(a){return!k.pe&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,
b,e,g){var c=null;if(f.od)try{c=new Blob([a],{type:f.Ld(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:f.Ld(b)}))}catch(t){ta("Blob constructor present but fails: "+t+"; falling back to blob builder")}c||(c=new f.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=f.gd.createObjectURL(c),r=new Image;r.onload=function(){assert(r.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=r.width;c.height=r.height;c.getContext("2d").drawImage(r,
0,0);k.preloadedImages[b]=c;f.gd.revokeObjectURL(d);e&&e(a)};r.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};r.src=d}});k.preloadPlugins.push({canHandle:function(a){return!k.Lf&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,g){function c(c){r||(r=!0,k.preloadedAudios[b]=c,e&&e(a))}function d(){r||(r=!0,k.preloadedAudios[b]=new Audio,g&&g())}var r=!1;if(f.od){try{var t=new Blob([a],{type:f.Ld(b)})}catch(K){return d()}t=f.gd.createObjectURL(t);var u=
new Audio;u.addEventListener("canplaythrough",function(){c(u)},!1);u.onerror=function(){if(!r){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,g=0,h=0;h<a.length;h++)for(e=e<<8|a[h],g+=8;6<=g;){var n=e>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[n]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&
15)<<2],d+="=");u.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(u)}};u.src=t;f.hf(function(){c(u)},1E4)}else return d()}});var b=k.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",
a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),k.elementPointerLock&&b.addEventListener("click",function(a){!f.bd&&k.canvas.requestPointerLock&&(k.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&k.Hc&&a==k.canvas)return k.Hc;var e;if(b){var g={antialias:!1,alpha:!1,le:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)g[h]=
d[h];if("undefined"!==typeof Ec&&(e=Fc(a,g)))var n=Gc[e].Uc}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof R,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),k.Hc=n,b&&(S=Gc[e],k.Hc=R=S&&S.Uc),k.Wf=b,f.cf.forEach(function(a){a()}),f.ie());return n},Bf:function(){},ee:!1,sd:void 0,Rc:void 0,requestFullscreen:function(a,b,c){function d(){f.Wc=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||
document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=f.exitFullscreen,f.sd&&e.requestPointerLock(),f.Wc=!0,f.Rc?f.lf():f.ed(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),f.Rc?f.mf():f.ed(e));if(k.onFullScreen)k.onFullScreen(f.Wc);if(k.onFullscreen)k.onFullscreen(f.Wc)}f.sd=a;f.Rc=b;f.Be=c;"undefined"===typeof f.sd&&(f.sd=!0);"undefined"===typeof f.Rc&&(f.Rc=!1);"undefined"===typeof f.Be&&(f.Be=null);var e=k.canvas;f.ee||(f.ee=!0,document.addEventListener("fullscreenchange",
d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");e.parentNode.insertBefore(g,e);g.appendChild(e);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:
null);c?g.requestFullscreen({Xf:c}):g.requestFullscreen()},te:function(a,b,c){l("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");f.te=function(a,b,c){return f.requestFullscreen(a,b,c)};return f.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!f.Wc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},Pc:0,Qe:function(a){var b=
Date.now();if(0===f.Pc)f.Pc=b+1E3/60;else for(;b+2>=f.Pc;)f.Pc+=1E3/60;setTimeout(a,Math.max(f.Pc-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=f.Qe;b(a)}},Qf:function(a){return function(){if(!B)return a.apply(null,arguments)}},Vc:!0,cd:[],Mf:function(){f.Vc=!1},Pf:function(){f.Vc=!0;if(0<f.cd.length){var a=f.cd;f.cd=[];a.forEach(function(a){a()})}},Rf:function(a){return f.requestAnimationFrame(function(){B||(f.Vc?a():f.cd.push(a))})},
hf:function(a,b){k.noExitRuntime=!0;return setTimeout(function(){B||(f.Vc?a():f.cd.push(a))},b)},Sf:function(a,b){k.noExitRuntime=!0;return setInterval(function(){B||f.Vc&&a()},b)},Ld:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Ue:function(a){return a.movementX||
a.mozMovementX||a.webkitMovementX||0},Ve:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},Te:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},Mc:0,Nc:0,ud:0,vd:0,touches:{},je:{},
Wd:function(a){if(f.bd)"mousemove"!=a.type&&"mozMovementX"in a?f.ud=f.vd=0:(f.ud=f.Ue(a),f.vd=f.Ve(a)),f.Mc+=f.ud,f.Nc+=f.vd;else{var b=k.canvas.getBoundingClientRect(),c=k.canvas.width,d=k.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var h=a.Vf;if(void 0!==h)if(e=h.pageX-(e+b.left),g=h.pageY-(g+b.top),e*=c/b.width,g*=
d/b.height,b={x:e,y:g},"touchstart"===a.type)f.je[h.identifier]=b,f.touches[h.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=f.touches[h.identifier])||(a=b),f.je[h.identifier]=a,f.touches[h.identifier]=b}else h=a.pageX-(e+b.left),a=a.pageY-(g+b.top),h*=c/b.width,a*=d/b.height,f.ud=h-f.Mc,f.vd=a-f.Nc,f.Mc=h,f.Nc=a}},He:function(a,b,c,d){var e=d?"":"al "+a;ma(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));e&&fb(e)},function(){if(c)c();
else throw'Loading data file "'+a+'" failed.';});e&&eb(e)},ue:[],Sd:function(){var a=k.canvas;f.ue.forEach(function(b){b(a.width,a.height)})},zd:function(a,b,c){f.ed(k.canvas,a,b);c||f.Sd()},$f:0,Zf:0,lf:function(){f.ed(k.canvas);f.Sd()},mf:function(){f.ed(k.canvas);f.Sd()},ed:function(a,b,c){b&&c?(a.wf=b,a.Xe=c):(b=a.wf,c=a.Xe);var d=b,e=c;k.forcedAspectRatio&&0<k.forcedAspectRatio&&(d/e<k.forcedAspectRatio?d=Math.round(e*k.forcedAspectRatio):e=Math.round(d/k.forcedAspectRatio));if((document.fullscreenElement||
document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}f.Rc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||
e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},Yf:{},oe:0,If:function(){var a=f.oe;f.oe++;return a}};
function Dc(a,b){f.pc.Bd=a;f.pc.Cd=b;if(f.pc.Cc)if(0==a)f.pc.Ec=function(){var a=Math.max(0,f.pc.pf+b-Bc())|0;setTimeout(f.pc.xd,a)},f.pc.method="timeout";else if(1==a)f.pc.Ec=function(){f.requestAnimationFrame(f.pc.xd)},f.pc.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);m?(void 0===k.setImmediates&&(k.setImmediates=
[]),k.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}f.pc.Ec=function(){setImmediate(f.pc.xd)};f.pc.method="immediate"}}
function Cc(a,b,c,d,e){k.noExitRuntime=!0;assert(!f.pc.Cc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");f.pc.Cc=a;f.pc.Fc=d;var g="undefined"!==typeof d?function(){k.dynCall_vi(a,d)}:function(){k.dynCall_v(a)};var h=f.pc.Kc;f.pc.xd=function(){if(!B)if(0<f.pc.se.length){var a=Date.now(),b=f.pc.se.shift();b.Cc(b.Fc);if(f.pc.Rd){var c=f.pc.Rd,d=0==c%1?c-1:Math.floor(c);
f.pc.Rd=b.zf?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");f.pc.vf();h<f.pc.Kc||setTimeout(f.pc.xd,0)}else h<f.pc.Kc||(f.pc.Jc=f.pc.Jc+1|0,1==f.pc.Bd&&1<f.pc.Cd&&0!=f.pc.Jc%f.pc.Cd?f.pc.Ec():(0==f.pc.Bd&&(f.pc.pf=Bc()),"undefined"!==typeof Ec&&S&&!Ec.Af&&!S.attributes.Ef&&S.Uc.Ne&&S.Uc.Ne(),"timeout"===f.pc.method&&k.Hc&&(l("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
f.pc.method=""),f.pc.gf(g),h<f.pc.Kc||f.pc.Ec()))};e||(b&&0<b?Dc(0,1E3/b):Dc(1,1),f.pc.Ec());if(c)throw"SimulateInfiniteLoop";}var Hc=0,Ic=!1;function Jc(){for(var a=Kc.length-1;0<=a;--a)Lc(a);Kc=[];Mc=[]}var Mc=[];function Nc(){if(Oc&&Pc.Ge)for(var a=0;a<Mc.length;++a){var b=Mc[a];Mc.splice(a,1);--a;b.Tf.apply(this,b.yf)}}var Oc=0,Pc=null,Kc=[];function Lc(a){var b=Kc[a];b.target.removeEventListener(b.md,b.Pe,b.Ae);Kc.splice(a,1)}
function Qc(a){function b(b){++Oc;Pc=a;Nc();a.We(b);Nc();--Oc}if(a.Le)a.Pe=b,a.target.addEventListener(a.md,b,a.Ae),Kc.push(a),Ic||(Za.push(Jc),Ic=!0);else for(var c=0;c<Kc.length;++c)Kc[c].target==a.target&&Kc[c].md==a.md&&Lc(c--)}function Rc(a){return a===a+0?D(a):a}var Sc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function Tc(a,b,c,d,e,g){Hc||(Hc=Fa(1684));a=Sc[a]||("undefined"!==typeof document?document.querySelector(Rc(a)):void 0);Qc({target:a,Ge:"touchstart"==g||"touchend"==g,md:g,Le:d,We:function(c){c=c||event;for(var g={},h=0;h<c.touches.length;++h){var t=c.touches[h];t.Xd=!1;g[t.identifier]=t}for(h=0;h<c.changedTouches.length;++h)t=c.changedTouches[h],g[t.identifier]=t,t.Xd=!0;for(h=0;h<c.targetTouches.length;++h)t=c.targetTouches[h],g[t.identifier].ef=!0;var u=t=Hc;w[u+4>>2]=c.ctrlKey;w[u+8>>2]=c.shiftKey;
w[u+12>>2]=c.altKey;w[u+16>>2]=c.metaKey;u+=20;var K=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},E=0;for(h in g){var x=g[h];w[u>>2]=x.identifier;w[u+4>>2]=x.screenX;w[u+8>>2]=x.screenY;w[u+12>>2]=x.clientX;w[u+16>>2]=x.clientY;w[u+20>>2]=x.pageX;w[u+24>>2]=x.pageY;w[u+28>>2]=x.Xd;w[u+32>>2]=x.ef;w[u+36>>2]=x.clientX-K.left;w[u+40>>2]=x.clientY-K.top;u+=52;if(32<=++E)break}w[t>>2]=E;Uc(d,e,t,b)&&c.preventDefault()},Ae:c})}
function Vc(a){if(0===a)return 0;a=D(a);if(!F.hasOwnProperty(a))return 0;Vc.vc&&Wc(Vc.vc);a=F[a];var b=Na(a)+1,c=Fa(b);c&&Ma(a,v,c,b);Vc.vc=c;return Vc.vc}var Xc=1,Yc=0,Zc=[],T=[],$c=[],ad=[],bd=[],cd=[],U=[],dd=[],Gc={},S=null,ed=[],fd={},gd={},hd=4;function V(a){Yc||(Yc=a)}function id(a){for(var b=Xc++,c=a.length;c<b;c++)a[c]=null;return b}var jd=null,kd=[0];function Fc(a,b){return(a=1<b.le?a.getContext("webgl2",b):a.getContext("webgl",b)||a.getContext("experimental-webgl",b))?ld(a,b):0}
function ld(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=Fa(8),e={handle:d,attributes:b,version:b.le,Uc:a};e.Ad=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.xf=e);Gc[d]=e;("undefined"===typeof b.Oe||b.Oe)&&md(e);return d}
function nd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,g){b.drawArraysInstancedANGLE(a,d,e,g)},a.drawElementsInstanced=function(a,d,e,g,h){b.drawElementsInstancedANGLE(a,d,e,g,h)})}
function od(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function pd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function md(a){a||(a=S);if(!a.Ye){a.Ye=!0;var b=a.Uc;2>a.version&&(nd(b),od(b),pd(b));b.Cf=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var Ec={},qd,rd,sd=[];function td(a,b,c,d){for(var e=0;e<a;e++){var g=R[c](),h=g&&id(d);g?(g.name=h,d[h]=g):V(1282);w[b+4*e>>2]=h}}
function ud(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=R.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>S.version){V(1282);return}d=R.getSupportedExtensions();c=null===d?0:2*d.length;break;case 33307:case 33308:if(2>S.version){V(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=R.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V(1280);return;case "object":if(null===
d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=0;break;default:V(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V(1280);l("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:V(1280);l("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+
a+") and it returns "+d+" of type "+typeof d+"!");return}w[b>>2]=c}else V(1281)}function vd(a){var b=Na(a)+1,c=Fa(b);Ma(a,C,c,b);return c}var wd={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},xd={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function yd(a,b,c,d,e){if(b=wd[b]*xd[a]){var g=hd;c=e+d*(c*b+g-1&-g);switch(a){case 5120:return v.subarray(e,c);case 5121:return C.subarray(e,c);case 5122:return xa.subarray(e>>1,c>>1);case 5124:return w.subarray(e>>2,c>>2);case 5126:return A.subarray(e>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:return Sa.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Ra.subarray(e>>1,c>>1);default:V(1280)}}else V(1280)}
function zd(a){switch(a){case 5120:return v;case 5121:return C;case 5122:return xa;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Ra;case 5124:return w;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return Sa;case 5126:return A}}var Ad={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1};
function Bd(a,b,c,d,e){this.id=a;this.y=this.x=0;this.Kd=!1;this.ye=this.xe=0;this.width=b;this.height=c;this.we=b;this.ve=c;this.title=d;this.share=e;this.attributes=Cd;this.pd={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.Id=[];this.hd=this.rd=this.$d=this.yd=this.kd=this.ld=this.td=this.de=this.Gd=this.Tc=this.Ce=this.title=null}function W(a){return 0>=a||!X?null:X[a-1]}
var Dd=null,Ed=null,Y=null,X=null,Fd=null,Gd=null,Cd=null,Hd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Id(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Jd(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Kd(a){Y&&Y.hd&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||Ld(Y.hd,Y.id,a))}function Md(a,b){if(Y){var c=Id(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Id[a]=b;Y.rd&&(d&&(b=2),Nd(Y.rd,Y.id,c,a,b,Jd()))}}}
function Od(){Pd()}function Qd(){Pd()}function Rd(a){Md(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Sd(a){Md(a.keyCode,0)}function Td(){if(Y)for(var a=0;a<Y.Id.length;++a)Y.Id[a]&&Md(a,0)}function Ud(a){Y&&(f.Wd(a),a.target==k.canvas&&Y.ld&&Vd(Y.ld,Y.id,f.Mc,f.Nc))}function Wd(a){Y&&a.target==k.canvas&&Y.kd&&Ld(Y.kd,Y.id,1)}function Xd(a){Y&&a.target==k.canvas&&Y.kd&&Ld(Y.kd,Y.id,0)}
function Yd(a,b){if(Y&&(f.Wd(a),a.target==k.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.td&&Zd(Y.td,Y.id,c,b,Jd())}}function $d(a){Y&&Yd(a,1)}function ae(a){Y&&Yd(a,0)}function be(a){f.Te(a);if(Y&&Y.yd&&a.target==k.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;Vd(Y.yd,Y.id,b,c);a.preventDefault()}}
function ce(){(k.canvas.requestFullscreen||k.canvas.mozRequestFullScreen||k.canvas.webkitRequestFullScreen||function(){}).apply(k.canvas,[])}var Z={},de=null,ee=null;
function Pd(){if(f.pc.Jc!==ee||!f.pc.Jc){de=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;ee=f.pc.Jc;for(var a=0;a<de.length;++a){var b=de[a];if(b){Z[a]||(console.log("glfw joystick connected:",a),Z[a]={id:Ea(zb(b.id),"i8"),Je:b.buttons.length,Ie:b.axes.length,buttons:Ea(Array(b.buttons.length),"i8"),axes:Ea(Array(4*b.axes.length),"float")});for(var c=Z[a],d=0;d<b.buttons.length;++d)q(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)q(c.axes+
4*d,b.axes[d],"float")}else Z[a]&&(console.log("glfw joystick disconnected",a),Wc(Z[a].id),Wc(Z[a].buttons),Wc(Z[a].axes),delete Z[a])}}}function fe(a){if(Y&&Y.$d&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1}function ge(a){if(Y&&Y.$d)return a.preventDefault(),!1}function he(a){!f.bd&&k.canvas.requestPointerLock&&(k.canvas.requestPointerLock(),a.preventDefault())}function ie(){ie.vc||(ie.vc=[]);ie.vc.push(je());return ie.vc.length-1}
function ke(a){a=Qa(a);var b=buffer.byteLength;try{return-1!==Da.grow((a-b)/65536)?(buffer=Da.buffer,!0):!1}catch(c){return!1}}function le(a){return 0===a%4&&(0!==a%100||0===a%400)}function me(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var ne=[31,29,31,30,31,30,31,31,30,31,30,31],oe=[31,28,31,30,31,30,31,31,30,31,30,31];
function pe(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(le(a.getFullYear())?ne:oe)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function qe(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return e(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function r(a){a=pe(new Date(a.xc+1900,0,1),a.Fd);var b=n(new Date(a.getFullYear()+1,0,4));return 0>=h(n(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var t=w[d+40>>2];d={sf:w[d>>2],rf:w[d+4>>2],Dd:w[d+8>>2],dd:w[d+12>>2],Sc:w[d+16>>2],xc:w[d+20>>2],Ed:w[d+24>>2],Fd:w[d+28>>2],Uf:w[d+32>>2],qf:w[d+36>>2],
tf:t?D(t):""};c=D(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in t)c=c.replace(new RegExp(u,"g"),t[u]);var K="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
E="January February March April May June July August September October November December".split(" ");t={"%a":function(a){return K[a.Ed].substring(0,3)},"%A":function(a){return K[a.Ed]},"%b":function(a){return E[a.Sc].substring(0,3)},"%B":function(a){return E[a.Sc]},"%C":function(a){return g((a.xc+1900)/100|0,2)},"%d":function(a){return g(a.dd,2)},"%e":function(a){return e(a.dd,2," ")},"%g":function(a){return r(a).toString().substring(2)},"%G":function(a){return r(a)},"%H":function(a){return g(a.Dd,
2)},"%I":function(a){a=a.Dd;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.dd+me(le(a.xc+1900)?ne:oe,a.Sc-1),3)},"%m":function(a){return g(a.Sc+1,2)},"%M":function(a){return g(a.rf,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.Dd&&12>a.Dd?"AM":"PM"},"%S":function(a){return g(a.sf,2)},"%t":function(){return"\t"},"%u":function(a){return a.Ed||7},"%U":function(a){var b=new Date(a.xc+1900,0,1),c=0===b.getDay()?b:pe(b,7-b.getDay());a=new Date(a.xc+1900,a.Sc,a.dd);return 0>
h(c,a)?g(Math.ceil((31-c.getDate()+(me(le(a.getFullYear())?ne:oe,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.xc+1900,0,4)),c=n(new Date(a.xc+1901,0,4)),d=pe(new Date(a.xc+1900,0,1),a.Fd);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.xc+1900?a.Fd+32-b.getDate():a.Fd+1-b.getDate())/7),2)},"%w":function(a){return a.Ed},"%W":function(a){var b=new Date(a.xc,0,1),c=1===b.getDay()?b:pe(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.xc+
1900,a.Sc,a.dd);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(me(le(a.getFullYear())?ne:oe,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.xc+1900).toString().substring(2)},"%Y":function(a){return a.xc+1900},"%z":function(a){a=a.qf;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.tf},"%%":function(){return"%"}};for(u in t)0<=c.indexOf(u)&&(c=c.replace(new RegExp(u,"g"),t[u](d)));u=zb(c,!1);if(u.length>
b)return 0;v.set(u,a);return u.length-1}nc();Mb=Array(4096);ac(I,"/");N("/tmp");N("/home");N("/home/web_user");
(function(){N("/dev");xb(259,{read:function(){return 0},write:function(a,b,c,h){return h}});cc("/dev/null",259);wb(1280,Bb);wb(1536,Cb);cc("/dev/tty",1280);cc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){p("random_device")});O("/dev","random",b);O("/dev","urandom",b);
N("/dev/shm");N("/dev/shm/tmp")})();N("/proc");N("/proc/self");N("/proc/self/fd");ac({yc:function(){var a=Eb("/proc/self","fd",16895,73);a.rc={lookup:function(a,c){var b=Kb[+c];if(!b)throw new H(9);a={parent:null,yc:{ne:"fake"},rc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");k.FS_createFolder=qc;k.FS_createPath=rc;k.FS_createDataFile=tc;k.FS_createPreloadedFile=xc;k.FS_createLazyFile=wc;k.FS_createLink=uc;k.FS_createDevice=O;k.FS_unlink=ec;
if(ia){var fs=require("fs"),Hb=require("path");L.nf()}ha?Bc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Bc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?Bc=function(){return performance.now()}:Bc=Date.now;k.requestFullScreen=function(a,b,c){l("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");k.requestFullScreen=k.requestFullscreen;f.te(a,b,c)};
k.requestFullscreen=function(a,b,c){f.requestFullscreen(a,b,c)};k.requestAnimationFrame=function(a){f.requestAnimationFrame(a)};k.setCanvasSize=function(a,b,c){f.zd(a,b,c)};k.pauseMainLoop=function(){f.pc.pause()};k.resumeMainLoop=function(){f.pc.resume()};k.getUserMedia=function(){f.getUserMedia()};k.createContext=function(a,b,c,d){return f.createContext(a,b,c,d)};var R;jd=new Float32Array(256);for(var re=0;256>re;re++)kd[re]=jd.subarray(0,re+1);for(var se=0;32>se;se++)sd.push(Array(se));
function zb(a,b){var c=Array(Na(a)+1);a=Ma(a,c,0,c.length);b&&(c.length=a);return c}
var ye=k.asm({},{c:p,Wb:nb,g:function(a){return Fa(a)},fb:function(){B=!0;throw"Pure virtual function called!";},f:function(a){"uncaught_exception"in te?te.re++:te.re=1;throw a;},_a:function(){return te.re},na:function(){},Ua:function(){ob(1);return-1},ja:ob,Oa:function(a,b){P=b;try{var c=Ac(),d=Q(),e=Q(),g=Q(),h=Q();a=4294967296*d+(e>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-75;lc(c,a,h);y=[c.position>>>0,(z=c.position,1<=+ya(z)?0<z?(za(+Aa(z/4294967296),4294967295)|0)>>>0:~~+Ba((z-
+(~~z>>>0))/4294967296)>>>0:0)];w[g>>2]=y[0];w[g+4>>2]=y[1];c.Ic&&0===a&&0===h&&(c.Ic=null);return 0}catch(n){return"undefined"!==typeof yc&&n instanceof H||p(n),-n.tc}},Vb:function(a,b){P=b;try{var c=Ac(),d=Q();a:{var e=Q();for(b=a=0;b<e;b++){var g=w[d+(8*b+4)>>2],h=c,n=w[d+8*b>>2],r=g,t=void 0,u=v;if(0>r||0>t)throw new H(22);if(null===h.fd)throw new H(9);if(1===(h.flags&2097155))throw new H(9);if(J(h.node.mode))throw new H(21);if(!h.sc.read)throw new H(22);var K="undefined"!==typeof t;if(!K)t=h.position;
else if(!h.seekable)throw new H(29);var E=h.sc.read(h,u,n,r,t);K||(h.position+=E);var x=E;if(0>x){var ic=-1;break a}a+=x;if(x<g)break}ic=a}return ic}catch(Ab){return"undefined"!==typeof yc&&Ab instanceof H||p(Ab),-Ab.tc}},Ja:function(a,b){P=b;try{var c=Ac(),d=Q();a:{var e=Q();for(b=a=0;b<e;b++){var g=mc(c,v,w[d+8*b>>2],w[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(n){return"undefined"!==typeof yc&&n instanceof H||p(n),-n.tc}},Jb:function(a,b){P=b;try{var c=Ac(),d=Q(),e=
Q();if(!c.Ic){var g=M(c.path,{nd:!0}).node;if(!g.rc.readdir)throw new H(20);var h=g.rc.readdir(g);c.Ic=h}a=0;for(var n=lc(c,0,1),r=Math.floor(n/280);r<c.Ic.length&&a+280<=e;){var t=c.Ic[r];if("."===t[0]){var u=1;var K=4}else{var E=Gb(c.node,t);u=E.id;K=8192===(E.mode&61440)?2:J(E.mode)?4:40960===(E.mode&61440)?10:8}y=[u>>>0,(z=u,1<=+ya(z)?0<z?(za(+Aa(z/4294967296),4294967295)|0)>>>0:~~+Ba((z-+(~~z>>>0))/4294967296)>>>0:0)];w[d+a>>2]=y[0];w[d+a+4>>2]=y[1];y=[280*(r+1)>>>0,(z=280*(r+1),1<=+ya(z)?0<
z?(za(+Aa(z/4294967296),4294967295)|0)>>>0:~~+Ba((z-+(~~z>>>0))/4294967296)>>>0:0)];w[d+a+8>>2]=y[0];w[d+a+12>>2]=y[1];xa[d+a+16>>1]=280;v[d+a+18>>0]=K;Ma(t,C,d+a+19,256);a+=280;r+=1}lc(c,280*r,0);return a}catch(x){return"undefined"!==typeof yc&&x instanceof H||p(x),-x.tc}},E:function(a,b){P=b;try{var c=Ac();switch(Q()){case 0:var d=Q();return 0>d?-22:hc(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Q(),c.flags|=d,0;case 12:return d=Q(),xa[d+0>>1]=2,0;case 13:case 14:return 0;
case 16:case 8:return-22;case 9:return ob(22),-1;default:return-22}}catch(e){return"undefined"!==typeof yc&&e instanceof H||p(e),-e.tc}},Ba:function(a,b){P=b;try{var c=D(Q()),d=Q(),e=Q();return hc(c,d,e).fd}catch(g){return"undefined"!==typeof yc&&g instanceof H||p(g),-g.tc}},wa:function(a,b){P=b;try{var c=Ac(),d=Q();switch(d){case 21509:case 21505:return c.tty?0:-25;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-25;case 21519:if(!c.tty)return-25;var e=Q();return w[e>>
2]=0;case 21520:return c.tty?-22:-25;case 21531:a=e=Q();if(!c.sc.$e)throw new H(25);return c.sc.$e(c,d,a);case 21523:return c.tty?0:-25;case 21524:return c.tty?0:-25;default:p("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof yc&&g instanceof H||p(g),-g.tc}},P:function(a,b){P=b;try{var c=Ac();kc(c);return 0}catch(d){return"undefined"!==typeof yc&&d instanceof H||p(d),-d.tc}},pb:function(a,b){P=b;try{var c=Q(),d=Q();if(-1===c||0===d)var e=-22;else{var g=zc[c];if(g&&d===g.Jf){var h=Kb[g.fd],
n=g.flags,r=new Uint8Array(C.subarray(c,c+d));h&&h.sc.wd&&h.sc.wd(h,r,0,d,n);zc[c]=null;g.Fe&&Wc(g.Kf)}e=0}return e}catch(t){return"undefined"!==typeof yc&&t instanceof H||p(t),-t.tc}},D:function(){},b:function(){k.abort()},ob:function(a,b){if(0===a)a=Date.now();else if(1===a&&(ha||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=Bc();else return ob(22),-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0},nb:Ja,mb:function(a,b,c){C.set(C.subarray(b,
b+c),a)},lb:function(a){if(2147418112<a)return!1;for(var b=Math.max(Ja(),16777216);b<a;)536870912>=b?b=Qa(2*b):b=Math.min(Qa((3*b+2147483648)/4),2147418112);if(!ke(b))return!1;Ta();return!0},kb:Cc,jb:function(a,b,c,d){Tc(a,b,c,d,25,"touchcancel");return 0},ib:function(a,b,c,d){Tc(a,b,c,d,23,"touchend");return 0},hb:function(a,b,c,d){Tc(a,b,c,d,24,"touchmove");return 0},gb:function(a,b,c,d){Tc(a,b,c,d,22,"touchstart");return 0},ua:function(a){ue(a)},O:Vc,j:function(a){R.activeTexture(a)},aa:function(a,
b){R.attachShader(T[a],U[b])},i:function(a,b){35051==a?R.Zd=b:35052==a&&(R.Hd=b);R.bindBuffer(a,Zc[b])},ta:function(a,b,c){R.bindBufferBase(a,b,Zc[c])},k:function(a,b){R.bindFramebuffer(a,$c[b])},eb:function(a,b){R.bindRenderbuffer(a,ad[b])},sa:function(a,b){R.bindSampler(a,ed[b])},d:function(a,b){R.bindTexture(a,bd[b])},u:function(a){R.bindVertexArray(dd[a])},db:function(a){R.blendEquation(a)},cb:function(a,b){R.blendEquationSeparate(a,b)},ra:function(a,b){R.blendFunc(a,b)},bb:function(a,b,c,d){R.blendFuncSeparate(a,
b,c,d)},y:function(a,b,c,d){S.Ad?c?R.bufferData(a,C,d,c,b):R.bufferData(a,b,d):R.bufferData(a,c?C.subarray(c,c+b):b,d)},t:function(a,b,c,d){S.Ad?R.bufferSubData(a,b,C,d,c):R.bufferSubData(a,b,C.subarray(d,d+c))},qa:function(a){return R.checkFramebufferStatus(a)},ab:function(a){R.clear(a)},C:function(a,b,c){R.clearBufferfv(a,b,A,c>>2)},$a:function(a,b,c,d){R.clearColor(a,b,c,d)},$:function(a){R.compileShader(U[a])},pa:function(){var a=id(T),b=R.createProgram();b.name=a;T[a]=b;return a},N:function(a){var b=
id(U);U[b]=R.createShader(a);return b},x:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Zc[d];e&&(R.deleteBuffer(e),e.name=0,Zc[d]=null,d==qd&&(qd=0),d==rd&&(rd=0),d==R.Zd&&(R.Zd=0),d==R.Hd&&(R.Hd=0))}},Za:function(a,b){for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=$c[d];e&&(R.deleteFramebuffer(e),e.name=0,$c[d]=null)}},oa:function(a){if(a){var b=T[a];b?(R.deleteProgram(b),b.name=0,T[a]=null,fd[a]=null):V(1281)}},Ya:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=ad[d];e&&(R.deleteRenderbuffer(e),
e.name=0,ad[d]=null)}},M:function(a){if(a){var b=U[a];b?(R.deleteShader(b),U[a]=null):V(1281)}},L:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=bd[d];e&&(R.deleteTexture(e),e.name=0,bd[d]=null)}},_:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];R.deleteVertexArray(dd[d]);dd[d]=null}},Z:function(a){R.depthMask(!!a)},Y:function(a,b){R.detachShader(T[a],U[b])},o:function(a){R.disable(a)},ma:function(a,b,c){R.drawArrays(a,b,c)},Xa:function(a,b){for(var c=sd[a],d=0;d<a;d++)c[d]=w[b+4*d>>
2];R.drawBuffers(c)},Wa:function(a,b,c,d){R.drawElements(a,b,c,d)},m:function(a){R.enable(a)},B:function(a){R.enableVertexAttribArray(a)},Va:function(a,b,c,d){R.framebufferRenderbuffer(a,b,c,ad[d])},X:function(a,b,c,d,e){R.framebufferTexture2D(a,b,c,bd[d],e)},w:function(a,b){td(a,b,"createBuffer",Zc)},la:function(a,b){td(a,b,"createFramebuffer",$c)},Ta:function(a,b){td(a,b,"createRenderbuffer",ad)},n:function(a,b){td(a,b,"createTexture",bd)},W:function(a,b){td(a,b,"createVertexArray",dd)},Sa:function(a){R.generateMipmap(a)},
Ra:function(a,b,c,d){if(d)switch(a=T[a],c){case 35393:a=R.getActiveUniformBlockName(a,b);w[d>>2]=a.length+1;break;default:if(a=R.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)w[d>>2]=a;else for(b=0;b<a.length;b++)w[d+4*b>>2]=a[b]}else V(1281)},V:function(a,b){return R.getAttribLocation(T[a],D(b))},e:function(a,b){ud(a,b)},ka:function(a,b,c,d){a=R.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ma(a,C,d,b):0;c&&(w[c>>2]=b)},K:function(a,b,c){if(c)if(a>=Xc)V(1281);else{var d=
fd[a];if(d)if(35716==b)a=R.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b)w[c>>2]=d.Nd;else if(35722==b){if(-1==d.Xc){a=T[a];var e=R.getProgramParameter(a,35721);for(b=d.Xc=0;b<e;++b)d.Xc=Math.max(d.Xc,R.getActiveAttrib(a,b).name.length+1)}w[c>>2]=d.Xc}else if(35381==b){if(-1==d.Yc)for(a=T[a],e=R.getProgramParameter(a,35382),b=d.Yc=0;b<e;++b)d.Yc=Math.max(d.Yc,R.getActiveUniformBlockName(a,b).length+1);w[c>>2]=d.Yc}else w[c>>2]=R.getProgramParameter(T[a],
b);else V(1282)}else V(1281)},ia:function(a,b,c,d){a=R.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ma(a,C,d,b):0;c&&(w[c>>2]=b)},J:function(a,b,c){c?35716==b?(a=R.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1):35720==b?(a=R.getShaderSource(U[a]),w[c>>2]=null===a||0==a.length?0:a.length+1):w[c>>2]=R.getShaderParameter(U[a],b):V(1281)},I:function(a){if(gd[a])return gd[a];switch(a){case 7939:var b=R.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),
c.push("GL_"+b[d]);b=vd(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=R.getParameter(a))||V(1280);b=vd(b);break;case 7938:b=R.getParameter(R.VERSION);b=2<=S.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=vd(b);break;case 35724:b=R.getParameter(R.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=vd(b);break;default:return V(1280),0}return gd[a]=b},ha:function(a,
b){return R.getUniformBlockIndex(T[a],D(b))},U:function(a,b){b=D(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=fd[a]&&fd[a].ze[b])&&0<=c&&c<a[0]?a[1]+c:-1},H:function(a){return R.isEnabled(a)},ga:function(a){R.linkProgram(T[a]);var b=T[a];a=fd[a]={ze:{},Nd:0,Xc:-1,Yc:-1};for(var c=a.ze,d=R.getProgramParameter(b,35718),e=0;e<d;++e){var g=R.getActiveUniform(b,e),h=g.name;a.Nd=Math.max(a.Nd,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,
h.lastIndexOf("[")));var n=R.getUniformLocation(b,h);if(n){var r=id(cd);c[h]=[g.size,r];cd[r]=n;for(var t=1;t<g.size;++t)n=R.getUniformLocation(b,h+"["+t+"]"),r=id(cd),cd[r]=n}}},Qa:function(a,b){3317==a&&(hd=b);R.pixelStorei(a,b)},Pa:function(a,b,c,d){R.renderbufferStorage(a,b,c,d)},fa:function(a,b,c,d){R.scissor(a,b,c,d)},T:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?w[d+4*g>>2]:-1;e+=D(w[c+4*g>>2],0>h?void 0:h)}R.shaderSource(U[a],e)},v:function(a,b,c,d,e,g,h,n,r){S.Ad?R.Hd?R.texImage2D(a,
b,c,d,e,g,h,n,r):0!=r?R.texImage2D(a,b,c,d,e,g,h,n,zd(n),r>>(Ad[n]|0)):R.texImage2D(a,b,c,d,e,g,h,n,null):R.texImage2D(a,b,c,d,e,g,h,n,r?yd(n,h,d,e,r):null)},S:function(a,b,c){R.texParameterf(a,b,c)},h:function(a,b,c){R.texParameteri(a,b,c)},ea:function(a,b){R.uniform1i(cd[a],b)},da:function(a,b,c){a=T[a];R.uniformBlockBinding(a,b,c)},Na:function(a,b,c,d){if(S.Ad)R.uniformMatrix4fv(cd[a],!!c,A,d>>2,16*b);else{if(256>=16*b)for(var e=kd[16*b-1],g=0;g<16*b;g+=16)e[g]=A[d+4*g>>2],e[g+1]=A[d+(4*g+4)>>
2],e[g+2]=A[d+(4*g+8)>>2],e[g+3]=A[d+(4*g+12)>>2],e[g+4]=A[d+(4*g+16)>>2],e[g+5]=A[d+(4*g+20)>>2],e[g+6]=A[d+(4*g+24)>>2],e[g+7]=A[d+(4*g+28)>>2],e[g+8]=A[d+(4*g+32)>>2],e[g+9]=A[d+(4*g+36)>>2],e[g+10]=A[d+(4*g+40)>>2],e[g+11]=A[d+(4*g+44)>>2],e[g+12]=A[d+(4*g+48)>>2],e[g+13]=A[d+(4*g+52)>>2],e[g+14]=A[d+(4*g+56)>>2],e[g+15]=A[d+(4*g+60)>>2];else e=A.subarray(d>>2,d+64*b>>2);R.uniformMatrix4fv(cd[a],!!c,e)}},G:function(a){R.useProgram(T[a])},A:function(a,b,c,d,e,g){R.vertexAttribPointer(a,b,c,!!d,
e,g)},s:function(a,b,c,d){R.viewport(a,b,c,d)},r:function(){},Ma:function(a,b,c,d,e){var g;for(g=0;g<X.length&&null!==X[g];g++);if(0<g)throw"glfwCreateWindow only supports one window at time currently";var h=g+1;if(0>=a||0>=b)h=0;else{d?ce():f.zd(a,b);for(g=0;g<X.length&&null==X[g];g++);g==X.length&&(k.Hc=f.createContext(k.canvas,!0,!0,{antialias:1<Cd[135181],depth:0<Cd[135173],stencil:0<Cd[135174],alpha:0<Cd[135172]}));k.Hc?(a=new Bd(h,a,b,c,e),h-1==X.length?X.push(a):X[h-1]=a,Y=a,h=a.id):h=0}return h},
Ub:function(){throw"glfwCreateWindowSurface is not implemented.";},Tb:function(){},La:function(a){a:{if(a=W(a)){a.Gd&&ve(a.Gd,a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}k.Hc=void 0}a=void 0}return a},Sb:function(){},Rb:function(){},Ka:function(a,b,c){q(b,f.Mc,"double");q(c,f.Nc,"double")},Qb:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.width,e=a.height;q(b,d,"i32");q(c,e,"i32")},Pb:function(a,b){if(a=W(a)){switch(b){case 208897:a.pd[b]=f.bd?212995:
212993}return a.pd[b]}},Ob:function(a,b){Pd();if((a=Z[a])&&a.axes)return q(b,a.Ie,"i32"),a.axes;q(b,0,"i32")},Nb:function(a,b){Pd();if((a=Z[a])&&a.buttons)return q(b,a.Je,"i32"),a.buttons;q(b,0,"i32")},z:function(a,b){return(a=W(a))?a.keys[b]:0},Mb:function(a,b,c){q(b,0,"i32");q(c,0,"i32")},Lb:function(a){q(a,1,"i32");Fd||(Fd=Ea([1,0,0,0],"i32"));return Fd},R:function(a,b){return(a=W(a))?0<(a.buttons&1<<b):0},Q:function(){return Bc()/1E3-Gd},Kb:function(){return 0},Ia:function(a,b){return(a=W(a))?
a.attributes[b]:0},Ha:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.x,e=a.y;q(b,d,"i32");q(c,e,"i32")},ca:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.width,e=a.height;q(b,d,"i32");q(c,e,"i32")},Ib:function(){if(X)return 1;Gd=Bc()/1E3;Cd=Hd;X=[];Y=null;window.addEventListener("gamepadconnected",Od,!0);window.addEventListener("gamepaddisconnected",Qd,!0);window.addEventListener("keydown",Rd,!0);window.addEventListener("keypress",Kd,!0);window.addEventListener("keyup",Sd,!0);window.addEventListener("blur",
Td,!0);k.canvas.addEventListener("mousemove",Ud,!0);k.canvas.addEventListener("mousedown",$d,!0);k.canvas.addEventListener("mouseup",ae,!0);k.canvas.addEventListener("wheel",be,!0);k.canvas.addEventListener("mousewheel",be,!0);k.canvas.addEventListener("mouseenter",Wd,!0);k.canvas.addEventListener("mouseleave",Xd,!0);k.canvas.addEventListener("drop",fe,!0);k.canvas.addEventListener("dragover",ge,!0);f.ue.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||
document.webkitIsFullScreen?(Y.xe=Y.x,Y.ye=Y.y,Y.we=Y.width,Y.ve=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Kd=!0):1==Y.Kd?(Y.x=Y.xe,Y.y=Y.ye,Y.width=Y.we,Y.height=Y.ve,Y.Kd=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(f.zd(Y.width,Y.height,!0),Y&&Y.Tc&&we(Y.Tc,Y.id,Y.width,Y.height),Y&&Y.de&&we(Y.de,Y.id,Y.width,Y.height))}});return 1},F:function(){},Hb:function(){},Ga:function(a,b){if(a=W(a)){var c=a.hd;a.hd=b;b=c}else b=null;return b},Gb:function(){},Fb:function(){},
Eb:function(){},Db:function(a,b){if(a=W(a)){var c=a.ld;a.ld=b;b=c}else b=null;return b},Cb:function(a){var b=Dd;Dd=a;return b},Fa:function(a,b,c){if(a=W(a))switch(b){case 208897:switch(c){case 212993:a.pd[b]=c;k.canvas.removeEventListener("click",he,!0);k.canvas.exitPointerLock();break;case 212994:console.log("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented.");break;case 212995:a.pd[b]=c;k.canvas.addEventListener("click",he,!0);k.canvas.requestPointerLock();break;default:console.log("glfwSetInputMode called with unknown value parameter value: "+
c+".")}break;case 208898:console.log("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented.");break;case 208899:console.log("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented.");break;default:console.log("glfwSetInputMode called with unknown mode parameter value: "+b+".")}},Ea:function(a,b){if(a=W(a)){var c=a.rd;a.rd=b;b=c}else b=null;return b},Bb:function(a){var b=Ed;Ed=a;return b},Da:function(a,b){if(a=W(a)){var c=a.td;a.td=b;b=c}else b=null;return b},Ca:function(a,
b){if(a=W(a)){var c=a.yd;a.yd=b;b=c}else b=null;return b},Ab:function(a,b){if(a=W(a)){var c=a.Gd;a.Gd=b;b=c}else b=null;return b},ba:function(a,b,c){if(a=W(a))a.x=b,a.y=c},zb:function(a,b){a=W(a);if(!a)return null;var c=a.Ce;a.Ce=b;return c},yb:function(a,b,c){if(a=W(a))Y.id==a.id&&(b==screen.width&&c==screen.height?ce():(f.exitFullscreen(),f.zd(b,c),a.width=b,a.height=c)),a.Tc&&we(a.Tc,a.id,b,c)},Aa:function(a,b){if(a=W(a)){var c=a.Tc;a.Tc=b;b=c}else b=null;return b},xb:function(a,b){if(a=W(a))a.title=
D(b),Y.id==a.id&&(document.title=a.title)},wb:function(){},za:function(){},ya:function(a){a=Math.abs(a);0==a?Dc(0,0):Dc(1,a)},xa:function(){window.removeEventListener("gamepadconnected",Od,!0);window.removeEventListener("gamepaddisconnected",Qd,!0);window.removeEventListener("keydown",Rd,!0);window.removeEventListener("keypress",Kd,!0);window.removeEventListener("keyup",Sd,!0);window.removeEventListener("blur",Td,!0);k.canvas.removeEventListener("mousemove",Ud,!0);k.canvas.removeEventListener("mousedown",
$d,!0);k.canvas.removeEventListener("mouseup",ae,!0);k.canvas.removeEventListener("wheel",be,!0);k.canvas.removeEventListener("mousewheel",be,!0);k.canvas.removeEventListener("mouseenter",Wd,!0);k.canvas.removeEventListener("mouseleave",Xd,!0);k.canvas.removeEventListener("drop",fe,!0);k.canvas.removeEventListener("dragover",ge,!0);k.canvas.width=k.canvas.height=1;Y=X=null},l:function(a,b){Cd[a]=b},vb:function(a){return Math.pow(2,a)},ub:function(a){return Math.log(a)/Math.LN2},q:function(a){var b=
ie.vc[a];ie.vc.splice(a,1);xe(b)},p:ie,va:function(){p("trap!")},tb:function(){return 0},sb:function(a,b,c,d){return qe(a,b,c,d)},rb:function(a){var b=Date.now()/1E3|0;a&&(w[a>>2]=b);return b},qb:function(){p("OOM")},a:Ia},buffer);k.asm=ye;var te=k.__ZSt18uncaught_exceptionv=function(){return k.asm.Xb.apply(null,arguments)};k.___em_js__get_orientation=function(){return k.asm.Yb.apply(null,arguments)};k.___em_js__screent_height=function(){return k.asm.Zb.apply(null,arguments)};
k.___em_js__screent_width=function(){return k.asm._b.apply(null,arguments)};k.___errno_location=function(){return k.asm.$b.apply(null,arguments)};var Wc=k._free=function(){return k.asm.ac.apply(null,arguments)};k._main=function(){return k.asm.bc.apply(null,arguments)};
var Fa=k._malloc=function(){return k.asm.cc.apply(null,arguments)},mb=k.globalCtors=function(){return k.asm.lc.apply(null,arguments)},Pa=k.stackAlloc=function(){return k.asm.mc.apply(null,arguments)},xe=k.stackRestore=function(){return k.asm.nc.apply(null,arguments)},je=k.stackSave=function(){return k.asm.oc.apply(null,arguments)},Uc=k.dynCall_iiii=function(){return k.asm.dc.apply(null,arguments)};k.dynCall_v=function(){return k.asm.ec.apply(null,arguments)};
var ve=k.dynCall_vi=function(){return k.asm.fc.apply(null,arguments)},Vd=k.dynCall_vidd=function(){return k.asm.gc.apply(null,arguments)},Ld=k.dynCall_vii=function(){return k.asm.hc.apply(null,arguments)},we=k.dynCall_viii=function(){return k.asm.ic.apply(null,arguments)},Zd=k.dynCall_viiii=function(){return k.asm.jc.apply(null,arguments)},Nd=k.dynCall_viiiii=function(){return k.asm.kc.apply(null,arguments)};k.asm=ye;k.getMemory=Ga;k.addRunDependency=eb;k.removeRunDependency=fb;
k.FS_createFolder=qc;k.FS_createPath=rc;k.FS_createDataFile=tc;k.FS_createPreloadedFile=xc;k.FS_createLazyFile=wc;k.FS_createLink=uc;k.FS_createDevice=O;k.FS_unlink=ec;function qa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}db=function ze(){k.calledRun||Ae();k.calledRun||(db=ze)};
function Ae(a){function b(){if(!k.calledRun&&(k.calledRun=!0,!B)){Ha=!0;k.noFSInit||oc||(oc=!0,nc(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?O("/dev","stdin",k.stdin):dc("/dev/tty","/dev/stdin"),k.stdout?O("/dev","stdout",null,k.stdout):dc("/dev/tty","/dev/stdout"),k.stderr?O("/dev","stderr",null,k.stderr):dc("/dev/tty1","/dev/stderr"),hc("/dev/stdin","r"),hc("/dev/stdout","w"),hc("/dev/stderr","w"));Va(Xa);Nb=!1;Va(Ya);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(Be){var b=
a;b=b||[];var d=b.length+1,e=Pa(4*(d+1));w[e>>2]=Oa(da);for(var g=1;g<d;g++)w[(e>>2)+g]=Oa(b[g-1]);w[(e>>2)+d]=0;try{var h=k._main(d,e);ue(h,!0)}catch(n){n instanceof qa||("SimulateInfiniteLoop"==n?k.noExitRuntime=!0:((b=n)&&"object"===typeof n&&n.stack&&(b=[n,n.stack]),l("exception thrown: "+b),ea(1,n)))}finally{}}if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)b=k.postRun.shift(),$a.unshift(b);Va($a)}}a=a||ca;if(!(0<bb)){if(k.preRun)for("function"==typeof k.preRun&&
(k.preRun=[k.preRun]);k.preRun.length;)ab();Va(Wa);0<bb||k.calledRun||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);b()},1)):b())}}k.run=Ae;function ue(a,b){if(!b||!k.noExitRuntime||0!==a){if(!k.noExitRuntime&&(B=!0,k.onExit))k.onExit(a);ea(a,new qa(a))}}function p(a){if(k.onAbort)k.onAbort(a);ra(a);l(a);B=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}k.abort=p;
if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();var Be=!0;k.noInitialRun&&(Be=!1);k.noExitRuntime=!0;Ae();
