var g;var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.vd||(h.vd=0,h.Be=0);h.vd++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var e=b;c.total&&(e=c.total);if(c.loaded){d.Fc?h.wc[a].loaded=c.loaded:(d.Fc=!0,h.wc||(h.wc={}),h.wc[a]={loaded:c.loaded,total:e});var f=e=c=0,k;for(k in h.wc){var p=h.wc[k];c+=p.total;e+=p.loaded;f++}c=Math.ceil(c*h.vd/f);h.setStatus&&h.setStatus("Downloading data... ("+e+"/"+c+")")}else!h.wc&&h.setStatus&&h.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){h.Be++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.ve=c;c=a.files;for(var d=
0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();h.removeRunDependency("datafile_R:/emsOut/MinSizeRel/wglChAoSP.data")}h.FS_createPath("/","Shaders",!0,!0);h.FS_createPath("/","ChaoticAttractors",!0,!0);h.FS_createPath("/","colorMaps",!0,!0);h.FS_createPath("/","Fonts",!0,!0);h.FS_createPath("/","startData",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;h.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.ve.subarray(this.start,
this.end))},finish:function(a){h.FS_createDataFile(this.name,null,a,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,e=0;e<d.length;++e)(new b(d[e].start,d[e].end,d[e].audio)).open("GET",d[e].filename);h.addRunDependency("datafile_R:/emsOut/MinSizeRel/wglChAoSP.data");h.ce||(h.ce={});h.ce["R:/emsOut/MinSizeRel/wglChAoSP.data"]={Fh:!1};r?(c(r),r=null):k=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=h.locateFile?h.locateFile("wglChAoSP.data",""):"wglChAoSP.data",f=a.Oh,k=null,r=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;r||b(e,f,function(a){k?(k(a),k=null):r=a},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({remote_package_size:4108477,files:[{filename:"/Shaders/allParticles.0.frag",start:0,audio:0,end:12639},{filename:"/Shaders/allParticles.0.vert",start:12639,audio:0,end:16723},{filename:"/Shaders/allParticles.1.frag",start:16723,audio:0,end:29419},{filename:"/Shaders/allParticles.frag",
start:29419,audio:0,end:42382},{filename:"/Shaders/allParticles.vert",start:42382,audio:0,end:46468},{filename:"/Shaders/ambientOcclusionFrag.glsl",start:46468,audio:0,end:54959},{filename:"/Shaders/bilateralVersions.glsl",start:54959,audio:0,end:79837},{filename:"/Shaders/BillboardFrag.glsl",start:79837,audio:0,end:80493},{filename:"/Shaders/BillboardGeom.glsl",start:80493,audio:0,end:82531},{filename:"/Shaders/BillboardVert.glsl",start:82531,audio:0,end:83632},{filename:"/Shaders/cmTexturedFrag.glsl",
start:83632,audio:0,end:85306},{filename:"/Shaders/colorSpaces.glsl",start:85306,audio:0,end:90280},{filename:"/Shaders/fxaaFrag.glsl",start:90280,audio:0,end:94247},{filename:"/Shaders/lightModelsFrag.glsl",start:94247,audio:0,end:104378},{filename:"/Shaders/MergedRenderingFrag.glsl",start:104378,audio:0,end:105296},{filename:"/Shaders/mmFBO_all_vert.glsl",start:105296,audio:0,end:106208},{filename:"/Shaders/MotionBlurFS.glsl",start:106208,audio:0,end:107306},{filename:"/Shaders/oglAxesFrag.glsl",
start:107306,audio:0,end:109006},{filename:"/Shaders/oglAxesVert.glsl",start:109006,audio:0,end:111191},{filename:"/Shaders/ParticlesFrag.glsl",start:111191,audio:0,end:116990},{filename:"/Shaders/ParticlesVert.glsl",start:116990,audio:0,end:119864},{filename:"/Shaders/PointSpriteFragLight.glsl",start:119864,audio:0,end:120594},{filename:"/Shaders/PointSpriteVert.glsl",start:120594,audio:0,end:122608},{filename:"/Shaders/postRenderingFrag.glsl",start:122608,audio:0,end:139177},{filename:"/Shaders/postRenderingVert.glsl",
start:139177,audio:0,end:141742},{filename:"/Shaders/RadialBlur2PassFrag.glsl",start:141742,audio:0,end:155261},{filename:"/Shaders/shadowFrag.glsl",start:155261,audio:0,end:156456},{filename:"/ChaoticAttractors/0000test0.sca",start:156456,audio:0,end:183192},{filename:"/ChaoticAttractors/0009e1.sca",start:183192,audio:0,end:209313},{filename:"/ChaoticAttractors/Aizawa05.sca",start:209313,audio:0,end:234581},{filename:"/ChaoticAttractors/Aizawa06.sca",start:234581,audio:0,end:259861},{filename:"/ChaoticAttractors/Aizawa09.sca",
start:259861,audio:0,end:285141},{filename:"/ChaoticAttractors/Aizawa10.sca",start:285141,audio:0,end:310476},{filename:"/ChaoticAttractors/Aizawa11.sca",start:310476,audio:0,end:335808},{filename:"/ChaoticAttractors/Aizawa12.sca",start:335808,audio:0,end:361173},{filename:"/ChaoticAttractors/aliDrago01.sca",start:361173,audio:0,end:385248},{filename:"/ChaoticAttractors/BicomplexJMod0_IIM1.sca",start:385248,audio:0,end:409324},{filename:"/ChaoticAttractors/BicomplexJMod3_IIM4.sca",start:409324,audio:0,
end:432995},{filename:"/ChaoticAttractors/BicomplexJMod3_IIM6.sca",start:432995,audio:0,end:456478},{filename:"/ChaoticAttractors/BicomplexJMod5_IIM.sca",start:456478,audio:0,end:480387},{filename:"/ChaoticAttractors/BicomplexJMod7_IIM.sca",start:480387,audio:0,end:504278},{filename:"/ChaoticAttractors/BicomplexMod_IIM02.sca",start:504278,audio:0,end:528416},{filename:"/ChaoticAttractors/biTorus_09o4a.sca",start:528416,audio:0,end:553550},{filename:"/ChaoticAttractors/biTorus_09o5.sca",start:553550,
audio:0,end:578680},{filename:"/ChaoticAttractors/biTorus_09o8.sca",start:578680,audio:0,end:603826},{filename:"/ChaoticAttractors/dragon3b.sca",start:603826,audio:0,end:629985},{filename:"/ChaoticAttractors/dragon4a.sca",start:629985,audio:0,end:656053},{filename:"/ChaoticAttractors/dreamcatcher01.sca",start:656053,audio:0,end:685988},{filename:"/ChaoticAttractors/flower_0009nc.sca",start:685988,audio:0,end:711060},{filename:"/ChaoticAttractors/flower_0009nd.sca",start:711060,audio:0,end:736134},
{filename:"/ChaoticAttractors/flower_0009ng.sca",start:736134,audio:0,end:762156},{filename:"/ChaoticAttractors/Halvorsen01.sca",start:762156,audio:0,end:787424},{filename:"/ChaoticAttractors/JuliaBulbN7_01.sca",start:787424,audio:0,end:811979},{filename:"/ChaoticAttractors/juliaBulb_IIM02.sca",start:811979,audio:0,end:835841},{filename:"/ChaoticAttractors/Magnetic_stright01.sca",start:835841,audio:0,end:860925},{filename:"/ChaoticAttractors/Magnetic_stright01a.sca",start:860925,audio:0,end:886471},
{filename:"/ChaoticAttractors/Mag_0009e2b.sca",start:886471,audio:0,end:912437},{filename:"/ChaoticAttractors/Pn3D_o06_001.sca",start:912437,audio:0,end:940613},{filename:"/ChaoticAttractors/quatJulia_01.sca",start:940613,audio:0,end:964246},{filename:"/ChaoticAttractors/Rampe03a.sca",start:964246,audio:0,end:989588},{filename:"/ChaoticAttractors/Rampe07old.sca",start:989588,audio:0,end:1013604},{filename:"/ChaoticAttractors/Thomas01.sca",start:1013604,audio:0,end:1037489},{filename:"/ChaoticAttractors/torus_0009j.sca",
start:1037489,audio:0,end:1063387},{filename:"/ChaoticAttractors/torus_0009k.sca",start:1063387,audio:0,end:1088599},{filename:"/ChaoticAttractors/torus_0009l.sca",start:1088599,audio:0,end:1113742},{filename:"/ChaoticAttractors/torus_0009m1.sca",start:1113742,audio:0,end:1138973},{filename:"/ChaoticAttractors/torus_0009m3.sca",start:1138973,audio:0,end:1164205},{filename:"/ChaoticAttractors/torus_0009m4.sca",start:1164205,audio:0,end:1189031},{filename:"/ChaoticAttractors/torus_0009nb.sca",start:1189031,
audio:0,end:1214272},{filename:"/colorMaps/palettes.json",start:1214272,audio:0,end:2199534},{filename:"/Fonts/Cousine-Regular.ttf",start:2199534,audio:0,end:2243446},{filename:"/Fonts/fontawesome-webfont.ttf",start:2243446,audio:0,end:2408994},{filename:"/Fonts/README.txt",start:2408994,audio:0,end:2409362},{filename:"/startData/Aizawa.sca",start:2409362,audio:0,end:2434633},{filename:"/startData/Arneodo.sca",start:2434633,audio:0,end:2459875},{filename:"/startData/BicomplexJExplorer.sca",start:2459875,
audio:0,end:2485189},{filename:"/startData/BicomplexJMod0_IIM.sca",start:2485189,audio:0,end:2508339},{filename:"/startData/BicomplexJMod1_IIM.sca",start:2508339,audio:0,end:2533746},{filename:"/startData/BicomplexJMod2_IIM.sca",start:2533746,audio:0,end:2557654},{filename:"/startData/BicomplexJMod3_IIM.sca",start:2557654,audio:0,end:2581518},{filename:"/startData/BicomplexJMod4_IIM.sca",start:2581518,audio:0,end:2605481},{filename:"/startData/BicomplexJMod5_IIM.sca",start:2605481,audio:0,end:2630921},
{filename:"/startData/BicomplexJMod6_IIM.sca",start:2630921,audio:0,end:2654919},{filename:"/startData/BicomplexJMod7_IIM.sca",start:2654919,audio:0,end:2680305},{filename:"/startData/BicomplexJ_IIM.sca",start:2680305,audio:0,end:2704227},{filename:"/startData/Bouali.sca",start:2704227,audio:0,end:2729558},{filename:"/startData/ChenLee.sca",start:2729558,audio:0,end:2754877},{filename:"/startData/Coullet.sca",start:2754877,audio:0,end:2780344},{filename:"/startData/Dadras.sca",start:2780344,audio:0,
end:2805780},{filename:"/startData/DequanLi.sca",start:2805780,audio:0,end:2831047},{filename:"/startData/dla3D.sca",start:2831047,audio:0,end:2856413},{filename:"/startData/FourWing.sca",start:2856413,audio:0,end:2881271},{filename:"/startData/FourWing2.sca",start:2881271,audio:0,end:2906579},{filename:"/startData/FourWing3.sca",start:2906579,audio:0,end:2931872},{filename:"/startData/GenesioTesi.sca",start:2931872,audio:0,end:2957294},{filename:"/startData/Hadley.sca",start:2957294,audio:0,end:2982732},
{filename:"/startData/Halvorsen.sca",start:2982732,audio:0,end:3006797},{filename:"/startData/juliaBulb4th_IIM.sca",start:3006797,audio:0,end:3032155},{filename:"/startData/juliaBulb_IIM.sca",start:3032155,audio:0,end:3056090},{filename:"/startData/KingsDream.sca",start:3056090,audio:0,end:3081402},{filename:"/startData/LiuChen.sca",start:3081402,audio:0,end:3106871},{filename:"/startData/Lorenz.sca",start:3106871,audio:0,end:3131347},{filename:"/startData/MagneticFull.sca",start:3131347,audio:0,
end:3156490},{filename:"/startData/MagneticLeft.sca",start:3156490,audio:0,end:3181585},{filename:"/startData/MagneticRight.sca",start:3181585,audio:0,end:3208310},{filename:"/startData/MagneticStraight.sca",start:3208310,audio:0,end:3232973},{filename:"/startData/Mira3D.sca",start:3232973,audio:0,end:3258325},{filename:"/startData/MultiChuaII.sca",start:3258325,audio:0,end:3283608},{filename:"/startData/NewtonLeipnik.sca",start:3283608,audio:0,end:3309006},{filename:"/startData/NoseHoover.sca",start:3309006,
audio:0,end:3334168},{filename:"/startData/Pickover.sca",start:3334168,audio:0,end:3357198},{filename:"/startData/PolynomialA.sca",start:3357198,audio:0,end:3382595},{filename:"/startData/PolynomialABS.sca",start:3382595,audio:0,end:3406824},{filename:"/startData/PolynomialB.sca",start:3406824,audio:0,end:3431276},{filename:"/startData/PolynomialC.sca",start:3431276,audio:0,end:3456891},{filename:"/startData/PolynomialPow.sca",start:3456891,audio:0,end:3480210},{filename:"/startData/PolynomialSin.sca",
start:3480210,audio:0,end:3506256},{filename:"/startData/PowerN3D.sca",start:3506256,audio:0,end:3546024},{filename:"/startData/quatJulia_IIM.sca",start:3546024,audio:0,end:3571439},{filename:"/startData/Rampe01.sca",start:3571439,audio:0,end:3595753},{filename:"/startData/Rampe02.sca",start:3595753,audio:0,end:3617704},{filename:"/startData/Rampe03.sca",start:3617704,audio:0,end:3641480},{filename:"/startData/Rampe03A.sca",start:3641480,audio:0,end:3665323},{filename:"/startData/Rampe04.sca",start:3665323,
audio:0,end:3689135},{filename:"/startData/Rampe05.sca",start:3689135,audio:0,end:3712565},{filename:"/startData/Rampe06.sca",start:3712565,audio:0,end:3737961},{filename:"/startData/Rampe07.sca",start:3737961,audio:0,end:3760293},{filename:"/startData/Rampe08.sca",start:3760293,audio:0,end:3784109},{filename:"/startData/Rampe09.sca",start:3784109,audio:0,end:3807500},{filename:"/startData/Rampe10.sca",start:3807500,audio:0,end:3831266},{filename:"/startData/RayleighBenard.sca",start:3831266,audio:0,
end:3856688},{filename:"/startData/Robinson.sca",start:3856688,audio:0,end:3880545},{filename:"/startData/Rossler.sca",start:3880545,audio:0,end:3905700},{filename:"/startData/Rucklidge.sca",start:3905700,audio:0,end:3932023},{filename:"/startData/Sakarya.sca",start:3932023,audio:0,end:3957547},{filename:"/startData/SinCos.sca",start:3957547,audio:0,end:3982081},{filename:"/startData/SprottLinzF.sca",start:3982081,audio:0,end:4007453},{filename:"/startData/Thomas.sca",start:4007453,audio:0,end:4032620},
{filename:"/startData/TSUCS.sca",start:4032620,audio:0,end:4057886},{filename:"/startData/YuWang.sca",start:4057886,audio:0,end:4083140},{filename:"/startData/ZhouChen.sca",start:4083140,audio:0,end:4108477}],package_uuid:"a7ba4b82-11a8-43dd-bf51-45aeadb4a9d8"});var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,m=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;m="function"===typeof importScripts;
ha=(ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!m;ja=!fa&&!ha&&!m;var n="",ka,la,ma;
if(ha){n=__dirname+"/";var na,oa;ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);a=na.readFileSync(a);return b?a:a.toString()};ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));ca=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=h);process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;});process.on("unhandledRejection",q);ea=function(a){process.exit(a)};
h.inspect=function(){return"[Emscripten Module object]"}}else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||m)m?n=self.location.href:document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=h.print||console.log.bind(console),l=h.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);
function ra(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:if("*"===a[a.length-1])return 4;if("i"===a[0]){var b=parseInt(a.substr(1));assert(0===b%8,"getNativeTypeSize invalid bits "+b+", type "+a);return b/8}return 0}}function sa(a){ta||(ta={});ta[a]||(ta[a]=1,l(a))}var ta,ua;h.wasmBinary&&(ua=h.wasmBinary);var va;h.noExitRuntime&&(va=h.noExitRuntime);"object"!==typeof WebAssembly&&l("no native wasm support detected");
function v(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":w[a>>0]=b;break;case "i8":w[a>>0]=b;break;case "i16":wa[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":z=[b>>>0,(A=b,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[a>>2]=z[0];x[a+4>>2]=z[1];break;case "float":B[a>>2]=b;break;case "double":Ba[a>>3]=b;break;default:q("invalid type for setValue: "+c)}}
var Ca,Da=new WebAssembly.Table({initial:857,maximum:857,element:"anyfunc"}),C=!1;function assert(a,b){a||q("Assertion failed: "+b)}
function Ea(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;var e="string"===typeof b?b:null;var f=Fa(Math.max(d,e?1:b.length));if(c){a=f;assert(0==(f&3));for(b=f+(d&-4);a<b;a+=4)x[a>>2]=0;for(b=f+d;a<b;)w[a++>>0]=0;return f}if("i8"===e)return a.subarray||a.slice?E.set(a,f):E.set(new Uint8Array(a),f),f;c=0;for(var k,r,p;c<d;){var u=a[c];k=e||b[c];0===k?c++:("i64"==k&&(k="i32"),v(f+c,u,k),p!==k&&(r=ra(k),p=k),c+=r)}return f}
var Ga="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ha(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ga)return Ga.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?Ha(E,a,b):""}
function Ia(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var r=a.charCodeAt(++f);k=65536+((k&1023)<<10)|r&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ka(a){var b=Ja(a)+1,c=La(b);Ia(a,w,c,b);return c}function Ma(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,w,E,wa,Na,x,Oa,B,Ba;
function Pa(a){buffer=a;h.HEAP8=w=new Int8Array(a);h.HEAP16=wa=new Int16Array(a);h.HEAP32=x=new Int32Array(a);h.HEAPU8=E=new Uint8Array(a);h.HEAPU16=Na=new Uint16Array(a);h.HEAPU32=Oa=new Uint32Array(a);h.HEAPF32=B=new Float32Array(a);h.HEAPF64=Ba=new Float64Array(a)}var Qa=h.TOTAL_MEMORY||16777216;h.wasmMemory?Ca=h.wasmMemory:Ca=new WebAssembly.Memory({initial:Qa/65536});Ca&&(buffer=Ca.buffer);Qa=buffer.byteLength;Pa(buffer);x[26168]=5347712;
function Ra(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.nc;"number"===typeof c?void 0===b.qc?h.dynCall_v(c):h.dynCall_vi(c,b.qc):c(void 0===b.qc?null:b.qc)}}}var Sa=[],Ta=[],Ua=[],Va=[],Wa=[],Xa=!1;function Ya(){var a=h.preRun.shift();Sa.unshift(a)}var xa=Math.abs,Aa=Math.ceil,za=Math.floor,ya=Math.min,Za=0,$a=null,ab=null;function bb(){Za++;h.monitorRunDependencies&&h.monitorRunDependencies(Za)}
function cb(){Za--;h.monitorRunDependencies&&h.monitorRunDependencies(Za);if(0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab)){var a=ab;ab=null;a()}}h.preloadedImages={};h.preloadedAudios={};function q(a){if(h.onAbort)h.onAbort(a);qa(a);l(a);C=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}function db(){var a=eb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var eb="wglChAoSP.wasm";
if(!db()){var fb=eb;eb=h.locateFile?h.locateFile(fb,n):n+fb}function gb(){try{if(ua)return new Uint8Array(ua);if(ma)return ma(eb);throw"both async and sync fetching of the wasm failed";}catch(a){q(a)}}function hb(){return ua||!fa&&!m||"function"!==typeof fetch?new Promise(function(a){a(gb())}):fetch(eb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+eb+"'";return a.arrayBuffer()}).catch(function(){return gb()})}var A,z;Ta.push({nc:function(){ib()}});
function jb(a){h.___errno_location&&(x[h.___errno_location()>>2]=a)}function kb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function lb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function mb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function nb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function ob(){var a=Array.prototype.slice.call(arguments,0);return lb(a.join("/"))}function G(a,b){return lb(a+"/"+b)}
function pb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var qb=[];function rb(a,b){qb[a]={input:[],output:[],Bc:b};sb(a,tb)}
var tb={open:function(a){var b=qb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Bc.flush(a.tty)},flush:function(a){a.tty.Bc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Bc.Td)throw new H(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.Bc.Td(a.tty)}catch(r){throw new H(29);}if(void 0===k&&0===e)throw new H(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Bc.Bd)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.Bc.Bd(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},vb={Td:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.Fc?Buffer.Fc(256):new Buffer(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ub(b,!0)}return a.input.shift()},Bd:function(a,b){null===b||10===b?(qa(Ha(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ha(a.output,0)),a.output=[])}},yb={Bd:function(a,b){null===b||10===b?(l(Ha(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(Ha(a.output,0)),a.output=[])}},I={lc:null,ic:function(){return I.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.lc||(I.lc={dir:{node:{mc:I.bc.mc,fc:I.bc.fc,lookup:I.bc.lookup,Lc:I.bc.Lc,rename:I.bc.rename,unlink:I.bc.unlink,rmdir:I.bc.rmdir,readdir:I.bc.readdir,symlink:I.bc.symlink},stream:{oc:I.cc.oc}},file:{node:{mc:I.bc.mc,fc:I.bc.fc},stream:{oc:I.cc.oc,read:I.cc.read,write:I.cc.write,Fd:I.cc.Fd,Zd:I.cc.Zd,hd:I.cc.hd}},link:{node:{mc:I.bc.mc,fc:I.bc.fc,readlink:I.bc.readlink},stream:{}},Kd:{node:{mc:I.bc.mc,
fc:I.bc.fc},stream:zb}});c=Ab(a,b,c,d);J(c.mode)?(c.bc=I.lc.dir.node,c.cc=I.lc.dir.stream,c.ac={}):32768===(c.mode&61440)?(c.bc=I.lc.file.node,c.cc=I.lc.file.stream,c.dc=0,c.ac=null):40960===(c.mode&61440)?(c.bc=I.lc.link.node,c.cc=I.lc.link.stream):8192===(c.mode&61440)&&(c.bc=I.lc.Kd.node,c.cc=I.lc.Kd.stream);c.timestamp=Date.now();a&&(a.ac[b]=c);return c},Gh:function(a){if(a.ac&&a.ac.subarray){for(var b=[],c=0;c<a.dc;++c)b.push(a.ac[c]);return b}return a.ac},Hh:function(a){return a.ac?a.ac.subarray?
a.ac.subarray(0,a.dc):new Uint8Array(a.ac):new Uint8Array},Nd:function(a,b){var c=a.ac?a.ac.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.ac,a.ac=new Uint8Array(b),0<a.dc&&a.ac.set(c.subarray(0,a.dc),0))},Qe:function(a,b){if(a.dc!=b)if(0==b)a.ac=null,a.dc=0;else{if(!a.ac||a.ac.subarray){var c=a.ac;a.ac=new Uint8Array(new ArrayBuffer(b));c&&a.ac.set(c.subarray(0,Math.min(b,a.dc)))}else if(a.ac||(a.ac=[]),a.ac.length>b)a.ac.length=b;else for(;a.ac.length<b;)a.ac.push(0);
a.dc=b}},bc:{mc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.dc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.rc=4096;b.blocks=Math.ceil(b.size/b.rc);return b},fc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&
I.Qe(a,b.size)},lookup:function(){throw Bb[44];},Lc:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(J(a.mode)){try{var d=Cb(b,c)}catch(f){}if(d)for(var e in d.ac)throw new H(55);}delete a.parent.ac[a.name];a.name=c;b.ac[c]=a;a.parent=b},unlink:function(a,b){delete a.ac[b]},rmdir:function(a,b){var c=Cb(a,b),d;for(d in c.ac)throw new H(55);delete a.ac[b]},readdir:function(a){var b=[".",".."],c;for(c in a.ac)a.ac.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=
I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},cc:{read:function(a,b,c,d,e){var f=a.node.ac;if(e>=a.node.dc)return 0;a=Math.min(a.node.dc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){f=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ac||a.ac.subarray)){if(f)return a.ac=b.subarray(c,c+d),a.dc=d;if(0===a.dc&&0===e)return a.ac=
new Uint8Array(b.subarray(c,c+d)),a.dc=d;if(e+d<=a.dc)return a.ac.set(b.subarray(c,c+d),e),d}I.Nd(a,e+d);if(a.ac.subarray&&b.subarray)a.ac.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ac[e+f]=b[c+f];a.dc=Math.max(a.dc,e+d);return d},oc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.dc);if(0>b)throw new H(28);return b},Fd:function(a,b,c){I.Nd(a.node,b+c);a.node.dc=Math.max(a.node.dc,b+c)},Zd:function(a,b,c,d,e,f,k){if(32768!==(a.node.mode&61440))throw new H(43);
c=a.node.ac;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.dc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==w.buffer;d=Fa(d);if(!d)throw new H(48);(e?w:b).set(c,d)}else a=!1,d=c.byteOffset;return{Nh:d,qe:a}},hd:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);if(e&2)return 0;I.cc.write(a,b,0,d,c,!1);return 0}}},Db={Xg:63,wg:44,kh:71,Tf:27,Vf:29,Tg:60,ff:1,xg:45,qf:8,zf:12,mf:6,uh:6,Bg:48,gf:2,Mf:21,Kg:105,xf:10,Lf:20,vh:75,vg:43,
Mg:54,Xf:31,Uf:28,qg:41,ig:33,Rg:59,rh:74,Nf:22,Gg:51,jh:70,gh:69,jg:34,Zg:64,If:18,dh:68,Cg:49,Qf:24,Af:106,Zf:156,$f:107,ag:108,gg:109,sh:110,tg:111,Yf:112,Ff:16,yg:46,pf:113,tf:114,wh:115,rg:104,uf:103,vf:102,Gf:16,wf:101,Ig:100,ug:116,oh:117,Hg:118,Dg:119,Eg:120,fh:121,zg:47,kf:122,lh:123,Bf:124,$g:65,lg:36,Jf:125,sf:9,Sg:126,rf:127,eh:128,bg:129,cg:130,fg:131,eg:132,dg:133,Jg:52,Ng:55,mg:37,hg:32,Ug:138,Yg:139,Ef:15,sg:42,lf:5,bh:67,Pg:57,Fg:50,hh:140,Df:14,hf:3,Cf:13,pg:40,ng:38,ph:73,Of:142,
Pf:23,Sf:26,nf:7,Hf:17,kg:35,ah:66,ih:137,jf:4,og:39,Wf:30,Lg:53,qh:141,th:136,Kf:19,mh:72,Qg:138,Ag:148,Rf:25,Vg:61,yf:11,Og:56,Wg:62,nh:135},L={ad:!1,Xe:function(){L.ad=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);L.Od={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Gd:function(a){return Buffer.alloc?Buffer.from(a):new Buffer(a)},ec:function(a){a=a.code;assert(a in Db);return Db[a]},ic:function(a){assert(ia);
return L.createNode(null,"/",L.Sd(a.Ad.root),0)},createNode:function(a,b,c){if(!J(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new H(28);a=Ab(a,b,c);a.bc=L.bc;a.cc=L.cc;return a},Sd:function(a){try{var b=fs.lstatSync(a);L.ad&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new H(L.ec(c));}return b.mode},jc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.ic.Ad.root);b.reverse();return ob.apply(null,b)},Ce:function(a){a&=-2656257;var b=0,c;for(c in L.Od)a&
c&&(b|=L.Od[c],a^=c);if(a)throw new H(28);return b},bc:{mc:function(a){a=L.jc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new H(L.ec(c));}L.ad&&!b.rc&&(b.rc=4096);L.ad&&!b.blocks&&(b.blocks=(b.size+b.rc-1)/b.rc|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,rc:b.rc,blocks:b.blocks}},fc:function(a,b){var c=L.jc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&
fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new H(L.ec(d));}},lookup:function(a,b){var c=G(L.jc(a),b);c=L.Sd(c);return L.createNode(a,b,c)},Lc:function(a,b,c,d){a=L.createNode(a,b,c,d);b=L.jc(a);try{J(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new H(L.ec(e));}return a},rename:function(a,b,c){a=L.jc(a);b=G(L.jc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new H(L.ec(d));}},unlink:function(a,b){a=G(L.jc(a),
b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new H(L.ec(c));}},rmdir:function(a,b){a=G(L.jc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new H(L.ec(c));}},readdir:function(a){a=L.jc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new H(L.ec(b));}},symlink:function(a,b,c){a=G(L.jc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new H(L.ec(d));}},readlink:function(a){var b=L.jc(a);try{return b=fs.readlinkSync(b),b=Eb.relative(Eb.resolve(a.ic.Ad.root),
b)}catch(c){if(!c.code)throw c;throw new H(L.ec(c));}}},cc:{open:function(a){var b=L.jc(a.node);try{32768===(a.node.mode&61440)&&(a.Nc=fs.openSync(b,L.Ce(a.flags)))}catch(c){if(!c.code)throw c;throw new H(L.ec(c));}},close:function(a){try{32768===(a.node.mode&61440)&&a.Nc&&fs.closeSync(a.Nc)}catch(b){if(!b.code)throw b;throw new H(L.ec(b));}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Nc,L.Gd(b.buffer),c,d,e)}catch(f){throw new H(L.ec(f));}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Nc,
L.Gd(b.buffer),c,d,e)}catch(f){throw new H(L.ec(f));}},oc:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Nc).size}catch(d){throw new H(L.ec(d));}if(0>b)throw new H(28);return b}}},Fb=null,Gb={},Hb=[],Ib=1,Jb=null,Kb=!0,Lb={},H=null,Bb={};
function M(a,b){a=pb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Pd:!0,Cd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Cd)throw new H(32);a=kb(a.split("/").filter(function(a){return!!a}),!1);var e=Fb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Cb(e,a[d]);c=G(c,a[d]);e.Mc&&(!f||f&&b.Pd)&&(e=e.Mc.root);if(!f||b.Yc)for(f=0;40960===(e.mode&61440);)if(e=Mb(c),c=pb(mb(c),e),e=M(c,{Cd:b.Cd}).node,40<f++)throw new H(32);}return{path:c,node:e}}
function Nb(a){for(var b;;){if(a===a.parent)return a=a.ic.$d,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Jb.length}function Pb(a){var b=Ob(a.parent.id,a.name);a.zc=Jb[b];Jb[b]=a}function Cb(a,b){var c;if(c=(c=Qb(a,"x"))?c:a.bc.lookup?0:2)throw new H(c,a);for(c=Jb[Ob(a.id,b)];c;c=c.zc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.bc.lookup(a,b)}
function Ab(a,b,c,d){Rb||(Rb=function(a,b,c,d){a||(a=this);this.parent=a;this.ic=a.ic;this.Mc=null;this.id=Ib++;this.name=b;this.mode=c;this.bc={};this.cc={};this.rdev=d},Rb.prototype={},Object.defineProperties(Rb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Me:{get:function(){return J(this.mode)}},Le:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Rb(a,b,c,d);Pb(a);return a}function J(a){return 16384===(a&61440)}var Sb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Qb(a,b){if(Kb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Ub(a,b){try{return Cb(a,b),20}catch(c){}return Qb(a,"wx")}function Vb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Hb[a])return a;throw new H(33);}function Wb(a,b){Xb||(Xb=function(){},Xb.prototype={},Object.defineProperties(Xb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Xb,d;for(d in a)c[d]=a[d];a=c;b=Vb(b);a.fd=b;return Hb[b]=a}var zb={open:function(a){a.cc=Gb[a.node.rdev].cc;a.cc.open&&a.cc.open(a)},oc:function(){throw new H(70);}};
function sb(a,b){Gb[a]={cc:b}}function Yb(a,b){var c="/"===b,d=!b;if(c&&Fb)throw new H(10);if(!c&&!d){var e=M(b,{Pd:!1});b=e.path;e=e.node;if(e.Mc)throw new H(10);if(!J(e.mode))throw new H(54);}b={type:a,Ad:{},$d:b,Oe:[]};a=a.ic(b);a.ic=b;b.root=a;c?Fb=a:e&&(e.Mc=b,e.ic&&e.ic.Oe.push(b))}function Zb(a,b,c){var d=M(a,{parent:!0}).node;a=nb(a);if(!a||"."===a||".."===a)throw new H(28);var e=Ub(d,a);if(e)throw new H(e);if(!d.bc.Lc)throw new H(63);return d.bc.Lc(d,a,b,c)}
function N(a,b){return Zb(a,(void 0!==b?b:511)&1023|16384,0)}function $b(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Zb(a,b|8192,c)}function ac(a,b){if(!pb(a))throw new H(44);var c=M(b,{parent:!0}).node;if(!c)throw new H(44);b=nb(b);var d=Ub(c,b);if(d)throw new H(d);if(!c.bc.symlink)throw new H(63);return c.bc.symlink(c,b,a)}
function bc(a){var b=M(a,{parent:!0}).node,c=nb(a),d=Cb(b,c);a:{try{var e=Cb(b,c)}catch(k){e=k.kc;break a}var f=Qb(b,"wx");e=f?f:J(e.mode)?31:0}if(e)throw new H(e);if(!b.bc.unlink)throw new H(63);if(d.Mc)throw new H(10);try{Lb.willDeletePath&&Lb.willDeletePath(a)}catch(k){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.bc.unlink(b,c);b=Ob(d.parent.id,d.name);if(Jb[b]===d)Jb[b]=d.zc;else for(b=Jb[b];b;){if(b.zc===d){b.zc=d.zc;break}b=b.zc}try{if(Lb.onDeletePath)Lb.onDeletePath(a)}catch(k){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Mb(a){a=M(a).node;if(!a)throw new H(44);if(!a.bc.readlink)throw new H(28);return pb(Nb(a.parent),a.bc.readlink(a))}function cc(a,b){var c;"string"===typeof a?c=M(a,{Yc:!0}).node:c=a;if(!c.bc.fc)throw new H(63);c.bc.fc(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function ec(a,b,c,d){if(""===a)throw new H(44);if("string"===typeof b){var e=Sb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=lb(a);try{f=M(a,{Yc:!(b&131072)}).node}catch(r){}}e=!1;if(b&64)if(f){if(b&128)throw new H(20);}else f=Zb(a,c,0),e=!0;if(!f)throw new H(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!J(f.mode))throw new H(54);if(!e&&(c=f?40960===(f.mode&61440)?32:J(f.mode)&&
("r"!==Tb(b)||b&512)?31:Qb(f,Tb(b)):44))throw new H(c);if(b&512){c=f;var k;"string"===typeof c?k=M(c,{Yc:!0}).node:k=c;if(!k.bc.fc)throw new H(63);if(J(k.mode))throw new H(31);if(32768!==(k.mode&61440))throw new H(28);if(c=Qb(k,"w"))throw new H(c);k.bc.fc(k,{size:0,timestamp:Date.now()})}b&=-641;d=Wb({node:f,path:Nb(f),flags:b,seekable:!0,position:0,cc:f.cc,cf:[],error:!1},d);d.cc.open&&d.cc.open(d);!h.logReadFiles||b&1||(fc||(fc={}),a in fc||(fc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Lb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Lb.onOpenFile(a,f))}catch(r){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+r.message)}return d}function hc(a){if(null===a.fd)throw new H(8);a.tc&&(a.tc=null);try{a.cc.close&&a.cc.close(a)}catch(b){throw b;}finally{Hb[a.fd]=null}a.fd=null}
function ic(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.cc.oc)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.cc.oc(a,b,c);a.cf=[];return a.position}
function jc(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(J(a.node.mode))throw new H(31);if(!a.cc.write)throw new H(28);a.flags&1024&&ic(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new H(70);b=a.cc.write(a,b,c,d,e,f);k||(a.position+=b);try{if(a.path&&Lb.onWriteToFile)Lb.onWriteToFile(a.path)}catch(r){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+r.message)}return b}
function kc(){H||(H=function(a,b){this.node=b;this.Ue=function(a){this.kc=a};this.Ue(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(function(a){Bb[a]=new H(a);Bb[a].stack="<generic error, no stack>"}))}var lc;function mc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function nc(a,b,c,d){a=G("string"===typeof a?a:Nb(a),b);return N(a,mc(c,d))}
function oc(a,b){a="string"===typeof a?a:Nb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a,c);try{N(d)}catch(e){}a=d}}return d}function pc(a,b,c,d){a=G("string"===typeof a?a:Nb(a),b);c=mc(c,d);return Zb(a,(void 0!==c?c:438)&4095|32768,0)}
function qc(a,b,c,d,e,f){a=b?G("string"===typeof a?a:Nb(a),b):a;d=mc(d,e);e=Zb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}cc(e,d|146);a=ec(e,"w");jc(a,c,0,c.length,0,f);hc(a);cc(e,d)}return e}
function O(a,b,c,d){a=G("string"===typeof a?a:Nb(a),b);b=mc(!!c,!!d);O.Xd||(O.Xd=64);var e=O.Xd++<<8|0;sb(e,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,e){for(var f=0,k=0;k<e;k++){try{var p=c()}catch(D){throw new H(29);}if(void 0===p&&0===f)throw new H(6);if(null===p||void 0===p)break;f++;b[d+k]=p}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){for(var f=0;f<e;f++)try{d(b[c+f])}catch(t){throw new H(29);}e&&(a.node.timestamp=
Date.now());return f}});return $b(a,b,e)}function rc(a,b,c){a=G("string"===typeof a?a:Nb(a),b);return ac(c,a)}
function sc(a){if(a.Le||a.Me||a.link||a.ac)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.ac=ub(ka(a.url),!0),a.dc=a.ac.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||jb(29);return b}
function tc(a,b,c,d,e){function f(){this.yd=!1;this.Uc=[]}f.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Ud(a/this.chunkSize|0)[b]}};f.prototype.Te=function(a){this.Ud=a};f.prototype.Hd=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,e=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var f=1048576;e||(f=b);var k=this;k.Te(function(a){var d=a*f,e=(a+1)*f-1;e=Math.min(e,b-1);if("undefined"===typeof k.Uc[a]){var y=k.Uc;if(d>e)throw Error("invalid range ("+d+", "+e+") or no bytes requested!");if(e>b-1)throw Error("only "+b+" bytes available! programmer error!");var p=new XMLHttpRequest;p.open("GET",c,!1);b!==f&&p.setRequestHeader("Range","bytes="+d+"-"+e);"undefined"!=typeof Uint8Array&&(p.responseType="arraybuffer");
p.overrideMimeType&&p.overrideMimeType("text/plain; charset=x-user-defined");p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);d=void 0!==p.response?new Uint8Array(p.response||[]):ub(p.responseText||"",!0);y[a]=d}if("undefined"===typeof k.Uc[a])throw Error("doXHR failed!");return k.Uc[a]});if(a||!b)f=b=1,f=b=this.Ud(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.pe=b;this.oe=
f;this.yd=!0};if("undefined"!==typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.yd||this.Hd();return this.pe}},chunkSize:{get:function(){this.yd||this.Hd();return this.oe}}});var r=void 0}else r=c,k=void 0;var p=pc(a,b,d,e);k?p.ac=k:r&&(p.ac=null,p.url=r);Object.defineProperties(p,{dc:{get:function(){return this.ac.length}}});var u=
{};Object.keys(p.cc).forEach(function(a){var b=p.cc[a];u[a]=function(){if(!sc(p))throw new H(29);return b.apply(null,arguments)}});u.read=function(a,b,c,d,e){if(!sc(p))throw new H(29);a=a.node.ac;if(e>=a.length)return 0;d=Math.min(a.length-e,d);if(a.slice)for(var f=0;f<d;f++)b[c+f]=a[e+f];else for(f=0;f<d;f++)b[c+f]=a.get(e+f);return d};p.cc=u;return p}
function uc(a,b,c,d,e,f,k,r,p,u){function t(c){function y(c){u&&u();r||qc(a,b,c,d,e,p);f&&f();cb(D)}var t=!1;h.preloadPlugins.forEach(function(a){!t&&a.canHandle(K)&&(a.handle(c,K,y,function(){k&&k();cb(D)}),t=!0)});t||y(c)}g.Vd();var K=b?pb(G(a,b)):a,D="cp "+K;bb(D);"string"==typeof c?g.se(c,function(a){t(a)},k):t(c)}var P={},Rb,Xb,fc,vc={},wc=0;function Q(){wc+=4;return x[wc-4>>2]}function xc(a){void 0===a&&(a=Q());a=Hb[a];if(!a)throw new H(8);return a}function yc(){q()}
g={$b:{pc:null,method:"",vc:0,nc:null,qc:0,nd:0,od:0,uc:0,de:[],pause:function(){g.$b.pc=null;g.$b.vc++},resume:function(){g.$b.vc++;var a=g.$b.nd,b=g.$b.od,c=g.$b.nc;g.$b.nc=null;zc(c,0,!1,g.$b.qc,!0);Ac(a,b);g.$b.pc()},df:function(){if(h.setStatus){var a=h.statusMessage||"Please wait...",b=g.$b.Dd,c=g.$b.Dh;b?b<c?h.setStatus(a+" ("+(c-b)+"/"+c+")"):h.setStatus(a):h.setStatus("")}},Re:function(a){if(!(C||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(b){if(b instanceof pa)return;b&&"object"===
typeof b&&b.stack&&l("exception thrown: "+[b,b.stack]);throw b;}h.postMainLoop&&h.postMainLoop()}}},Ic:!1,Oc:!1,Ne:[],workers:[],Vd:function(){function a(){g.Oc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!g.Je){g.Je=!0;try{g.Zc=!0}catch(c){g.Zc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}g.BlobBuilder=
"undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:g.Zc?null:console.log("warning: no BlobBuilder");g.Sc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.be||"undefined"!==typeof g.Sc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.be=!0);h.preloadPlugins.push({canHandle:function(a){return!h.be&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,
b,e,f){var c=null;if(g.Zc)try{c=new Blob([a],{type:g.xd(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:g.xd(b)}))}catch(u){sa("Blob constructor present but fails: "+u+"; falling back to blob builder")}c||(c=new g.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=g.Sc.createObjectURL(c),p=new Image;p.onload=function(){assert(p.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=p.width;c.height=p.height;c.getContext("2d").drawImage(p,
0,0);h.preloadedImages[b]=c;g.Sc.revokeObjectURL(d);e&&e(a)};p.onerror=function(){console.log("Image "+d+" could not be decoded");f&&f()};p.src=d}});h.preloadPlugins.push({canHandle:function(a){return!h.Lh&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,f){function c(c){p||(p=!0,h.preloadedAudios[b]=c,e&&e(a))}function d(){p||(p=!0,h.preloadedAudios[b]=new Audio,f&&f())}var p=!1;if(g.Zc){try{var u=new Blob([a],{type:g.xd(b)})}catch(K){return d()}u=g.Sc.createObjectURL(u);var t=
new Audio;t.addEventListener("canplaythrough",function(){c(t)},!1);t.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,f=0,k=0;k<a.length;k++)for(e=e<<8|a[k],f+=8;6<=f;){var r=e>>f-6&63;f-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==f?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==f&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&
15)<<2],d+="=");t.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(t)}};t.src=u;g.Se(function(){c(t)},1E4)}else return d()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",
a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",function(a){!g.Oc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&h.sc&&a==h.canvas)return h.sc;var e;if(b){var f={antialias:!1,alpha:!1,Yd:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)f[k]=
d[k];if("undefined"!==typeof Bc&&(e=Cc(a,f)))var r=Dc[e].Gc}else r=a.getContext("2d");if(!r)return null;c&&(b||assert("undefined"===typeof R,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.sc=r,b&&(S=Dc[e],h.sc=R=S&&S.Gc),h.Wh=b,g.Ne.forEach(function(a){a()}),g.Vd());return r},Bh:function(){},Rd:!1,cd:void 0,Cc:void 0,requestFullscreen:function(a,b,c){function d(){g.Ic=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||
document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=g.exitFullscreen,g.cd&&e.requestPointerLock(),g.Ic=!0,g.Cc?g.Ve():g.Rc(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),g.Cc?g.We():g.Rc(e));if(h.onFullScreen)h.onFullScreen(g.Ic);if(h.onFullscreen)h.onFullscreen(g.Ic)}g.cd=a;g.Cc=b;g.me=c;"undefined"===typeof g.cd&&(g.cd=!0);"undefined"===typeof g.Cc&&(g.Cc=!1);"undefined"===typeof g.me&&(g.me=null);var e=h.canvas;g.Rd||(g.Rd=!0,document.addEventListener("fullscreenchange",
d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:
null);c?f.requestFullscreen({Xh:c}):f.requestFullscreen()},ee:function(a,b,c){l("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");g.ee=function(a,b,c){return g.requestFullscreen(a,b,c)};return g.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!g.Ic)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},Ac:0,Ae:function(a){var b=
Date.now();if(0===g.Ac)g.Ac=b+1E3/60;else for(;b+2>=g.Ac;)g.Ac+=1E3/60;setTimeout(a,Math.max(g.Ac-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=g.Ae;b(a)}},Qh:function(a){return function(){if(!C)return a.apply(null,arguments)}},Hc:!0,Pc:[],Mh:function(){g.Hc=!1},Ph:function(){g.Hc=!0;if(0<g.Pc.length){var a=g.Pc;g.Pc=[];a.forEach(function(a){a()})}},Rh:function(a){return g.requestAnimationFrame(function(){C||(g.Hc?a():g.Pc.push(a))})},
Se:function(a,b){va=!0;return setTimeout(function(){C||(g.Hc?a():g.Pc.push(a))},b)},Sh:function(a,b){va=!0;return setInterval(function(){C||g.Hc&&a()},b)},xd:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Ee:function(a){return a.movementX||
a.mozMovementX||a.webkitMovementX||0},Fe:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},De:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},xc:0,yc:0,ed:0,gd:0,touches:{},Wd:{},
Id:function(a){if(g.Oc)"mousemove"!=a.type&&"mozMovementX"in a?g.ed=g.gd=0:(g.ed=g.Ee(a),g.gd=g.Fe(a)),g.xc+=g.ed,g.yc+=g.gd;else{var b=h.canvas.getBoundingClientRect(),c=h.canvas.width,d=h.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var k=a.Vh;if(void 0!==k)if(e=k.pageX-(e+b.left),f=k.pageY-(f+b.top),e*=c/b.width,f*=
d/b.height,b={x:e,y:f},"touchstart"===a.type)g.Wd[k.identifier]=b,g.touches[k.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=g.touches[k.identifier])||(a=b),g.Wd[k.identifier]=a,g.touches[k.identifier]=b}else k=a.pageX-(e+b.left),a=a.pageY-(f+b.top),k*=c/b.width,a*=d/b.height,g.ed=k-g.xc,g.gd=a-g.yc,g.xc=k,g.yc=a}},se:function(a,b,c,d){var e=d?"":"al "+a;la(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));e&&cb(e)},function(){if(c)c();
else throw'Loading data file "'+a+'" failed.';});e&&bb(e)},fe:[],Ed:function(){var a=h.canvas;g.fe.forEach(function(b){b(a.width,a.height)})},ld:function(a,b,c){g.Rc(h.canvas,a,b);c||g.Ed()},$h:0,Zh:0,Ve:function(){g.Rc(h.canvas);g.Ed()},We:function(){g.Rc(h.canvas);g.Ed()},Rc:function(a,b,c){b&&c?(a.ef=b,a.He=c):(b=a.ef,c=a.He);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||
document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}g.Cc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||
e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},Yh:{},ae:0,Ih:function(){var a=g.ae;g.ae++;return a}};
function Ac(a,b){g.$b.nd=a;g.$b.od=b;if(g.$b.nc)if(0==a)g.$b.pc=function(){var a=Math.max(0,g.$b.Ye+b-yc())|0;setTimeout(g.$b.jd,a)},g.$b.method="timeout";else if(1==a)g.$b.pc=function(){g.requestAnimationFrame(g.$b.jd)},g.$b.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);m?(void 0===h.setImmediates&&(h.setImmediates=
[]),h.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}g.$b.pc=function(){setImmediate(g.$b.jd)};g.$b.method="immediate"}}
function zc(a,b,c,d,e){va=!0;assert(!g.$b.nc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");g.$b.nc=a;g.$b.qc=d;var f="undefined"!==typeof d?function(){h.dynCall_vi(a,d)}:function(){h.dynCall_v(a)};var k=g.$b.vc;g.$b.jd=function(){if(!C)if(0<g.$b.de.length){var a=Date.now(),b=g.$b.de.shift();b.nc(b.qc);if(g.$b.Dd){var c=g.$b.Dd,d=0==c%1?c-1:Math.floor(c);
g.$b.Dd=b.zh?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");g.$b.df();k<g.$b.vc||setTimeout(g.$b.jd,0)}else k<g.$b.vc||(g.$b.uc=g.$b.uc+1|0,1==g.$b.nd&&1<g.$b.od&&0!=g.$b.uc%g.$b.od?g.$b.pc():(0==g.$b.nd&&(g.$b.Ye=yc()),"undefined"!==typeof Bc&&S&&!Bc.Ah&&!S.attributes.Eh&&S.Gc.xe&&S.Gc.xe(),"timeout"===g.$b.method&&h.sc&&(l("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
g.$b.method=""),g.$b.Re(f),k<g.$b.vc||g.$b.pc()))};e||(b&&0<b?Ac(0,1E3/b):Ac(1,1),g.$b.pc());if(c)throw"SimulateInfiniteLoop";}var Ec=0,Fc=!1;function Gc(){for(var a=Hc.length-1;0<=a;--a)Ic(a);Hc=[];Jc=[]}var Jc=[];function Kc(){if(Lc&&Mc.re)for(var a=0;a<Jc.length;++a){var b=Jc[a];Jc.splice(a,1);--a;b.Th.apply(this,b.yh)}}var Lc=0,Mc=null,Hc=[];function Ic(a){var b=Hc[a];b.target.removeEventListener(b.Xc,b.ze,b.le);Hc.splice(a,1)}
function Nc(a){function b(b){++Lc;Mc=a;Kc();a.Ge(b);Kc();--Lc}if(a.we)a.ze=b,a.target.addEventListener(a.Xc,b,a.le),Hc.push(a),Fc||(Va.push(Gc),Fc=!0);else for(var c=0;c<Hc.length;++c)Hc[c].target==a.target&&Hc[c].Xc==a.Xc&&Ic(c--)}function Oc(a){return a===a+0?F(a):a}var Pc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function Qc(a,b,c,d,e,f){Ec||(Ec=Fa(1684));a=Pc[a]||("undefined"!==typeof document?document.querySelector(Oc(a)):void 0);Nc({target:a,re:"touchstart"==f||"touchend"==f,Xc:f,we:d,Ge:function(c){c=c||event;for(var f={},k=0;k<c.touches.length;++k){var u=c.touches[k];u.Jd=!1;f[u.identifier]=u}for(k=0;k<c.changedTouches.length;++k)u=c.changedTouches[k],f[u.identifier]=u,u.Jd=!0;for(k=0;k<c.targetTouches.length;++k)u=c.targetTouches[k],f[u.identifier].Pe=!0;var t=u=Ec;x[t+4>>2]=c.ctrlKey;x[t+8>>2]=c.shiftKey;
x[t+12>>2]=c.altKey;x[t+16>>2]=c.metaKey;t+=20;var K=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},D=0;for(k in f){var y=f[k];x[t>>2]=y.identifier;x[t+4>>2]=y.screenX;x[t+8>>2]=y.screenY;x[t+12>>2]=y.clientX;x[t+16>>2]=y.clientY;x[t+20>>2]=y.pageX;x[t+24>>2]=y.pageY;x[t+28>>2]=y.Jd;x[t+32>>2]=y.Pe;x[t+36>>2]=y.clientX-K.left;x[t+40>>2]=y.clientY-K.top;t+=52;if(32<=++D)break}x[u>>2]=D;Rc(d,e,u,b)&&c.preventDefault()},le:c})}var Sc={};
function Tc(){if(!Uc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da},b;for(b in Sc)a[b]=Sc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Uc=c}return Uc}var Uc,Vc=1,Wc=0,Xc=[],T=[],Yc=[],Zc=[],$c=[],ad=[],U=[],bd=[],Dc={},S=null,cd=[],dd={},ed={},fd=4;function V(a){Wc||(Wc=a)}function gd(a){for(var b=Vc++,c=a.length;c<b;c++)a[c]=null;return b}
var hd=null,id=[0];function Cc(a,b){return(a=1<b.Yd?a.getContext("webgl2",b):a.getContext("webgl",b)||a.getContext("experimental-webgl",b))?jd(a,b):0}function jd(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=Fa(8),e={handle:d,attributes:b,version:b.Yd,Gc:a};e.md=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.xh=e);Dc[d]=e;("undefined"===typeof b.ye||b.ye)&&kd(e);return d}
function ld(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,f){b.drawArraysInstancedANGLE(a,d,e,f)},a.drawElementsInstanced=function(a,d,e,f,k){b.drawElementsInstancedANGLE(a,d,e,f,k)})}
function md(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function nd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function kd(a){a||(a=S);if(!a.Ie){a.Ie=!0;var b=a.Gc;2>a.version&&(ld(b),md(b),nd(b));b.Ch=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var Bc={},od,pd,qd=[];function rd(a,b,c,d){for(var e=0;e<a;e++){var f=R[c](),k=f&&gd(d);f?(f.name=k,d[k]=f):V(1282);x[b+4*e>>2]=k}}
function sd(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=R.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>S.version){V(1282);return}c=2*(R.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){V(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=R.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:V(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)x[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V(1280);l("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:V(1280);l("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}x[b>>2]=c}else V(1281)}
function td(a){var b=Ja(a)+1,c=Fa(b);Ia(a,E,c,b);return c}var ud={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},vd={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function wd(a,b,c,d,e){if(b=ud[b]*vd[a]){var f=fd;c=e+d*(c*b+f-1&-f);switch(a){case 5120:return w.subarray(e,c);case 5121:return E.subarray(e,c);case 5122:return wa.subarray(e>>1,c>>1);case 5124:return x.subarray(e>>2,c>>2);case 5126:return B.subarray(e>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:return Oa.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Na.subarray(e>>1,c>>1);default:V(1280)}}else V(1280)}
function xd(a){switch(a){case 5120:return w;case 5121:return E;case 5122:return wa;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Na;case 5124:return x;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return Oa;case 5126:return B}}var yd={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1};
function zd(a,b,c,d,e){this.id=a;this.y=this.x=0;this.wd=!1;this.je=this.ie=0;this.width=b;this.height=c;this.he=b;this.ge=c;this.title=d;this.share=e;this.attributes=Ad;this.$c={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.ud=[];this.Tc=this.bd=this.Md=this.kd=this.Vc=this.Wc=this.dd=this.Qd=this.sd=this.Ec=this.ne=this.title=null}function W(a){return 0>=a||!X?null:X[a-1]}
var Bd=null,Cd=null,Y=null,X=null,Dd=null,Ed=null,Ad=null,Fd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Gd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Hd(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Id(a){Y&&Y.Tc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||Jd(Y.Tc,Y.id,a))}function Kd(a,b){if(Y){var c=Gd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.ud[a]=b;Y.bd&&(d&&(b=2),Ld(Y.bd,Y.id,c,a,b,Hd()))}}}
function Md(){Nd()}function Od(){Nd()}function Pd(a){Kd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Qd(a){Kd(a.keyCode,0)}function Rd(){if(Y)for(var a=0;a<Y.ud.length;++a)Y.ud[a]&&Kd(a,0)}function Sd(a){Y&&(g.Id(a),a.target==h.canvas&&Y.Wc&&Td(Y.Wc,Y.id,g.xc,g.yc))}function Ud(a){Y&&a.target==h.canvas&&Y.Vc&&Jd(Y.Vc,Y.id,1)}function Vd(a){Y&&a.target==h.canvas&&Y.Vc&&Jd(Y.Vc,Y.id,0)}
function Wd(a,b){if(Y&&(g.Id(a),a.target==h.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.dd&&Xd(Y.dd,Y.id,c,b,Hd())}}function Yd(a){Y&&Wd(a,1)}function Zd(a){Y&&Wd(a,0)}function $d(a){g.De(a);if(Y&&Y.kd&&a.target==h.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;Td(Y.kd,Y.id,b,c);a.preventDefault()}}
function ae(){(h.canvas.requestFullscreen||h.canvas.mozRequestFullScreen||h.canvas.webkitRequestFullScreen||function(){}).apply(h.canvas,[])}var Z={},be=null,ce=null;
function Nd(){if(g.$b.uc!==ce||!g.$b.uc){be=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;ce=g.$b.uc;for(var a=0;a<be.length;++a){var b=be[a];if(b){Z[a]||(console.log("glfw joystick connected:",a),Z[a]={id:Ea(ub(b.id),"i8"),ue:b.buttons.length,te:b.axes.length,buttons:Ea(Array(b.buttons.length),"i8"),axes:Ea(Array(4*b.axes.length),"float")});for(var c=Z[a],d=0;d<b.buttons.length;++d)v(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)v(c.axes+
4*d,b.axes[d],"float")}else Z[a]&&(console.log("glfw joystick disconnected",a),de(Z[a].id),de(Z[a].buttons),de(Z[a].axes),delete Z[a])}}}function ee(a){if(Y&&Y.Md&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1}function fe(a){if(Y&&Y.Md)return a.preventDefault(),!1}function ge(a){!g.Oc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),a.preventDefault())}function he(a){return 0===a%4&&(0!==a%100||0===a%400)}
function ie(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var je=[31,29,31,30,31,30,31,31,30,31,30,31],ke=[31,28,31,30,31,30,31,31,30,31,30,31];function le(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(he(a.getFullYear())?je:ke)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function me(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function r(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function p(a){a=le(new Date(a.hc+1900,0,1),a.rd);var b=r(new Date(a.getFullYear()+1,0,4));return 0>=k(r(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var u=x[d+40>>2];d={af:x[d>>2],$e:x[d+4>>2],pd:x[d+8>>2],Qc:x[d+12>>2],Dc:x[d+16>>2],hc:x[d+20>>2],qd:x[d+24>>2],rd:x[d+28>>2],Uh:x[d+32>>2],Ze:x[d+36>>2],
bf:u?F(u):""};c=F(c);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in u)c=c.replace(new RegExp(t,"g"),u[t]);var K="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
D="January February March April May June July August September October November December".split(" ");u={"%a":function(a){return K[a.qd].substring(0,3)},"%A":function(a){return K[a.qd]},"%b":function(a){return D[a.Dc].substring(0,3)},"%B":function(a){return D[a.Dc]},"%C":function(a){return f((a.hc+1900)/100|0,2)},"%d":function(a){return f(a.Qc,2)},"%e":function(a){return e(a.Qc,2," ")},"%g":function(a){return p(a).toString().substring(2)},"%G":function(a){return p(a)},"%H":function(a){return f(a.pd,
2)},"%I":function(a){a=a.pd;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.Qc+ie(he(a.hc+1900)?je:ke,a.Dc-1),3)},"%m":function(a){return f(a.Dc+1,2)},"%M":function(a){return f(a.$e,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.pd&&12>a.pd?"AM":"PM"},"%S":function(a){return f(a.af,2)},"%t":function(){return"\t"},"%u":function(a){return a.qd||7},"%U":function(a){var b=new Date(a.hc+1900,0,1),c=0===b.getDay()?b:le(b,7-b.getDay());a=new Date(a.hc+1900,a.Dc,a.Qc);return 0>
k(c,a)?f(Math.ceil((31-c.getDate()+(ie(he(a.getFullYear())?je:ke,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=r(new Date(a.hc+1900,0,4)),c=r(new Date(a.hc+1901,0,4)),d=le(new Date(a.hc+1900,0,1),a.rd);return 0>k(d,b)?"53":0>=k(c,d)?"01":f(Math.ceil((b.getFullYear()<a.hc+1900?a.rd+32-b.getDate():a.rd+1-b.getDate())/7),2)},"%w":function(a){return a.qd},"%W":function(a){var b=new Date(a.hc,0,1),c=1===b.getDay()?b:le(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.hc+
1900,a.Dc,a.Qc);return 0>k(c,a)?f(Math.ceil((31-c.getDate()+(ie(he(a.getFullYear())?je:ke,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.hc+1900).toString().substring(2)},"%Y":function(a){return a.hc+1900},"%z":function(a){a=a.Ze;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.bf},"%%":function(){return"%"}};for(t in u)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),u[t](d)));t=ub(c,!1);if(t.length>
b)return 0;w.set(t,a);return t.length-1}kc();Jb=Array(4096);Yb(I,"/");N("/tmp");N("/home");N("/home/web_user");
(function(){N("/dev");sb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});$b("/dev/null",259);rb(1280,vb);rb(1536,yb);$b("/dev/tty",1280);$b("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){q("random_device")});O("/dev","random",b);O("/dev","urandom",b);
N("/dev/shm");N("/dev/shm/tmp")})();N("/proc");N("/proc/self");N("/proc/self/fd");Yb({ic:function(){var a=Ab("/proc/self","fd",16895,73);a.bc={lookup:function(a,c){var b=Hb[+c];if(!b)throw new H(8);a={parent:null,ic:{$d:"fake"},bc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");h.FS_createFolder=nc;h.FS_createPath=oc;h.FS_createDataFile=qc;h.FS_createPreloadedFile=uc;h.FS_createLazyFile=tc;h.FS_createLink=rc;h.FS_createDevice=O;h.FS_unlink=bc;
if(ia){var fs=require("fs"),Eb=require("path");L.Xe()}ha?yc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?yc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?yc=function(){return performance.now()}:yc=Date.now;h.requestFullScreen=function(a,b,c){l("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");h.requestFullScreen=h.requestFullscreen;g.ee(a,b,c)};
h.requestFullscreen=function(a,b,c){g.requestFullscreen(a,b,c)};h.requestAnimationFrame=function(a){g.requestAnimationFrame(a)};h.setCanvasSize=function(a,b,c){g.ld(a,b,c)};h.pauseMainLoop=function(){g.$b.pause()};h.resumeMainLoop=function(){g.$b.resume()};h.getUserMedia=function(){g.getUserMedia()};h.createContext=function(a,b,c,d){return g.createContext(a,b,c,d)};var R;hd=new Float32Array(256);for(var ne=0;256>ne;ne++)id[ne]=hd.subarray(0,ne+1);for(var oe=0;32>oe;oe++)qd.push(Array(oe));
function ub(a,b){var c=Array(Ja(a)+1);a=Ia(a,c,0,c.length);b&&(c.length=a);return c}
var te={e:function(a){return Fa(a)},g:function(a){"uncaught_exception"in pe?pe.Fc++:pe.Fc=1;throw a;},sa:function(){},pb:function(){jb(63);return-1},yb:function(a,b){wc=b;try{var c=xc(),d=Q(),e=Q();if(!c.tc){var f=M(c.path,{Yc:!0}).node;if(!f.bc.readdir)throw new H(54);var k=f.bc.readdir(f);c.tc=k}a=0;for(var r=ic(c,0,1),p=Math.floor(r/280);p<c.tc.length&&a+280<=e;){var u=c.tc[p];if("."===u[0]){var t=1;var K=4}else{var D=Cb(c.node,u);t=D.id;K=8192===(D.mode&61440)?2:J(D.mode)?4:40960===(D.mode&61440)?
10:8}z=[t>>>0,(A=t,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[d+a>>2]=z[0];x[d+a+4>>2]=z[1];z=[280*(p+1)>>>0,(A=280*(p+1),1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[d+a+8>>2]=z[0];x[d+a+12>>2]=z[1];wa[d+a+16>>1]=280;w[d+a+18>>0]=K;Ia(u,E,d+a+19,256);a+=280;p+=1}ic(c,280*p,0);return a}catch(y){return"undefined"!==typeof P&&y instanceof H||q(y),-y.kc}},ra:function(a,b){wc=b;try{var c=xc();switch(Q()){case 0:var d=
Q();return 0>d?-28:ec(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Q(),c.flags|=d,0;case 12:return d=Q(),wa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return jb(28),-1;default:return-28}}catch(e){return"undefined"!==typeof P&&e instanceof H||q(e),-e.kc}},ta:function(a,b){wc=b;try{var c=F(Q()),d=Q(),e=Q();return ec(c,d,e).fd}catch(f){return"undefined"!==typeof P&&f instanceof H||q(f),-f.kc}},wb:function(a,b){wc=b;try{var c=xc(),d=Q();
switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var e=Q();return x[e>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=e=Q();if(!c.cc.Ke)throw new H(59);return c.cc.Ke(c,d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:q("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof P&&f instanceof H||q(f),-f.kc}},ob:function(a,b){wc=b;try{var c=Q(),d=Q();if(-1===
c||0===d)var e=-28;else{var f=vc[c];if(f&&d===f.Jh){var k=Hb[f.fd],r=f.flags,p=new Uint8Array(E.subarray(c,c+d));k&&k.cc.hd&&k.cc.hd(k,p,0,d,r);vc[c]=null;f.qe&&de(f.Kh)}e=0}return e}catch(u){return"undefined"!==typeof P&&u instanceof H||q(u),-u.kc}},y:function(){},I:function(){q()},tb:function(a,b){if(0===a)a=Date.now();else if(1===a&&(ha||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=yc();else return jb(28),-1;x[b>>2]=a/1E3|0;x[b+
4>>2]=a%1E3*1E6|0;return 0},lb:function(a,b,c){E.set(E.subarray(b,b+c),a)},mb:function(a){if(2147418112<a)return!1;for(var b=Math.max(w.length,16777216);b<a;)536870912>=b?b=Ma(2*b):b=Math.min(Ma((3*b+2147483648)/4),2147418112);a:{try{Ca.grow(b-buffer.byteLength+65535>>16);Pa(Ca.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},Ib:zc,Ea:function(a,b,c,d){Qc(a,b,c,d,25,"touchcancel");return 0},Ga:function(a,b,c,d){Qc(a,b,c,d,23,"touchend");return 0},Fa:function(a,b,c,d){Qc(a,b,c,d,24,"touchmove");
return 0},Ha:function(a,b,c,d){Qc(a,b,c,d,22,"touchstart");return 0},qb:function(a,b){var c=0;Tc().forEach(function(d,e){var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)w[e++>>0]=d.charCodeAt(f);w[e>>0]=0;c+=d.length+1});return 0},rb:function(a,b){var c=Tc();x[a>>2]=c.length;var d=0;c.forEach(function(a){d+=a.length+1});x[b>>2]=d;return 0},Ba:function(a){qe(a)},J:function(a){try{var b=xc(a);hc(b);return 0}catch(c){return"undefined"!==typeof P&&c instanceof H||q(c),c.kc}},vb:function(a,b,c,d){try{a:{for(var e=
xc(a),f=a=0;f<c;f++){var k=x[b+(8*f+4)>>2],r=e,p=x[b+8*f>>2],u=k,t=void 0,K=w;if(0>u||0>t)throw new H(28);if(null===r.fd)throw new H(8);if(1===(r.flags&2097155))throw new H(8);if(J(r.node.mode))throw new H(31);if(!r.cc.read)throw new H(28);var D="undefined"!==typeof t;if(!D)t=r.position;else if(!r.seekable)throw new H(70);var y=r.cc.read(r,K,p,u,t);D||(r.position+=y);var wb=y;if(0>wb){var dc=-1;break a}a+=wb;if(wb<k)break}dc=a}x[d>>2]=dc;return 0}catch(xb){return"undefined"!==typeof P&&xb instanceof
H||q(xb),xb.kc}},kb:function(a,b,c,d,e){try{var f=xc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;ic(f,a,d);z=[f.position>>>0,(A=f.position,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[e>>2]=z[0];x[e+4>>2]=z[1];f.tc&&0===a&&0===d&&(f.tc=null);return 0}catch(k){return"undefined"!==typeof P&&k instanceof H||q(k),k.kc}},ub:function(a,b,c,d){try{a:{for(var e=xc(a),f=a=0;f<c;f++){var k=jc(e,w,x[b+8*f>>2],x[b+(8*f+
4)>>2],void 0);if(0>k){var r=-1;break a}a+=k}r=a}x[d>>2]=r;return 0}catch(p){return"undefined"!==typeof P&&p instanceof H||q(p),p.kc}},f:function(a){R.activeTexture(a)},R:function(a,b){R.attachShader(T[a],U[b])},d:function(a,b){35051==a?R.Ld=b:35052==a&&(R.td=b);R.bindBuffer(a,Xc[b])},wa:function(a,b,c){R.bindBufferBase(a,b,Xc[c])},i:function(a,b){R.bindFramebuffer(a,Yc[b])},Db:function(a,b){R.bindRenderbuffer(a,Zc[b])},ba:function(a,b){R.bindSampler(a,cd[b])},a:function(a,b){R.bindTexture(a,$c[b])},
o:function(a){R.bindVertexArray(bd[a])},Ra:function(a){R.blendEquation(a)},Ua:function(a,b){R.blendEquationSeparate(a,b)},aa:function(a,b){R.blendFunc(a,b)},Ta:function(a,b,c,d){R.blendFuncSeparate(a,b,c,d)},r:function(a,b,c,d){S.md?c?R.bufferData(a,E,d,c,b):R.bufferData(a,b,d):R.bufferData(a,c?E.subarray(c,c+b):b,d)},p:function(a,b,c,d){S.md?R.bufferSubData(a,b,E,d,c):R.bufferSubData(a,b,E.subarray(d,d+c))},xa:function(a){return R.checkFramebufferStatus(a)},Na:function(a){R.clear(a)},z:function(a,
b,c){R.clearBufferfv(a,b,B,c>>2)},Oa:function(a,b,c,d){R.clearColor(a,b,c,d)},S:function(a){R.compileShader(U[a])},ea:function(){var a=gd(T),b=R.createProgram();b.name=a;T[a]=b;return a},G:function(a){var b=gd(U);U[b]=R.createShader(a);return b},t:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Xc[d];e&&(R.deleteBuffer(e),e.name=0,Xc[d]=null,d==od&&(od=0),d==pd&&(pd=0),d==R.Ld&&(R.Ld=0),d==R.td&&(R.td=0))}},Hb:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Yc[d];e&&(R.deleteFramebuffer(e),
e.name=0,Yc[d]=null)}},fa:function(a){if(a){var b=T[a];b?(R.deleteProgram(b),b.name=0,T[a]=null,dd[a]=null):V(1281)}},Gb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Zc[d];e&&(R.deleteRenderbuffer(e),e.name=0,Zc[d]=null)}},H:function(a){if(a){var b=U[a];b?(R.deleteShader(b),U[a]=null):V(1281)}},D:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=$c[d];e&&(R.deleteTexture(e),e.name=0,$c[d]=null)}},M:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];R.deleteVertexArray(bd[d]);bd[d]=
null}},W:function(a){R.depthMask(!!a)},U:function(a,b){R.detachShader(T[a],U[b])},m:function(a){R.disable(a)},za:function(a,b,c){R.drawArrays(a,b,c)},Ab:function(a,b){for(var c=qd[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];R.drawBuffers(c)},Va:function(a,b,c,d){R.drawElements(a,b,c,d)},j:function(a){R.enable(a)},w:function(a){R.enableVertexAttribArray(a)},Bb:function(a,b,c,d){R.framebufferRenderbuffer(a,b,c,Zc[d])},Y:function(a,b,c,d,e){R.framebufferTexture2D(a,b,c,$c[d],e)},s:function(a,b){rd(a,b,"createBuffer",
Xc)},ya:function(a,b){rd(a,b,"createFramebuffer",Yc)},Eb:function(a,b){rd(a,b,"createRenderbuffer",Zc)},k:function(a,b){rd(a,b,"createTexture",$c)},O:function(a,b){rd(a,b,"createVertexArray",bd)},La:function(a){R.generateMipmap(a)},zb:function(a,b,c,d){if(d)switch(a=T[a],c){case 35393:a=R.getActiveUniformBlockName(a,b);x[d>>2]=a.length+1;break;default:if(a=R.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)x[d>>2]=a;else for(b=0;b<a.length;b++)x[d+4*b>>2]=a[b]}else V(1281)},P:function(a,
b){return R.getAttribLocation(T[a],F(b))},b:function(a,b){sd(a,b)},Z:function(a,b,c,d){a=R.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ia(a,E,d,b):0;c&&(x[c>>2]=b)},B:function(a,b,c){if(c)if(a>=Vc)V(1281);else{var d=dd[a];if(d)if(35716==b)a=R.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.zd;else if(35722==b){if(-1==d.Jc){a=T[a];var e=R.getProgramParameter(a,35721);for(b=d.Jc=0;b<e;++b)d.Jc=Math.max(d.Jc,R.getActiveAttrib(a,
b).name.length+1)}x[c>>2]=d.Jc}else if(35381==b){if(-1==d.Kc)for(a=T[a],e=R.getProgramParameter(a,35382),b=d.Kc=0;b<e;++b)d.Kc=Math.max(d.Kc,R.getActiveUniformBlockName(a,b).length+1);x[c>>2]=d.Kc}else x[c>>2]=R.getProgramParameter(T[a],b);else V(1282)}else V(1281)},_:function(a,b,c,d){a=R.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ia(a,E,d,b):0;c&&(x[c>>2]=b)},C:function(a,b,c){c?35716==b?(a=R.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1):35720==
b?(a=R.getShaderSource(U[a]),x[c>>2]=null===a||0==a.length?0:a.length+1):x[c>>2]=R.getShaderParameter(U[a],b):V(1281)},A:function(a){if(ed[a])return ed[a];switch(a){case 7939:var b=R.getSupportedExtensions()||[];b=b.concat(b.map(function(a){return"GL_"+a}));b=td(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=R.getParameter(a))||V(1280);b=td(b);break;case 7938:b=R.getParameter(R.VERSION);b=2<=S.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=td(b);break;case 35724:b=R.getParameter(R.SHADING_LANGUAGE_VERSION);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=td(b);break;default:return V(1280),0}return ed[a]=b},va:function(a,b){return R.getUniformBlockIndex(T[a],F(b))},Q:function(a,b){b=F(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=dd[a]&&dd[a].ke[b])&&0<=c&&c<a[0]?a[1]+c:-1},F:function(a){return R.isEnabled(a)},da:function(a){R.linkProgram(T[a]);
var b=T[a];a=dd[a]={ke:{},zd:0,Jc:-1,Kc:-1};for(var c=a.ke,d=R.getProgramParameter(b,35718),e=0;e<d;++e){var f=R.getActiveUniform(b,e),k=f.name;a.zd=Math.max(a.zd,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var r=R.getUniformLocation(b,k);if(r){var p=gd(ad);c[k]=[f.size,p];ad[p]=r;for(var u=1;u<f.size;++u)r=R.getUniformLocation(b,k+"["+u+"]"),p=gd(ad),ad[p]=r}}},Pa:function(a,b){3317==a&&(fd=b);R.pixelStorei(a,b)},Cb:function(a,b,c,d){R.renderbufferStorage(a,b,c,d)},ca:function(a,
b,c,d){R.scissor(a,b,c,d)},T:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?x[d+4*f>>2]:-1;e+=F(x[c+4*f>>2],0>k?void 0:k)}R.shaderSource(U[a],e)},q:function(a,b,c,d,e,f,k,r,p){S.md?R.td?R.texImage2D(a,b,c,d,e,f,k,r,p):0!=p?R.texImage2D(a,b,c,d,e,f,k,r,xd(r),p>>(yd[r]|0)):R.texImage2D(a,b,c,d,e,f,k,r,null):R.texImage2D(a,b,c,d,e,f,k,r,p?wd(r,k,d,e,p):null)},X:function(a,b,c){R.texParameterf(a,b,c)},c:function(a,b,c){R.texParameteri(a,b,c)},$:function(a,b){R.uniform1i(ad[a],b)},ua:function(a,b,
c){a=T[a];R.uniformBlockBinding(a,b,c)},Qa:function(a,b,c,d){if(S.md)R.uniformMatrix4fv(ad[a],!!c,B,d>>2,16*b);else{if(256>=16*b)for(var e=id[16*b-1],f=0;f<16*b;f+=16)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2],e[f+4]=B[d+(4*f+16)>>2],e[f+5]=B[d+(4*f+20)>>2],e[f+6]=B[d+(4*f+24)>>2],e[f+7]=B[d+(4*f+28)>>2],e[f+8]=B[d+(4*f+32)>>2],e[f+9]=B[d+(4*f+36)>>2],e[f+10]=B[d+(4*f+40)>>2],e[f+11]=B[d+(4*f+44)>>2],e[f+12]=B[d+(4*f+48)>>2],e[f+13]=B[d+(4*f+52)>>2],e[f+
14]=B[d+(4*f+56)>>2],e[f+15]=B[d+(4*f+60)>>2];else e=B.subarray(d>>2,d+64*b>>2);R.uniformMatrix4fv(ad[a],!!c,e)}},L:function(a){R.useProgram(T[a])},v:function(a,b,c,d,e,f){R.vertexAttribPointer(a,b,c,!!d,e,f)},l:function(a,b,c,d){R.viewport(a,b,c,d)},n:function(){},na:function(a,b,c,d,e){var f;for(f=0;f<X.length&&null!==X[f];f++);if(0<f)throw"glfwCreateWindow only supports one window at time currently";var k=f+1;if(0>=a||0>=b)k=0;else{d?ae():g.ld(a,b);for(f=0;f<X.length&&null==X[f];f++);f==X.length&&
(h.sc=g.createContext(h.canvas,!0,!0,{antialias:1<Ad[135181],depth:0<Ad[135173],stencil:0<Ad[135174],alpha:0<Ad[135172]}));h.sc?(a=new zd(k,a,b,c,e),k-1==X.length?X.push(a):X[k-1]=a,Y=a,k=a.id):k=0}return k},Xa:function(){throw"glfwCreateWindowSurface is not implemented.";},Wa:function(){},ja:function(a){a:{if(a=W(a)){a.sd&&re(a.sd,a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}h.sc=void 0}a=void 0}return a},Za:function(){},db:function(){},qa:function(a,
b,c){v(b,g.xc,"double");v(c,g.yc,"double")},Sa:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.width,e=a.height;v(b,d,"i32");v(c,e,"i32")},jb:function(a,b){if(a=W(a)){switch(b){case 208897:a.$c[b]=g.Oc?212995:212993}return a.$c[b]}},gb:function(a,b){Nd();if((a=Z[a])&&a.axes)return v(b,a.te,"i32"),a.axes;v(b,0,"i32")},fb:function(a,b){Nd();if((a=Z[a])&&a.buttons)return v(b,a.ue,"i32"),a.buttons;v(b,0,"i32")},u:function(a,b){return(a=W(a))?a.keys[b]:0},Kb:function(a,b,c){v(b,0,"i32");v(c,0,"i32")},Ma:function(a){v(a,
1,"i32");Dd||(Dd=Ea([1,0,0,0],"i32"));return Dd},K:function(a,b){return(a=W(a))?0<(a.buttons&1<<b):0},E:function(){return yc()/1E3-Ed},Fb:function(){return 0},ia:function(a,b){return(a=W(a))?a.attributes[b]:0},pa:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.x,e=a.y;v(b,d,"i32");v(c,e,"i32")},N:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.width,e=a.height;v(b,d,"i32");v(c,e,"i32")},Ia:function(){if(X)return 1;Ed=yc()/1E3;Ad=Fd;X=[];Y=null;window.addEventListener("gamepadconnected",Md,!0);window.addEventListener("gamepaddisconnected",
Od,!0);window.addEventListener("keydown",Pd,!0);window.addEventListener("keypress",Id,!0);window.addEventListener("keyup",Qd,!0);window.addEventListener("blur",Rd,!0);h.canvas.addEventListener("mousemove",Sd,!0);h.canvas.addEventListener("mousedown",Yd,!0);h.canvas.addEventListener("mouseup",Zd,!0);h.canvas.addEventListener("wheel",$d,!0);h.canvas.addEventListener("mousewheel",$d,!0);h.canvas.addEventListener("mouseenter",Ud,!0);h.canvas.addEventListener("mouseleave",Vd,!0);h.canvas.addEventListener("drop",
ee,!0);h.canvas.addEventListener("dragover",fe,!0);g.fe.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.ie=Y.x,Y.je=Y.y,Y.he=Y.width,Y.ge=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.wd=!0):1==Y.wd?(Y.x=Y.ie,Y.y=Y.je,Y.width=Y.he,Y.height=Y.ge,Y.wd=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(g.ld(Y.width,Y.height,!0),Y&&Y.Ec&&se(Y.Ec,Y.id,Y.width,Y.height),Y&&Y.Qd&&se(Y.Qd,Y.id,Y.width,
Y.height))}});return 1},x:function(){},Jb:function(){},ga:function(a,b){if(a=W(a)){var c=a.Tc;a.Tc=b;b=c}else b=null;return b},eb:function(){},ib:function(){},xb:function(){},Da:function(a,b){if(a=W(a)){var c=a.Wc;a.Wc=b;b=c}else b=null;return b},Ja:function(a){var b=Bd;Bd=a;return b},hb:function(a,b,c){if(a=W(a))switch(b){case 208897:switch(c){case 212993:a.$c[b]=c;h.canvas.removeEventListener("click",ge,!0);h.canvas.exitPointerLock();break;case 212994:console.log("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented.");
break;case 212995:a.$c[b]=c;h.canvas.addEventListener("click",ge,!0);h.canvas.requestPointerLock();break;default:console.log("glfwSetInputMode called with unknown value parameter value: "+c+".")}break;case 208898:console.log("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented.");break;case 208899:console.log("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented.");break;default:console.log("glfwSetInputMode called with unknown mode parameter value: "+b+".")}},
la:function(a,b){if(a=W(a)){var c=a.bd;a.bd=b;b=c}else b=null;return b},cb:function(a){var b=Cd;Cd=a;return b},Ca:function(a,b){if(a=W(a)){var c=a.dd;a.dd=b;b=c}else b=null;return b},oa:function(a,b){if(a=W(a)){var c=a.kd;a.kd=b;b=c}else b=null;return b},bb:function(a,b){if(a=W(a)){var c=a.sd;a.sd=b;b=c}else b=null;return b},V:function(a,b,c){if(a=W(a))a.x=b,a.y=c},ab:function(a,b){a=W(a);if(!a)return null;var c=a.ne;a.ne=b;return c},_a:function(a,b,c){if(a=W(a))Y.id==a.id&&(b==screen.width&&c==screen.height?
ae():(g.exitFullscreen(),g.ld(b,c),a.width=b,a.height=c)),a.Ec&&se(a.Ec,a.id,b,c)},ma:function(a,b){if(a=W(a)){var c=a.Ec;a.Ec=b;b=c}else b=null;return b},Ya:function(a,b){if(a=W(a))a.title=F(b),Y.id==a.id&&(document.title=a.title)},$a:function(){},ha:function(){},ka:function(a){a=Math.abs(a);0==a?Ac(0,0):Ac(1,a)},Aa:function(){window.removeEventListener("gamepadconnected",Md,!0);window.removeEventListener("gamepaddisconnected",Od,!0);window.removeEventListener("keydown",Pd,!0);window.removeEventListener("keypress",
Id,!0);window.removeEventListener("keyup",Qd,!0);window.removeEventListener("blur",Rd,!0);h.canvas.removeEventListener("mousemove",Sd,!0);h.canvas.removeEventListener("mousedown",Yd,!0);h.canvas.removeEventListener("mouseup",Zd,!0);h.canvas.removeEventListener("wheel",$d,!0);h.canvas.removeEventListener("mousewheel",$d,!0);h.canvas.removeEventListener("mouseenter",Ud,!0);h.canvas.removeEventListener("mouseleave",Vd,!0);h.canvas.removeEventListener("drop",ee,!0);h.canvas.removeEventListener("dragover",
fe,!0);h.canvas.width=h.canvas.height=1;Y=X=null},h:function(a,b){Ad[a]=b},memory:Ca,sb:function(){return 0},nb:function(a,b,c,d){return me(a,b,c,d)},table:Da,Ka:function(a){var b=Date.now()/1E3|0;a&&(x[a>>2]=b);return b}},ue=function(){function a(a){h.asm=a.exports;cb("wasm-instantiate")}function b(b){a(b.instance)}function c(a){return hb().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){l("failed to asynchronously prepare wasm: "+a);q(a)})}var d={env:te,wasi_unstable:te};
bb("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(ua||"function"!==typeof WebAssembly.instantiateStreaming||db()||"function"!==typeof fetch)return c(b);fetch(eb,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){l("wasm streaming compile failed: "+a);l("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();
h.asm=ue;var ib=h.___wasm_call_ctors=function(){return h.asm.Lb.apply(null,arguments)},Fa=h._malloc=function(){return h.asm.Mb.apply(null,arguments)},de=h._free=function(){return h.asm.Nb.apply(null,arguments)};h.___errno_location=function(){return h.asm.Ob.apply(null,arguments)};h._main=function(){return h.asm.Pb.apply(null,arguments)};
var pe=h.__ZSt18uncaught_exceptionv=function(){return h.asm.Qb.apply(null,arguments)},La=h.stackAlloc=function(){return h.asm.Rb.apply(null,arguments)},re=h.dynCall_vi=function(){return h.asm.Sb.apply(null,arguments)},Jd=h.dynCall_vii=function(){return h.asm.Tb.apply(null,arguments)},se=h.dynCall_viii=function(){return h.asm.Ub.apply(null,arguments)},Xd=h.dynCall_viiii=function(){return h.asm.Vb.apply(null,arguments)},Rc=h.dynCall_iiii=function(){return h.asm.Wb.apply(null,arguments)},Td=h.dynCall_vidd=
function(){return h.asm.Xb.apply(null,arguments)},Ld=h.dynCall_viiiii=function(){return h.asm.Yb.apply(null,arguments)};h.dynCall_v=function(){return h.asm.Zb.apply(null,arguments)};h.asm=ue;h.getMemory=function(a){if(Xa)var b=Fa(a);else b=x[26168],a=b+a+15&-16,a>w.length&&q(),x[26168]=a;return b};h.addRunDependency=bb;h.removeRunDependency=cb;h.FS_createFolder=nc;h.FS_createPath=oc;h.FS_createDataFile=qc;h.FS_createPreloadedFile=uc;h.FS_createLazyFile=tc;h.FS_createLink=rc;h.FS_createDevice=O;
h.FS_unlink=bc;h.calledRun=ve;var ve;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ab=function we(){ve||xe();ve||(ab=we)};
function xe(a){function b(){if(!ve&&(ve=!0,h.calledRun=!0,!C)){Xa=!0;h.noFSInit||lc||(lc=!0,kc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?O("/dev","stdin",h.stdin):ac("/dev/tty","/dev/stdin"),h.stdout?O("/dev","stdout",null,h.stdout):ac("/dev/tty","/dev/stdout"),h.stderr?O("/dev","stderr",null,h.stderr):ac("/dev/tty1","/dev/stderr"),ec("/dev/stdin","r"),ec("/dev/stdout","w"),ec("/dev/stderr","w"));Ra(Ta);Kb=!1;Ra(Ua);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(ye){var b=
a,d=h._main;b=b||[];var e=b.length+1,f=La(4*(e+1));x[f>>2]=Ka(da);for(var k=1;k<e;k++)x[(f>>2)+k]=Ka(b[k-1]);x[(f>>2)+e]=0;try{var r=d(e,f);qe(r,!0)}catch(p){p instanceof pa||("SimulateInfiniteLoop"==p?va=!0:((b=p)&&"object"===typeof p&&p.stack&&(b=[p,p.stack]),l("exception thrown: "+b),ea(1,p)))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)b=h.postRun.shift(),Wa.unshift(b);Ra(Wa)}}a=a||ca;if(!(0<Za)){if(h.preRun)for("function"==typeof h.preRun&&
(h.preRun=[h.preRun]);h.preRun.length;)Ya();Ra(Sa);0<Za||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=xe;function qe(a,b){if(!b||!va||0!==a){if(!va&&(C=!0,h.onExit))h.onExit(a);ea(a,new pa(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ye=!0;h.noInitialRun&&(ye=!1);va=!0;xe();
