var g;var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.xd||(h.xd=0,h.De=0);h.xd++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var e=b;c.total&&(e=c.total);if(c.loaded){d.Jc?h.zc[a].loaded=c.loaded:(d.Jc=!0,h.zc||(h.zc={}),h.zc[a]={loaded:c.loaded,total:e});var f=e=c=0,k;for(k in h.zc){var p=h.zc[k];c+=p.total;e+=p.loaded;f++}c=Math.ceil(c*h.xd/f);h.setStatus&&h.setStatus("Downloading data... ("+e+"/"+c+")")}else!h.zc&&h.setStatus&&h.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){h.De++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.xe=c;c=a.files;for(var d=
0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();h.removeRunDependency("datafile_R:/emsOut/MinSizeRel/wglChAoSP.data")}h.FS_createPath("/","Shaders",!0,!0);h.FS_createPath("/","ChaoticAttractors",!0,!0);h.FS_createPath("/","colorMaps",!0,!0);h.FS_createPath("/","Fonts",!0,!0);h.FS_createPath("/","startData",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;h.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.xe.subarray(this.start,
this.end))},finish:function(a){h.FS_createDataFile(this.name,null,a,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,e=0;e<d.length;++e)(new b(d[e].start,d[e].end,d[e].audio)).open("GET",d[e].filename);h.addRunDependency("datafile_R:/emsOut/MinSizeRel/wglChAoSP.data");h.ee||(h.ee={});h.ee["R:/emsOut/MinSizeRel/wglChAoSP.data"]={Hh:!1};r?(c(r),r=null):k=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=h.locateFile?h.locateFile("wglChAoSP.data",""):"wglChAoSP.data",f=a.Qh,k=null,r=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;r||b(e,f,function(a){k?(k(a),k=null):r=a},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({package_uuid:"087a3dcd-3dd6-4144-b88a-beadd2c2f95b",remote_package_size:4205826,files:[{audio:0,filename:"/Shaders/allParticles.0.frag",end:12639,start:0},{audio:0,filename:"/Shaders/allParticles.0.vert",end:16723,start:12639},{audio:0,filename:"/Shaders/allParticles.1.frag",
end:29419,start:16723},{audio:0,filename:"/Shaders/allParticles.frag",end:42382,start:29419},{audio:0,filename:"/Shaders/allParticles.vert",end:46468,start:42382},{audio:0,filename:"/Shaders/ambientOcclusionFrag.glsl",end:54959,start:46468},{audio:0,filename:"/Shaders/bilateralVersions.glsl",end:79837,start:54959},{audio:0,filename:"/Shaders/BillboardFrag.glsl",end:80493,start:79837},{audio:0,filename:"/Shaders/BillboardGeom.glsl",end:82531,start:80493},{audio:0,filename:"/Shaders/BillboardVert.glsl",
end:83730,start:82531},{audio:0,filename:"/Shaders/cmTexturedFrag.glsl",end:85293,start:83730},{audio:0,filename:"/Shaders/colorSpaces.glsl",end:90267,start:85293},{audio:0,filename:"/Shaders/fxaaFrag.glsl",end:94088,start:90267},{audio:0,filename:"/Shaders/lightModelsFrag.glsl",end:104118,start:94088},{audio:0,filename:"/Shaders/MergedRenderingFrag.glsl",end:105036,start:104118},{audio:0,filename:"/Shaders/mmFBO_all_vert.glsl",end:105948,start:105036},{audio:0,filename:"/Shaders/MotionBlurFS.glsl",
end:107046,start:105948},{audio:0,filename:"/Shaders/oglAxesFrag.glsl",end:108746,start:107046},{audio:0,filename:"/Shaders/oglAxesVert.glsl",end:110931,start:108746},{audio:0,filename:"/Shaders/ParticlesFrag.glsl",end:116792,start:110931},{audio:0,filename:"/Shaders/ParticlesVert.glsl",end:119752,start:116792},{audio:0,filename:"/Shaders/PointSpriteFragLight.glsl",end:120482,start:119752},{audio:0,filename:"/Shaders/PointSpriteVert.glsl",end:122570,start:120482},{audio:0,filename:"/Shaders/postRenderingFrag.glsl",
end:139134,start:122570},{audio:0,filename:"/Shaders/postRenderingVert.glsl",end:141728,start:139134},{audio:0,filename:"/Shaders/RadialBlur2PassFrag.glsl",end:154560,start:141728},{audio:0,filename:"/Shaders/shadowFrag.glsl",end:155755,start:154560},{audio:0,filename:"/ChaoticAttractors/Aizawa05.sca",end:181023,start:155755},{audio:0,filename:"/ChaoticAttractors/Aizawa06.sca",end:206303,start:181023},{audio:0,filename:"/ChaoticAttractors/Aizawa09.sca",end:231583,start:206303},{audio:0,filename:"/ChaoticAttractors/Aizawa10.sca",
end:256918,start:231583},{audio:0,filename:"/ChaoticAttractors/Aizawa11.sca",end:282250,start:256918},{audio:0,filename:"/ChaoticAttractors/Aizawa12.sca",end:307615,start:282250},{audio:0,filename:"/ChaoticAttractors/Aizawa13.sca",end:332900,start:307615},{audio:0,filename:"/ChaoticAttractors/aliDrago01.sca",end:356975,start:332900},{audio:0,filename:"/ChaoticAttractors/BicomplexJMod0_IIM1.sca",end:381051,start:356975},{audio:0,filename:"/ChaoticAttractors/BicomplexJMod3_IIM4.sca",end:404722,start:381051},
{audio:0,filename:"/ChaoticAttractors/BicomplexJMod3_IIM6.sca",end:428205,start:404722},{audio:0,filename:"/ChaoticAttractors/BicomplexJMod5_IIM.sca",end:452114,start:428205},{audio:0,filename:"/ChaoticAttractors/BicomplexJMod7_IIM.sca",end:476005,start:452114},{audio:0,filename:"/ChaoticAttractors/BicomplexMod_IIM02.sca",end:500143,start:476005},{audio:0,filename:"/ChaoticAttractors/biCplxExpl01a.sca",end:525511,start:500143},{audio:0,filename:"/ChaoticAttractors/biCplxExpl02.sca",end:550871,start:525511},
{audio:0,filename:"/ChaoticAttractors/biTorus_09o4a.sca",end:576005,start:550871},{audio:0,filename:"/ChaoticAttractors/biTorus_09o5.sca",end:601135,start:576005},{audio:0,filename:"/ChaoticAttractors/biTorus_09o8.sca",end:626281,start:601135},{audio:0,filename:"/ChaoticAttractors/dragon3b.sca",end:652440,start:626281},{audio:0,filename:"/ChaoticAttractors/dragon4a.sca",end:678508,start:652440},{audio:0,filename:"/ChaoticAttractors/dreamcatcher01.sca",end:708443,start:678508},{audio:0,filename:"/ChaoticAttractors/flower_0009nc.sca",
end:733515,start:708443},{audio:0,filename:"/ChaoticAttractors/flower_0009nd.sca",end:758589,start:733515},{audio:0,filename:"/ChaoticAttractors/flower_0009ng.sca",end:784611,start:758589},{audio:0,filename:"/ChaoticAttractors/Halvorsen01.sca",end:809879,start:784611},{audio:0,filename:"/ChaoticAttractors/JuliaBulbN7_01.sca",end:834434,start:809879},{audio:0,filename:"/ChaoticAttractors/juliaBulb_IIM02.sca",end:858296,start:834434},{audio:0,filename:"/ChaoticAttractors/Magnetic_stright01.sca",end:883380,
start:858296},{audio:0,filename:"/ChaoticAttractors/Magnetic_stright01a.sca",end:908926,start:883380},{audio:0,filename:"/ChaoticAttractors/Mag_0009e2b.sca",end:934892,start:908926},{audio:0,filename:"/ChaoticAttractors/Pn3D_o06_001.sca",end:963068,start:934892},{audio:0,filename:"/ChaoticAttractors/quatJulia_01.sca",end:986701,start:963068},{audio:0,filename:"/ChaoticAttractors/Rampe03a.sca",end:1012043,start:986701},{audio:0,filename:"/ChaoticAttractors/Rampe07old.sca",end:1036059,start:1012043},
{audio:0,filename:"/ChaoticAttractors/t009e1.sca",end:1062180,start:1036059},{audio:0,filename:"/ChaoticAttractors/Thomas01.sca",end:1086065,start:1062180},{audio:0,filename:"/ChaoticAttractors/torus_0009j.sca",end:1111963,start:1086065},{audio:0,filename:"/ChaoticAttractors/torus_0009k.sca",end:1137175,start:1111963},{audio:0,filename:"/ChaoticAttractors/torus_0009l.sca",end:1162318,start:1137175},{audio:0,filename:"/ChaoticAttractors/torus_0009m1.sca",end:1187549,start:1162318},{audio:0,filename:"/ChaoticAttractors/torus_0009m3.sca",
end:1212781,start:1187549},{audio:0,filename:"/ChaoticAttractors/torus_0009m4.sca",end:1237607,start:1212781},{audio:0,filename:"/ChaoticAttractors/torus_0009nb.sca",end:1262848,start:1237607},{audio:0,filename:"/colorMaps/palettes.json",end:2248110,start:1262848},{audio:0,filename:"/Fonts/Cousine-Regular.ttf",end:2292022,start:2248110},{audio:0,filename:"/Fonts/fontawesome-webfont.ttf",end:2457570,start:2292022},{audio:0,filename:"/Fonts/README.txt",end:2457938,start:2457570},{audio:0,filename:"/startData/Aizawa.sca",
end:2483209,start:2457938},{audio:0,filename:"/startData/Arneodo.sca",end:2508451,start:2483209},{audio:0,filename:"/startData/BicomplexJExplorer.sca",end:2533752,start:2508451},{audio:0,filename:"/startData/BicomplexJMod0_IIM.sca",end:2556902,start:2533752},{audio:0,filename:"/startData/BicomplexJMod1_IIM.sca",end:2582309,start:2556902},{audio:0,filename:"/startData/BicomplexJMod2_IIM.sca",end:2606217,start:2582309},{audio:0,filename:"/startData/BicomplexJMod3_IIM.sca",end:2630081,start:2606217},
{audio:0,filename:"/startData/BicomplexJMod4_IIM.sca",end:2654044,start:2630081},{audio:0,filename:"/startData/BicomplexJMod5_IIM.sca",end:2679484,start:2654044},{audio:0,filename:"/startData/BicomplexJMod6_IIM.sca",end:2703482,start:2679484},{audio:0,filename:"/startData/BicomplexJMod7_IIM.sca",end:2728868,start:2703482},{audio:0,filename:"/startData/BicomplexJ_IIM.sca",end:2752790,start:2728868},{audio:0,filename:"/startData/Bouali.sca",end:2778121,start:2752790},{audio:0,filename:"/startData/ChenLee.sca",
end:2803440,start:2778121},{audio:0,filename:"/startData/Coullet.sca",end:2828907,start:2803440},{audio:0,filename:"/startData/Dadras.sca",end:2854317,start:2828907},{audio:0,filename:"/startData/DequanLi.sca",end:2879584,start:2854317},{audio:0,filename:"/startData/dla3D.sca",end:2904950,start:2879584},{audio:0,filename:"/startData/FourWing.sca",end:2929808,start:2904950},{audio:0,filename:"/startData/FourWing2.sca",end:2955116,start:2929808},{audio:0,filename:"/startData/FourWing3.sca",end:2980409,
start:2955116},{audio:0,filename:"/startData/GenesioTesi.sca",end:3005831,start:2980409},{audio:0,filename:"/startData/Hadley.sca",end:3031269,start:3005831},{audio:0,filename:"/startData/Halvorsen.sca",end:3055334,start:3031269},{audio:0,filename:"/startData/juliaBulb4th_IIM.sca",end:3080692,start:3055334},{audio:0,filename:"/startData/juliaBulb_IIM.sca",end:3104627,start:3080692},{audio:0,filename:"/startData/KingsDream.sca",end:3129939,start:3104627},{audio:0,filename:"/startData/LiuChen.sca",
end:3155408,start:3129939},{audio:0,filename:"/startData/Lorenz.sca",end:3179884,start:3155408},{audio:0,filename:"/startData/MagneticFull.sca",end:3205027,start:3179884},{audio:0,filename:"/startData/MagneticLeft.sca",end:3230122,start:3205027},{audio:0,filename:"/startData/MagneticRight.sca",end:3256847,start:3230122},{audio:0,filename:"/startData/MagneticStraight.sca",end:3281510,start:3256847},{audio:0,filename:"/startData/Mira3D.sca",end:3306862,start:3281510},{audio:0,filename:"/startData/MultiChuaII.sca",
end:3332145,start:3306862},{audio:0,filename:"/startData/NewtonLeipnik.sca",end:3357543,start:3332145},{audio:0,filename:"/startData/NoseHoover.sca",end:3382705,start:3357543},{audio:0,filename:"/startData/Pickover.sca",end:3405735,start:3382705},{audio:0,filename:"/startData/PolynomialA.sca",end:3431132,start:3405735},{audio:0,filename:"/startData/PolynomialABS.sca",end:3455361,start:3431132},{audio:0,filename:"/startData/PolynomialB.sca",end:3479813,start:3455361},{audio:0,filename:"/startData/PolynomialC.sca",
end:3505428,start:3479813},{audio:0,filename:"/startData/PolynomialPow.sca",end:3528747,start:3505428},{audio:0,filename:"/startData/PolynomialSin.sca",end:3554793,start:3528747},{audio:0,filename:"/startData/PowerN3D.sca",end:3594561,start:3554793},{audio:0,filename:"/startData/quatJulia_IIM.sca",end:3619976,start:3594561},{audio:0,filename:"/startData/Rampe01.sca",end:3644290,start:3619976},{audio:0,filename:"/startData/Rampe01A.sca",end:3668102,start:3644290},{audio:0,filename:"/startData/Rampe02.sca",
end:3690053,start:3668102},{audio:0,filename:"/startData/Rampe03.sca",end:3713829,start:3690053},{audio:0,filename:"/startData/Rampe03A.sca",end:3737672,start:3713829},{audio:0,filename:"/startData/Rampe04.sca",end:3762275,start:3737672},{audio:0,filename:"/startData/Rampe05.sca",end:3785705,start:3762275},{audio:0,filename:"/startData/Rampe06.sca",end:3811101,start:3785705},{audio:0,filename:"/startData/Rampe07.sca",end:3833433,start:3811101},{audio:0,filename:"/startData/Rampe08.sca",end:3857249,
start:3833433},{audio:0,filename:"/startData/Rampe09.sca",end:3880640,start:3857249},{audio:0,filename:"/startData/Rampe10.sca",end:3904406,start:3880640},{audio:0,filename:"/startData/RayleighBenard.sca",end:3929828,start:3904406},{audio:0,filename:"/startData/Robinson.sca",end:3953685,start:3929828},{audio:0,filename:"/startData/Rossler.sca",end:3978840,start:3953685},{audio:0,filename:"/startData/Rucklidge.sca",end:4005163,start:3978840},{audio:0,filename:"/startData/Sakarya.sca",end:4030687,start:4005163},
{audio:0,filename:"/startData/SinCos.sca",end:4055221,start:4030687},{audio:0,filename:"/startData/SprottLinzB.sca",end:4079304,start:4055221},{audio:0,filename:"/startData/SprottLinzF.sca",end:4104676,start:4079304},{audio:0,filename:"/startData/Thomas.sca",end:4129843,start:4104676},{audio:0,filename:"/startData/TSUCS.sca",end:4155109,start:4129843},{audio:0,filename:"/startData/YuWang.sca",end:4180409,start:4155109},{audio:0,filename:"/startData/ZhouChen.sca",end:4205826,start:4180409}]});
var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,m=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;m="function"===typeof importScripts;ha=(ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!m;ja=!fa&&!ha&&!m;var n="",ka,la,ma;
if(ha){n=__dirname+"/";var na,oa;ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);a=na.readFileSync(a);return b?a:a.toString()};ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));ca=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=h);process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;});process.on("unhandledRejection",q);ea=function(a){process.exit(a)};
h.inspect=function(){return"[Emscripten Module object]"}}else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||m)m?n=self.location.href:document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=h.print||console.log.bind(console),l=h.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);
function ra(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:if("*"===a[a.length-1])return 4;if("i"===a[0]){var b=parseInt(a.substr(1));assert(0===b%8,"getNativeTypeSize invalid bits "+b+", type "+a);return b/8}return 0}}function sa(a){ta||(ta={});ta[a]||(ta[a]=1,l(a))}var ta,ua;h.wasmBinary&&(ua=h.wasmBinary);var va;h.noExitRuntime&&(va=h.noExitRuntime);"object"!==typeof WebAssembly&&l("no native wasm support detected");
function v(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":w[a>>0]=b;break;case "i8":w[a>>0]=b;break;case "i16":wa[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":z=[b>>>0,(A=b,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[a>>2]=z[0];x[a+4>>2]=z[1];break;case "float":B[a>>2]=b;break;case "double":Ba[a>>3]=b;break;default:q("invalid type for setValue: "+c)}}
var Ca,Da=new WebAssembly.Table({initial:856,maximum:856,element:"anyfunc"}),C=!1;function assert(a,b){a||q("Assertion failed: "+b)}
function Ea(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;var e="string"===typeof b?b:null;var f=Fa(Math.max(d,e?1:b.length));if(c){a=f;assert(0==(f&3));for(b=f+(d&-4);a<b;a+=4)x[a>>2]=0;for(b=f+d;a<b;)w[a++>>0]=0;return f}if("i8"===e)return a.subarray||a.slice?D.set(a,f):D.set(new Uint8Array(a),f),f;c=0;for(var k,r,p;c<d;){var u=a[c];k=e||b[c];0===k?c++:("i64"==k&&(k="i32"),v(f+c,u,k),p!==k&&(r=ra(k),p=k),c+=r)}return f}
var Ga="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ha(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ga)return Ga.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?Ha(D,a,b):""}
function Ia(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var r=a.charCodeAt(++f);k=65536+((k&1023)<<10)|r&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ka(a){var b=Ja(a)+1,c=La(b);Ia(a,w,c,b);return c}function Ma(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,w,D,wa,Na,x,Oa,B,Ba;
function Pa(a){buffer=a;h.HEAP8=w=new Int8Array(a);h.HEAP16=wa=new Int16Array(a);h.HEAP32=x=new Int32Array(a);h.HEAPU8=D=new Uint8Array(a);h.HEAPU16=Na=new Uint16Array(a);h.HEAPU32=Oa=new Uint32Array(a);h.HEAPF32=B=new Float32Array(a);h.HEAPF64=Ba=new Float64Array(a)}var Qa=h.TOTAL_MEMORY||16777216;h.wasmMemory?Ca=h.wasmMemory:Ca=new WebAssembly.Memory({initial:Qa/65536});Ca&&(buffer=Ca.buffer);Qa=buffer.byteLength;Pa(buffer);x[26084]=5347376;
function Ra(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.qc;"number"===typeof c?void 0===b.tc?h.dynCall_v(c):h.dynCall_vi(c,b.tc):c(void 0===b.tc?null:b.tc)}}}var Sa=[],Ta=[],Ua=[],Va=[],Wa=[],Xa=!1;function Ya(){var a=h.preRun.shift();Sa.unshift(a)}var xa=Math.abs,Aa=Math.ceil,za=Math.floor,ya=Math.min,Za=0,$a=null,ab=null;function bb(){Za++;h.monitorRunDependencies&&h.monitorRunDependencies(Za)}
function cb(){Za--;h.monitorRunDependencies&&h.monitorRunDependencies(Za);if(0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab)){var a=ab;ab=null;a()}}h.preloadedImages={};h.preloadedAudios={};function q(a){if(h.onAbort)h.onAbort(a);qa(a);l(a);C=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}function db(){var a=eb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var eb="wglChAoSP_lowres.wasm";
if(!db()){var fb=eb;eb=h.locateFile?h.locateFile(fb,n):n+fb}function gb(){try{if(ua)return new Uint8Array(ua);if(ma)return ma(eb);throw"both async and sync fetching of the wasm failed";}catch(a){q(a)}}function hb(){return ua||!fa&&!m||"function"!==typeof fetch?new Promise(function(a){a(gb())}):fetch(eb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+eb+"'";return a.arrayBuffer()}).catch(function(){return gb()})}
var A,z,ib=[function(a,b,c){h.oc.getBufferSubData(h.oc.ARRAY_BUFFER,a,D.subarray(c,c+b))}];Ta.push({qc:function(){jb()}});function kb(a){h.___errno_location&&(x[h.___errno_location()>>2]=a)}function lb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function mb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=lb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function nb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ob(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function pb(){var a=Array.prototype.slice.call(arguments,0);return mb(a.join("/"))}function G(a,b){return mb(a+"/"+b)}function qb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=lb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var rb=[];function sb(a,b){rb[a]={input:[],output:[],Ec:b};tb(a,ub)}
var ub={open:function(a){var b=rb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ec.flush(a.tty)},flush:function(a){a.tty.Ec.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ec.Vd)throw new H(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.Ec.Vd(a.tty)}catch(r){throw new H(29);}if(void 0===k&&0===e)throw new H(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ec.Dd)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.Ec.Dd(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},wb={Vd:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.Jc?Buffer.Jc(256):new Buffer(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=vb(b,!0)}return a.input.shift()},Dd:function(a,b){null===b||10===b?(qa(Ha(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ha(a.output,0)),a.output=[])}},zb={Dd:function(a,b){null===b||10===b?(l(Ha(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(Ha(a.output,0)),a.output=[])}},I={nc:null,kc:function(){return I.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.nc||(I.nc={dir:{node:{pc:I.dc.pc,ic:I.dc.ic,lookup:I.dc.lookup,Nc:I.dc.Nc,rename:I.dc.rename,unlink:I.dc.unlink,rmdir:I.dc.rmdir,readdir:I.dc.readdir,symlink:I.dc.symlink},stream:{rc:I.ec.rc}},file:{node:{pc:I.dc.pc,ic:I.dc.ic},stream:{rc:I.ec.rc,read:I.ec.read,write:I.ec.write,Hd:I.ec.Hd,ae:I.ec.ae,kd:I.ec.kd}},link:{node:{pc:I.dc.pc,ic:I.dc.ic,readlink:I.dc.readlink},stream:{}},Md:{node:{pc:I.dc.pc,
ic:I.dc.ic},stream:Ab}});c=Bb(a,b,c,d);J(c.mode)?(c.dc=I.nc.dir.node,c.ec=I.nc.dir.stream,c.cc={}):32768===(c.mode&61440)?(c.dc=I.nc.file.node,c.ec=I.nc.file.stream,c.fc=0,c.cc=null):40960===(c.mode&61440)?(c.dc=I.nc.link.node,c.ec=I.nc.link.stream):8192===(c.mode&61440)&&(c.dc=I.nc.Md.node,c.ec=I.nc.Md.stream);c.timestamp=Date.now();a&&(a.cc[b]=c);return c},Ih:function(a){if(a.cc&&a.cc.subarray){for(var b=[],c=0;c<a.fc;++c)b.push(a.cc[c]);return b}return a.cc},Jh:function(a){return a.cc?a.cc.subarray?
a.cc.subarray(0,a.fc):new Uint8Array(a.cc):new Uint8Array},Pd:function(a,b){var c=a.cc?a.cc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.cc,a.cc=new Uint8Array(b),0<a.fc&&a.cc.set(c.subarray(0,a.fc),0))},Se:function(a,b){if(a.fc!=b)if(0==b)a.cc=null,a.fc=0;else{if(!a.cc||a.cc.subarray){var c=a.cc;a.cc=new Uint8Array(new ArrayBuffer(b));c&&a.cc.set(c.subarray(0,Math.min(b,a.fc)))}else if(a.cc||(a.cc=[]),a.cc.length>b)a.cc.length=b;else for(;a.cc.length<b;)a.cc.push(0);
a.fc=b}},dc:{pc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.fc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.uc=4096;b.blocks=Math.ceil(b.size/b.uc);return b},ic:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&
I.Se(a,b.size)},lookup:function(){throw Cb[44];},Nc:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(J(a.mode)){try{var d=Db(b,c)}catch(f){}if(d)for(var e in d.cc)throw new H(55);}delete a.parent.cc[a.name];a.name=c;b.cc[c]=a;a.parent=b},unlink:function(a,b){delete a.cc[b]},rmdir:function(a,b){var c=Db(a,b),d;for(d in c.cc)throw new H(55);delete a.cc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.cc)a.cc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=
I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},ec:{read:function(a,b,c,d,e){var f=a.node.cc;if(e>=a.node.fc)return 0;a=Math.min(a.node.fc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){f=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.cc||a.cc.subarray)){if(f)return a.cc=b.subarray(c,c+d),a.fc=d;if(0===a.fc&&0===e)return a.cc=
new Uint8Array(b.subarray(c,c+d)),a.fc=d;if(e+d<=a.fc)return a.cc.set(b.subarray(c,c+d),e),d}I.Pd(a,e+d);if(a.cc.subarray&&b.subarray)a.cc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.cc[e+f]=b[c+f];a.fc=Math.max(a.fc,e+d);return d},rc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.fc);if(0>b)throw new H(28);return b},Hd:function(a,b,c){I.Pd(a.node,b+c);a.node.fc=Math.max(a.node.fc,b+c)},ae:function(a,b,c,d,e,f,k){if(32768!==(a.node.mode&61440))throw new H(43);
c=a.node.cc;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.fc)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==w.buffer;d=Fa(d);if(!d)throw new H(48);(e?w:b).set(c,d)}else a=!1,d=c.byteOffset;return{Ph:d,se:a}},kd:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);if(e&2)return 0;I.ec.write(a,b,0,d,c,!1);return 0}}},Eb={Zg:63,yg:44,mh:71,Vf:27,Xf:29,Vg:60,hf:1,zg:45,sf:8,Bf:12,pf:6,wh:6,Dg:48,jf:2,Of:21,Mg:105,zf:10,Nf:20,xh:75,xg:43,
Og:54,Zf:31,Wf:28,sg:41,kg:33,Tg:59,th:74,Pf:22,Ig:51,lh:70,ih:69,lg:34,ah:64,Kf:18,fh:68,Eg:49,Sf:24,Cf:106,ag:156,bg:107,cg:108,ig:109,uh:110,vg:111,$f:112,Hf:16,Ag:46,rf:113,vf:114,yh:115,tg:104,wf:103,xf:102,If:16,yf:101,Kg:100,wg:116,qh:117,Jg:118,Fg:119,Gg:120,hh:121,Bg:47,mf:122,nh:123,Df:124,bh:65,ng:36,Lf:125,uf:9,Ug:126,tf:127,gh:128,dg:129,eg:130,hg:131,gg:132,fg:133,Lg:52,Pg:55,og:37,jg:32,Wg:138,$g:139,Gf:15,ug:42,nf:5,eh:67,Rg:57,Hg:50,jh:140,Ff:14,kf:3,Ef:13,rg:40,pg:38,rh:73,Qf:142,
Rf:23,Uf:26,qf:7,Jf:17,mg:35,dh:66,kh:137,lf:4,qg:39,Yf:30,Ng:53,sh:141,vh:136,Mf:19,oh:72,Sg:138,Cg:148,Tf:25,Xg:61,Af:11,Qg:56,Yg:62,ph:135},K={cd:!1,Ze:function(){K.cd=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);K.Qd={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Id:function(a){return Buffer.alloc?Buffer.from(a):new Buffer(a)},hc:function(a){a=a.code;assert(a in Eb);return Eb[a]},kc:function(a){assert(ia);
return K.createNode(null,"/",K.Ud(a.Cd.root),0)},createNode:function(a,b,c){if(!J(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new H(28);a=Bb(a,b,c);a.dc=K.dc;a.ec=K.ec;return a},Ud:function(a){try{var b=fs.lstatSync(a);K.cd&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new H(K.hc(c));}return b.mode},lc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.kc.Cd.root);b.reverse();return pb.apply(null,b)},Ee:function(a){a&=-2656257;var b=0,c;for(c in K.Qd)a&
c&&(b|=K.Qd[c],a^=c);if(a)throw new H(28);return b},dc:{pc:function(a){a=K.lc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new H(K.hc(c));}K.cd&&!b.uc&&(b.uc=4096);K.cd&&!b.blocks&&(b.blocks=(b.size+b.uc-1)/b.uc|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,uc:b.uc,blocks:b.blocks}},ic:function(a,b){var c=K.lc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&
fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new H(K.hc(d));}},lookup:function(a,b){var c=G(K.lc(a),b);c=K.Ud(c);return K.createNode(a,b,c)},Nc:function(a,b,c,d){a=K.createNode(a,b,c,d);b=K.lc(a);try{J(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new H(K.hc(e));}return a},rename:function(a,b,c){a=K.lc(a);b=G(K.lc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new H(K.hc(d));}},unlink:function(a,b){a=G(K.lc(a),
b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new H(K.hc(c));}},rmdir:function(a,b){a=G(K.lc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new H(K.hc(c));}},readdir:function(a){a=K.lc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new H(K.hc(b));}},symlink:function(a,b,c){a=G(K.lc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new H(K.hc(d));}},readlink:function(a){var b=K.lc(a);try{return b=fs.readlinkSync(b),b=Fb.relative(Fb.resolve(a.kc.Cd.root),
b)}catch(c){if(!c.code)throw c;throw new H(K.hc(c));}}},ec:{open:function(a){var b=K.lc(a.node);try{32768===(a.node.mode&61440)&&(a.Pc=fs.openSync(b,K.Ee(a.flags)))}catch(c){if(!c.code)throw c;throw new H(K.hc(c));}},close:function(a){try{32768===(a.node.mode&61440)&&a.Pc&&fs.closeSync(a.Pc)}catch(b){if(!b.code)throw b;throw new H(K.hc(b));}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Pc,K.Id(b.buffer),c,d,e)}catch(f){throw new H(K.hc(f));}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Pc,
K.Id(b.buffer),c,d,e)}catch(f){throw new H(K.hc(f));}},rc:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Pc).size}catch(d){throw new H(K.hc(d));}if(0>b)throw new H(28);return b}}},Gb=null,Hb={},Ib=[],Jb=1,Kb=null,Lb=!0,Mb={},H=null,Cb={};
function M(a,b){a=qb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Rd:!0,Ed:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ed)throw new H(32);a=lb(a.split("/").filter(function(a){return!!a}),!1);var e=Gb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Db(e,a[d]);c=G(c,a[d]);e.Oc&&(!f||f&&b.Rd)&&(e=e.Oc.root);if(!f||b.$c)for(f=0;40960===(e.mode&61440);)if(e=Nb(c),c=qb(nb(c),e),e=M(c,{Ed:b.Ed}).node,40<f++)throw new H(32);}return{path:c,node:e}}
function Ob(a){for(var b;;){if(a===a.parent)return a=a.kc.be,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Pb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Kb.length}function Qb(a){var b=Pb(a.parent.id,a.name);a.Cc=Kb[b];Kb[b]=a}function Db(a,b){var c;if(c=(c=Rb(a,"x"))?c:a.dc.lookup?0:2)throw new H(c,a);for(c=Kb[Pb(a.id,b)];c;c=c.Cc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.dc.lookup(a,b)}
function Bb(a,b,c,d){Sb||(Sb=function(a,b,c,d){a||(a=this);this.parent=a;this.kc=a.kc;this.Oc=null;this.id=Jb++;this.name=b;this.mode=c;this.dc={};this.ec={};this.rdev=d},Sb.prototype={},Object.defineProperties(Sb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Oe:{get:function(){return J(this.mode)}},Ne:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Sb(a,b,c,d);Qb(a);return a}function J(a){return 16384===(a&61440)}var Tb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ub(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Rb(a,b){if(Lb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Vb(a,b){try{return Db(a,b),20}catch(c){}return Rb(a,"wx")}function Wb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Ib[a])return a;throw new H(33);}function Xb(a,b){Yb||(Yb=function(){},Yb.prototype={},Object.defineProperties(Yb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Yb,d;for(d in a)c[d]=a[d];a=c;b=Wb(b);a.fd=b;return Ib[b]=a}var Ab={open:function(a){a.ec=Hb[a.node.rdev].ec;a.ec.open&&a.ec.open(a)},rc:function(){throw new H(70);}};
function tb(a,b){Hb[a]={ec:b}}function Zb(a,b){var c="/"===b,d=!b;if(c&&Gb)throw new H(10);if(!c&&!d){var e=M(b,{Rd:!1});b=e.path;e=e.node;if(e.Oc)throw new H(10);if(!J(e.mode))throw new H(54);}b={type:a,Cd:{},be:b,Qe:[]};a=a.kc(b);a.kc=b;b.root=a;c?Gb=a:e&&(e.Oc=b,e.kc&&e.kc.Qe.push(b))}function $b(a,b,c){var d=M(a,{parent:!0}).node;a=ob(a);if(!a||"."===a||".."===a)throw new H(28);var e=Vb(d,a);if(e)throw new H(e);if(!d.dc.Nc)throw new H(63);return d.dc.Nc(d,a,b,c)}
function N(a,b){return $b(a,(void 0!==b?b:511)&1023|16384,0)}function ac(a,b,c){"undefined"===typeof c&&(c=b,b=438);return $b(a,b|8192,c)}function bc(a,b){if(!qb(a))throw new H(44);var c=M(b,{parent:!0}).node;if(!c)throw new H(44);b=ob(b);var d=Vb(c,b);if(d)throw new H(d);if(!c.dc.symlink)throw new H(63);return c.dc.symlink(c,b,a)}
function cc(a){var b=M(a,{parent:!0}).node,c=ob(a),d=Db(b,c);a:{try{var e=Db(b,c)}catch(k){e=k.mc;break a}var f=Rb(b,"wx");e=f?f:J(e.mode)?31:0}if(e)throw new H(e);if(!b.dc.unlink)throw new H(63);if(d.Oc)throw new H(10);try{Mb.willDeletePath&&Mb.willDeletePath(a)}catch(k){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.dc.unlink(b,c);b=Pb(d.parent.id,d.name);if(Kb[b]===d)Kb[b]=d.Cc;else for(b=Kb[b];b;){if(b.Cc===d){b.Cc=d.Cc;break}b=b.Cc}try{if(Mb.onDeletePath)Mb.onDeletePath(a)}catch(k){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Nb(a){a=M(a).node;if(!a)throw new H(44);if(!a.dc.readlink)throw new H(28);return qb(Ob(a.parent),a.dc.readlink(a))}function dc(a,b){var c;"string"===typeof a?c=M(a,{$c:!0}).node:c=a;if(!c.dc.ic)throw new H(63);c.dc.ic(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function fc(a,b,c,d){if(""===a)throw new H(44);if("string"===typeof b){var e=Tb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=mb(a);try{f=M(a,{$c:!(b&131072)}).node}catch(r){}}e=!1;if(b&64)if(f){if(b&128)throw new H(20);}else f=$b(a,c,0),e=!0;if(!f)throw new H(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!J(f.mode))throw new H(54);if(!e&&(c=f?40960===(f.mode&61440)?32:J(f.mode)&&
("r"!==Ub(b)||b&512)?31:Rb(f,Ub(b)):44))throw new H(c);if(b&512){c=f;var k;"string"===typeof c?k=M(c,{$c:!0}).node:k=c;if(!k.dc.ic)throw new H(63);if(J(k.mode))throw new H(31);if(32768!==(k.mode&61440))throw new H(28);if(c=Rb(k,"w"))throw new H(c);k.dc.ic(k,{size:0,timestamp:Date.now()})}b&=-641;d=Xb({node:f,path:Ob(f),flags:b,seekable:!0,position:0,ec:f.ec,ef:[],error:!1},d);d.ec.open&&d.ec.open(d);!h.logReadFiles||b&1||(hc||(hc={}),a in hc||(hc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Mb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Mb.onOpenFile(a,f))}catch(r){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+r.message)}return d}function ic(a){if(null===a.fd)throw new H(8);a.vc&&(a.vc=null);try{a.ec.close&&a.ec.close(a)}catch(b){throw b;}finally{Ib[a.fd]=null}a.fd=null}
function jc(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.ec.rc)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.ec.rc(a,b,c);a.ef=[];return a.position}
function kc(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(J(a.node.mode))throw new H(31);if(!a.ec.write)throw new H(28);a.flags&1024&&jc(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new H(70);b=a.ec.write(a,b,c,d,e,f);k||(a.position+=b);try{if(a.path&&Mb.onWriteToFile)Mb.onWriteToFile(a.path)}catch(r){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+r.message)}return b}
function lc(){H||(H=function(a,b){this.node=b;this.We=function(a){this.mc=a};this.We(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(function(a){Cb[a]=new H(a);Cb[a].stack="<generic error, no stack>"}))}var mc;function nc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function oc(a,b,c,d){a=G("string"===typeof a?a:Ob(a),b);return N(a,nc(c,d))}
function pc(a,b){a="string"===typeof a?a:Ob(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a,c);try{N(d)}catch(e){}a=d}}return d}function qc(a,b,c,d){a=G("string"===typeof a?a:Ob(a),b);c=nc(c,d);return $b(a,(void 0!==c?c:438)&4095|32768,0)}
function rc(a,b,c,d,e,f){a=b?G("string"===typeof a?a:Ob(a),b):a;d=nc(d,e);e=$b(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}dc(e,d|146);a=fc(e,"w");kc(a,c,0,c.length,0,f);ic(a);dc(e,d)}return e}
function O(a,b,c,d){a=G("string"===typeof a?a:Ob(a),b);b=nc(!!c,!!d);O.Zd||(O.Zd=64);var e=O.Zd++<<8|0;tb(e,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,e){for(var f=0,k=0;k<e;k++){try{var p=c()}catch(E){throw new H(29);}if(void 0===p&&0===f)throw new H(6);if(null===p||void 0===p)break;f++;b[d+k]=p}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){for(var f=0;f<e;f++)try{d(b[c+f])}catch(t){throw new H(29);}e&&(a.node.timestamp=
Date.now());return f}});return ac(a,b,e)}function sc(a,b,c){a=G("string"===typeof a?a:Ob(a),b);return bc(c,a)}
function tc(a){if(a.Ne||a.Oe||a.link||a.cc)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.cc=vb(ka(a.url),!0),a.fc=a.cc.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||kb(29);return b}
function uc(a,b,c,d,e){function f(){this.Ad=!1;this.Wc=[]}f.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Wd(a/this.chunkSize|0)[b]}};f.prototype.Ve=function(a){this.Wd=a};f.prototype.Jd=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,e=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var f=1048576;e||(f=b);var k=this;k.Ve(function(a){var d=a*f,e=(a+1)*f-1;e=Math.min(e,b-1);if("undefined"===typeof k.Wc[a]){var y=k.Wc;if(d>e)throw Error("invalid range ("+d+", "+e+") or no bytes requested!");if(e>b-1)throw Error("only "+b+" bytes available! programmer error!");var p=new XMLHttpRequest;p.open("GET",c,!1);b!==f&&p.setRequestHeader("Range","bytes="+d+"-"+e);"undefined"!=typeof Uint8Array&&(p.responseType="arraybuffer");
p.overrideMimeType&&p.overrideMimeType("text/plain; charset=x-user-defined");p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);d=void 0!==p.response?new Uint8Array(p.response||[]):vb(p.responseText||"",!0);y[a]=d}if("undefined"===typeof k.Wc[a])throw Error("doXHR failed!");return k.Wc[a]});if(a||!b)f=b=1,f=b=this.Wd(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.re=b;this.qe=
f;this.Ad=!0};if("undefined"!==typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.Ad||this.Jd();return this.re}},chunkSize:{get:function(){this.Ad||this.Jd();return this.qe}}});var r=void 0}else r=c,k=void 0;var p=qc(a,b,d,e);k?p.cc=k:r&&(p.cc=null,p.url=r);Object.defineProperties(p,{fc:{get:function(){return this.cc.length}}});var u=
{};Object.keys(p.ec).forEach(function(a){var b=p.ec[a];u[a]=function(){if(!tc(p))throw new H(29);return b.apply(null,arguments)}});u.read=function(a,b,c,d,e){if(!tc(p))throw new H(29);a=a.node.cc;if(e>=a.length)return 0;d=Math.min(a.length-e,d);if(a.slice)for(var f=0;f<d;f++)b[c+f]=a[e+f];else for(f=0;f<d;f++)b[c+f]=a.get(e+f);return d};p.ec=u;return p}
function vc(a,b,c,d,e,f,k,r,p,u){function t(c){function y(c){u&&u();r||rc(a,b,c,d,e,p);f&&f();cb(E)}var t=!1;h.preloadPlugins.forEach(function(a){!t&&a.canHandle(L)&&(a.handle(c,L,y,function(){k&&k();cb(E)}),t=!0)});t||y(c)}g.Xd();var L=b?qb(G(a,b)):a,E="cp "+L;bb(E);"string"==typeof c?g.ue(c,function(a){t(a)},k):t(c)}var P={},Sb,Yb,hc,wc={},xc=0;function Q(){xc+=4;return x[xc-4>>2]}function yc(a){void 0===a&&(a=Q());a=Ib[a];if(!a)throw new H(8);return a}function zc(){q()}
g={bc:{sc:null,method:"",yc:0,qc:null,tc:0,pd:0,qd:0,xc:0,fe:[],pause:function(){g.bc.sc=null;g.bc.yc++},resume:function(){g.bc.yc++;var a=g.bc.pd,b=g.bc.qd,c=g.bc.qc;g.bc.qc=null;Ac(c,0,!1,g.bc.tc,!0);Bc(a,b);g.bc.sc()},ff:function(){if(h.setStatus){var a=h.statusMessage||"Please wait...",b=g.bc.Fd,c=g.bc.Fh;b?b<c?h.setStatus(a+" ("+(c-b)+"/"+c+")"):h.setStatus(a):h.setStatus("")}},Te:function(a){if(!(C||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(b){if(b instanceof pa)return;b&&"object"===
typeof b&&b.stack&&l("exception thrown: "+[b,b.stack]);throw b;}h.postMainLoop&&h.postMainLoop()}}},Kc:!1,Qc:!1,Pe:[],workers:[],Xd:function(){function a(){g.Qc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!g.Le){g.Le=!0;try{g.ad=!0}catch(c){g.ad=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}g.BlobBuilder=
"undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:g.ad?null:console.log("warning: no BlobBuilder");g.Uc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.de||"undefined"!==typeof g.Uc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.de=!0);h.preloadPlugins.push({canHandle:function(a){return!h.de&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,
b,e,f){var c=null;if(g.ad)try{c=new Blob([a],{type:g.zd(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:g.zd(b)}))}catch(u){sa("Blob constructor present but fails: "+u+"; falling back to blob builder")}c||(c=new g.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=g.Uc.createObjectURL(c),p=new Image;p.onload=function(){assert(p.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=p.width;c.height=p.height;c.getContext("2d").drawImage(p,
0,0);h.preloadedImages[b]=c;g.Uc.revokeObjectURL(d);e&&e(a)};p.onerror=function(){console.log("Image "+d+" could not be decoded");f&&f()};p.src=d}});h.preloadPlugins.push({canHandle:function(a){return!h.Nh&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,f){function c(c){p||(p=!0,h.preloadedAudios[b]=c,e&&e(a))}function d(){p||(p=!0,h.preloadedAudios[b]=new Audio,f&&f())}var p=!1;if(g.ad){try{var u=new Blob([a],{type:g.zd(b)})}catch(L){return d()}u=g.Uc.createObjectURL(u);var t=
new Audio;t.addEventListener("canplaythrough",function(){c(t)},!1);t.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,f=0,k=0;k<a.length;k++)for(e=e<<8|a[k],f+=8;6<=f;){var r=e>>f-6&63;f-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==f?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==f&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&
15)<<2],d+="=");t.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(t)}};t.src=u;g.Ue(function(){c(t)},1E4)}else return d()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",
a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",function(a){!g.Qc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&h.oc&&a==h.canvas)return h.oc;var e;if(b){var f={antialias:!1,alpha:!1,$d:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)f[k]=
d[k];if("undefined"!==typeof Cc&&(e=Dc(a,f)))var r=Ec[e].wc}else r=a.getContext("2d");if(!r)return null;c&&(b||assert("undefined"===typeof R,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.oc=r,b&&(S=Ec[e],h.oc=R=S&&S.wc),h.Yh=b,g.Pe.forEach(function(a){a()}),g.Xd());return r},Dh:function(){},Td:!1,ed:void 0,Fc:void 0,requestFullscreen:function(a,b,c){function d(){g.Kc=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||
document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=g.exitFullscreen,g.ed&&e.requestPointerLock(),g.Kc=!0,g.Fc?g.Xe():g.Tc(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),g.Fc?g.Ye():g.Tc(e));if(h.onFullScreen)h.onFullScreen(g.Kc);if(h.onFullscreen)h.onFullscreen(g.Kc)}g.ed=a;g.Fc=b;g.oe=c;"undefined"===typeof g.ed&&(g.ed=!0);"undefined"===typeof g.Fc&&(g.Fc=!1);"undefined"===typeof g.oe&&(g.oe=null);var e=h.canvas;g.Td||(g.Td=!0,document.addEventListener("fullscreenchange",
d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:
null);c?f.requestFullscreen({Zh:c}):f.requestFullscreen()},ge:function(a,b,c){l("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");g.ge=function(a,b,c){return g.requestFullscreen(a,b,c)};return g.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!g.Kc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},Dc:0,Ce:function(a){var b=
Date.now();if(0===g.Dc)g.Dc=b+1E3/60;else for(;b+2>=g.Dc;)g.Dc+=1E3/60;setTimeout(a,Math.max(g.Dc-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=g.Ce;b(a)}},Sh:function(a){return function(){if(!C)return a.apply(null,arguments)}},Ic:!0,Rc:[],Oh:function(){g.Ic=!1},Rh:function(){g.Ic=!0;if(0<g.Rc.length){var a=g.Rc;g.Rc=[];a.forEach(function(a){a()})}},Th:function(a){return g.requestAnimationFrame(function(){C||(g.Ic?a():g.Rc.push(a))})},
Ue:function(a,b){va=!0;return setTimeout(function(){C||(g.Ic?a():g.Rc.push(a))},b)},Uh:function(a,b){va=!0;return setInterval(function(){C||g.Ic&&a()},b)},zd:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Ge:function(a){return a.movementX||
a.mozMovementX||a.webkitMovementX||0},He:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},Fe:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},Ac:0,Bc:0,hd:0,jd:0,touches:{},Yd:{},
Kd:function(a){if(g.Qc)"mousemove"!=a.type&&"mozMovementX"in a?g.hd=g.jd=0:(g.hd=g.Ge(a),g.jd=g.He(a)),g.Ac+=g.hd,g.Bc+=g.jd;else{var b=h.canvas.getBoundingClientRect(),c=h.canvas.width,d=h.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var k=a.Xh;if(void 0!==k)if(e=k.pageX-(e+b.left),f=k.pageY-(f+b.top),e*=c/b.width,f*=
d/b.height,b={x:e,y:f},"touchstart"===a.type)g.Yd[k.identifier]=b,g.touches[k.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=g.touches[k.identifier])||(a=b),g.Yd[k.identifier]=a,g.touches[k.identifier]=b}else k=a.pageX-(e+b.left),a=a.pageY-(f+b.top),k*=c/b.width,a*=d/b.height,g.hd=k-g.Ac,g.jd=a-g.Bc,g.Ac=k,g.Bc=a}},ue:function(a,b,c,d){var e=d?"":"al "+a;la(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));e&&cb(e)},function(){if(c)c();
else throw'Loading data file "'+a+'" failed.';});e&&bb(e)},he:[],Gd:function(){var a=h.canvas;g.he.forEach(function(b){b(a.width,a.height)})},nd:function(a,b,c){g.Tc(h.canvas,a,b);c||g.Gd()},bi:0,ai:0,Xe:function(){g.Tc(h.canvas);g.Gd()},Ye:function(){g.Tc(h.canvas);g.Gd()},Tc:function(a,b,c){b&&c?(a.gf=b,a.Je=c):(b=a.gf,c=a.Je);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||
document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}g.Fc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||
e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},$h:{},ce:0,Kh:function(){var a=g.ce;g.ce++;return a}};
function Bc(a,b){g.bc.pd=a;g.bc.qd=b;if(g.bc.qc)if(0==a)g.bc.sc=function(){var a=Math.max(0,g.bc.$e+b-zc())|0;setTimeout(g.bc.ld,a)},g.bc.method="timeout";else if(1==a)g.bc.sc=function(){g.requestAnimationFrame(g.bc.ld)},g.bc.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);m?(void 0===h.setImmediates&&(h.setImmediates=
[]),h.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}g.bc.sc=function(){setImmediate(g.bc.ld)};g.bc.method="immediate"}}
function Ac(a,b,c,d,e){va=!0;assert(!g.bc.qc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");g.bc.qc=a;g.bc.tc=d;var f="undefined"!==typeof d?function(){h.dynCall_vi(a,d)}:function(){h.dynCall_v(a)};var k=g.bc.yc;g.bc.ld=function(){if(!C)if(0<g.bc.fe.length){var a=Date.now(),b=g.bc.fe.shift();b.qc(b.tc);if(g.bc.Fd){var c=g.bc.Fd,d=0==c%1?c-1:Math.floor(c);
g.bc.Fd=b.Bh?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");g.bc.ff();k<g.bc.yc||setTimeout(g.bc.ld,0)}else k<g.bc.yc||(g.bc.xc=g.bc.xc+1|0,1==g.bc.pd&&1<g.bc.qd&&0!=g.bc.xc%g.bc.qd?g.bc.sc():(0==g.bc.pd&&(g.bc.$e=zc()),"undefined"!==typeof Cc&&S&&!Cc.Ch&&!S.attributes.Gh&&S.wc.ze&&S.wc.ze(),"timeout"===g.bc.method&&h.oc&&(l("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
g.bc.method=""),g.bc.Te(f),k<g.bc.yc||g.bc.sc()))};e||(b&&0<b?Bc(0,1E3/b):Bc(1,1),g.bc.sc());if(c)throw"SimulateInfiniteLoop";}var Fc=0,Gc=!1;function Hc(){for(var a=Ic.length-1;0<=a;--a)Jc(a);Ic=[];Kc=[]}var Kc=[];function Lc(){if(Mc&&Nc.te)for(var a=0;a<Kc.length;++a){var b=Kc[a];Kc.splice(a,1);--a;b.Vh.apply(this,b.Ah)}}var Mc=0,Nc=null,Ic=[];function Jc(a){var b=Ic[a];b.target.removeEventListener(b.Zc,b.Be,b.ne);Ic.splice(a,1)}
function Oc(a){function b(b){++Mc;Nc=a;Lc();a.Ie(b);Lc();--Mc}if(a.ye)a.Be=b,a.target.addEventListener(a.Zc,b,a.ne),Ic.push(a),Gc||(Va.push(Hc),Gc=!0);else for(var c=0;c<Ic.length;++c)Ic[c].target==a.target&&Ic[c].Zc==a.Zc&&Jc(c--)}function Pc(a){return a===a+0?F(a):a}var Qc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function Rc(a,b,c,d,e,f){Fc||(Fc=Fa(1684));a=Qc[a]||("undefined"!==typeof document?document.querySelector(Pc(a)):void 0);Oc({target:a,te:"touchstart"==f||"touchend"==f,Zc:f,ye:d,Ie:function(c){c=c||event;for(var f={},k=0;k<c.touches.length;++k){var u=c.touches[k];u.Ld=!1;f[u.identifier]=u}for(k=0;k<c.changedTouches.length;++k)u=c.changedTouches[k],f[u.identifier]=u,u.Ld=!0;for(k=0;k<c.targetTouches.length;++k)u=c.targetTouches[k],f[u.identifier].Re=!0;var t=u=Fc;x[t+4>>2]=c.ctrlKey;x[t+8>>2]=c.shiftKey;
x[t+12>>2]=c.altKey;x[t+16>>2]=c.metaKey;t+=20;var L=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},E=0;for(k in f){var y=f[k];x[t>>2]=y.identifier;x[t+4>>2]=y.screenX;x[t+8>>2]=y.screenY;x[t+12>>2]=y.clientX;x[t+16>>2]=y.clientY;x[t+20>>2]=y.pageX;x[t+24>>2]=y.pageY;x[t+28>>2]=y.Ld;x[t+32>>2]=y.Re;x[t+36>>2]=y.clientX-L.left;x[t+40>>2]=y.clientY-L.top;t+=52;if(32<=++E)break}x[u>>2]=E;Sc(d,e,u,b)&&c.preventDefault()},ne:c})}var Tc={};
function Uc(){if(!Vc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da},b;for(b in Tc)a[b]=Tc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Vc=c}return Vc}var Vc,Wc=1,Xc=0,Yc=[],T=[],Zc=[],$c=[],ad=[],bd=[],U=[],cd=[],Ec={},S=null,dd=[],ed={},fd={},gd=4;function V(a){Xc||(Xc=a)}function hd(a){for(var b=Wc++,c=a.length;c<b;c++)a[c]=null;return b}
var id=null,jd=[0];function Dc(a,b){return(a=1<b.$d?a.getContext("webgl2",b):a.getContext("webgl",b)||a.getContext("experimental-webgl",b))?kd(a,b):0}function kd(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=Fa(8),e={handle:d,attributes:b,version:b.$d,wc:a};e.od=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.zh=e);Ec[d]=e;("undefined"===typeof b.Ae||b.Ae)&&ld(e);return d}
function md(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,f){b.drawArraysInstancedANGLE(a,d,e,f)},a.drawElementsInstanced=function(a,d,e,f,k){b.drawElementsInstancedANGLE(a,d,e,f,k)})}
function nd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function od(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function ld(a){a||(a=S);if(!a.Ke){a.Ke=!0;var b=a.wc;2>a.version&&(md(b),nd(b),od(b));b.Eh=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var Cc={},pd,qd,rd=[];function sd(a,b,c,d){for(var e=0;e<a;e++){var f=R[c](),k=f&&hd(d);f?(f.name=k,d[k]=f):V(1282);x[b+4*e>>2]=k}}
function td(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=R.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>S.version){V(1282);return}c=2*(R.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){V(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=R.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:V(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)x[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V(1280);l("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:V(1280);l("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}x[b>>2]=c}else V(1281)}
function ud(a){var b=Ja(a)+1,c=Fa(b);Ia(a,D,c,b);return c}var vd={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},wd={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function xd(a,b,c,d,e){if(b=vd[b]*wd[a]){var f=gd;c=e+d*(c*b+f-1&-f);switch(a){case 5120:return w.subarray(e,c);case 5121:return D.subarray(e,c);case 5122:return wa.subarray(e>>1,c>>1);case 5124:return x.subarray(e>>2,c>>2);case 5126:return B.subarray(e>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:return Oa.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Na.subarray(e>>1,c>>1);default:V(1280)}}else V(1280)}
function yd(a){switch(a){case 5120:return w;case 5121:return D;case 5122:return wa;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Na;case 5124:return x;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return Oa;case 5126:return B}}var zd={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1};
function Ad(a,b,c,d,e){this.id=a;this.y=this.x=0;this.yd=!1;this.le=this.ke=0;this.width=b;this.height=c;this.je=b;this.ie=c;this.title=d;this.share=e;this.attributes=Bd;this.bd={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.wd=[];this.Vc=this.dd=this.Od=this.md=this.Xc=this.Yc=this.gd=this.Sd=this.ud=this.Hc=this.pe=this.title=null}function W(a){return 0>=a||!X?null:X[a-1]}
var Cd=null,Dd=null,Y=null,X=null,Ed=null,Fd=null,Bd=null,Gd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Hd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Id(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Jd(a){Y&&Y.Vc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||Kd(Y.Vc,Y.id,a))}function Ld(a,b){if(Y){var c=Hd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.wd[a]=b;Y.dd&&(d&&(b=2),Md(Y.dd,Y.id,c,a,b,Id()))}}}
function Nd(){Od()}function Pd(){Od()}function Qd(a){Ld(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Rd(a){Ld(a.keyCode,0)}function Sd(){if(Y)for(var a=0;a<Y.wd.length;++a)Y.wd[a]&&Ld(a,0)}function Td(a){Y&&(g.Kd(a),a.target==h.canvas&&Y.Yc&&Ud(Y.Yc,Y.id,g.Ac,g.Bc))}function Vd(a){Y&&a.target==h.canvas&&Y.Xc&&Kd(Y.Xc,Y.id,1)}function Wd(a){Y&&a.target==h.canvas&&Y.Xc&&Kd(Y.Xc,Y.id,0)}
function Xd(a,b){if(Y&&(g.Kd(a),a.target==h.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.gd&&Yd(Y.gd,Y.id,c,b,Id())}}function Zd(a){Y&&Xd(a,1)}function $d(a){Y&&Xd(a,0)}function ae(a){g.Fe(a);if(Y&&Y.md&&a.target==h.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;Ud(Y.md,Y.id,b,c);a.preventDefault()}}
function be(){(h.canvas.requestFullscreen||h.canvas.mozRequestFullScreen||h.canvas.webkitRequestFullScreen||function(){}).apply(h.canvas,[])}var Z={},ce=null,de=null;
function Od(){if(g.bc.xc!==de||!g.bc.xc){ce=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;de=g.bc.xc;for(var a=0;a<ce.length;++a){var b=ce[a];if(b){Z[a]||(console.log("glfw joystick connected:",a),Z[a]={id:Ea(vb(b.id),"i8"),we:b.buttons.length,ve:b.axes.length,buttons:Ea(Array(b.buttons.length),"i8"),axes:Ea(Array(4*b.axes.length),"float")});for(var c=Z[a],d=0;d<b.buttons.length;++d)v(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)v(c.axes+
4*d,b.axes[d],"float")}else Z[a]&&(console.log("glfw joystick disconnected",a),ee(Z[a].id),ee(Z[a].buttons),ee(Z[a].axes),delete Z[a])}}}function fe(a){if(Y&&Y.Od&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1}function ge(a){if(Y&&Y.Od)return a.preventDefault(),!1}function he(a){!g.Qc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),a.preventDefault())}function ie(a){return 0===a%4&&(0!==a%100||0===a%400)}
function je(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var ke=[31,29,31,30,31,30,31,31,30,31,30,31],le=[31,28,31,30,31,30,31,31,30,31,30,31];function me(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(ie(a.getFullYear())?ke:le)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function ne(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function r(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function p(a){a=me(new Date(a.jc+1900,0,1),a.td);var b=r(new Date(a.getFullYear()+1,0,4));return 0>=k(r(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var u=x[d+40>>2];d={cf:x[d>>2],bf:x[d+4>>2],rd:x[d+8>>2],Sc:x[d+12>>2],Gc:x[d+16>>2],jc:x[d+20>>2],sd:x[d+24>>2],td:x[d+28>>2],Wh:x[d+32>>2],af:x[d+36>>2],
df:u?F(u):""};c=F(c);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in u)c=c.replace(new RegExp(t,"g"),u[t]);var L="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
E="January February March April May June July August September October November December".split(" ");u={"%a":function(a){return L[a.sd].substring(0,3)},"%A":function(a){return L[a.sd]},"%b":function(a){return E[a.Gc].substring(0,3)},"%B":function(a){return E[a.Gc]},"%C":function(a){return f((a.jc+1900)/100|0,2)},"%d":function(a){return f(a.Sc,2)},"%e":function(a){return e(a.Sc,2," ")},"%g":function(a){return p(a).toString().substring(2)},"%G":function(a){return p(a)},"%H":function(a){return f(a.rd,
2)},"%I":function(a){a=a.rd;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.Sc+je(ie(a.jc+1900)?ke:le,a.Gc-1),3)},"%m":function(a){return f(a.Gc+1,2)},"%M":function(a){return f(a.bf,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.rd&&12>a.rd?"AM":"PM"},"%S":function(a){return f(a.cf,2)},"%t":function(){return"\t"},"%u":function(a){return a.sd||7},"%U":function(a){var b=new Date(a.jc+1900,0,1),c=0===b.getDay()?b:me(b,7-b.getDay());a=new Date(a.jc+1900,a.Gc,a.Sc);return 0>
k(c,a)?f(Math.ceil((31-c.getDate()+(je(ie(a.getFullYear())?ke:le,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=r(new Date(a.jc+1900,0,4)),c=r(new Date(a.jc+1901,0,4)),d=me(new Date(a.jc+1900,0,1),a.td);return 0>k(d,b)?"53":0>=k(c,d)?"01":f(Math.ceil((b.getFullYear()<a.jc+1900?a.td+32-b.getDate():a.td+1-b.getDate())/7),2)},"%w":function(a){return a.sd},"%W":function(a){var b=new Date(a.jc,0,1),c=1===b.getDay()?b:me(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.jc+
1900,a.Gc,a.Sc);return 0>k(c,a)?f(Math.ceil((31-c.getDate()+(je(ie(a.getFullYear())?ke:le,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.jc+1900).toString().substring(2)},"%Y":function(a){return a.jc+1900},"%z":function(a){a=a.af;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.df},"%%":function(){return"%"}};for(t in u)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),u[t](d)));t=vb(c,!1);if(t.length>
b)return 0;w.set(t,a);return t.length-1}lc();Kb=Array(4096);Zb(I,"/");N("/tmp");N("/home");N("/home/web_user");
(function(){N("/dev");tb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});ac("/dev/null",259);sb(1280,wb);sb(1536,zb);ac("/dev/tty",1280);ac("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){q("random_device")});O("/dev","random",b);O("/dev","urandom",b);
N("/dev/shm");N("/dev/shm/tmp")})();N("/proc");N("/proc/self");N("/proc/self/fd");Zb({kc:function(){var a=Bb("/proc/self","fd",16895,73);a.dc={lookup:function(a,c){var b=Ib[+c];if(!b)throw new H(8);a={parent:null,kc:{be:"fake"},dc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");h.FS_createFolder=oc;h.FS_createPath=pc;h.FS_createDataFile=rc;h.FS_createPreloadedFile=vc;h.FS_createLazyFile=uc;h.FS_createLink=sc;h.FS_createDevice=O;h.FS_unlink=cc;
if(ia){var fs=require("fs"),Fb=require("path");K.Ze()}ha?zc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?zc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?zc=function(){return performance.now()}:zc=Date.now;h.requestFullScreen=function(a,b,c){l("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");h.requestFullScreen=h.requestFullscreen;g.ge(a,b,c)};
h.requestFullscreen=function(a,b,c){g.requestFullscreen(a,b,c)};h.requestAnimationFrame=function(a){g.requestAnimationFrame(a)};h.setCanvasSize=function(a,b,c){g.nd(a,b,c)};h.pauseMainLoop=function(){g.bc.pause()};h.resumeMainLoop=function(){g.bc.resume()};h.getUserMedia=function(){g.getUserMedia()};h.createContext=function(a,b,c,d){return g.createContext(a,b,c,d)};var R;id=new Float32Array(256);for(var oe=0;256>oe;oe++)jd[oe]=id.subarray(0,oe+1);for(var pe=0;32>pe;pe++)rd.push(Array(pe));
function vb(a,b){var c=Array(Ja(a)+1);a=Ia(a,c,0,c.length);b&&(c.length=a);return c}
var ue={e:function(a){return Fa(a)},h:function(a){"uncaught_exception"in qe?qe.Jc++:qe.Jc=1;throw a;},ra:function(){},qb:function(){kb(63);return-1},zb:function(a,b){xc=b;try{var c=yc(),d=Q(),e=Q();if(!c.vc){var f=M(c.path,{$c:!0}).node;if(!f.dc.readdir)throw new H(54);var k=f.dc.readdir(f);c.vc=k}a=0;for(var r=jc(c,0,1),p=Math.floor(r/280);p<c.vc.length&&a+280<=e;){var u=c.vc[p];if("."===u[0]){var t=1;var L=4}else{var E=Db(c.node,u);t=E.id;L=8192===(E.mode&61440)?2:J(E.mode)?4:40960===(E.mode&61440)?
10:8}z=[t>>>0,(A=t,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[d+a>>2]=z[0];x[d+a+4>>2]=z[1];z=[280*(p+1)>>>0,(A=280*(p+1),1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[d+a+8>>2]=z[0];x[d+a+12>>2]=z[1];wa[d+a+16>>1]=280;w[d+a+18>>0]=L;Ia(u,D,d+a+19,256);a+=280;p+=1}jc(c,280*p,0);return a}catch(y){return"undefined"!==typeof P&&y instanceof H||q(y),-y.mc}},qa:function(a,b){xc=b;try{var c=yc();switch(Q()){case 0:var d=
Q();return 0>d?-28:fc(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Q(),c.flags|=d,0;case 12:return d=Q(),wa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return kb(28),-1;default:return-28}}catch(e){return"undefined"!==typeof P&&e instanceof H||q(e),-e.mc}},sa:function(a,b){xc=b;try{var c=F(Q()),d=Q(),e=Q();return fc(c,d,e).fd}catch(f){return"undefined"!==typeof P&&f instanceof H||q(f),-f.mc}},xb:function(a,b){xc=b;try{var c=yc(),d=Q();
switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var e=Q();return x[e>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=e=Q();if(!c.ec.Me)throw new H(59);return c.ec.Me(c,d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:q("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof P&&f instanceof H||q(f),-f.mc}},pb:function(a,b){xc=b;try{var c=Q(),d=Q();if(-1===
c||0===d)var e=-28;else{var f=wc[c];if(f&&d===f.Lh){var k=Ib[f.fd],r=f.flags,p=new Uint8Array(D.subarray(c,c+d));k&&k.ec.kd&&k.ec.kd(k,p,0,d,r);wc[c]=null;f.se&&ee(f.Mh)}e=0}return e}catch(u){return"undefined"!==typeof P&&u instanceof H||q(u),-u.mc}},y:function(){},H:function(){q()},ub:function(a,b){if(0===a)a=Date.now();else if(1===a&&(ha||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=zc();else return kb(28),-1;x[b>>2]=a/1E3|0;x[b+
4>>2]=a%1E3*1E6|0;return 0},kb:function(a,b,c){var d=[];a:for(var e="";;){var f=D[b++>>0];if(!f){b=e;break a}e+=String.fromCharCode(f)}for(e=0;e<b.length;e++)f=b[e],"d"==f||"f"==f?(c=c+8-1&-8,d.push(Ba[c>>3]),c+=8):"i"==f&&(c=c+4-1&-4,d.push(x[c>>2]),c+=4);return ib[a].apply(null,d)},mb:function(a,b,c){D.set(D.subarray(b,b+c),a)},nb:function(a){if(2147418112<a)return!1;for(var b=Math.max(w.length,16777216);b<a;)536870912>=b?b=Ma(2*b):b=Math.min(Ma((3*b+2147483648)/4),2147418112);a:{try{Ca.grow(b-
buffer.byteLength+65535>>16);Pa(Ca.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},Jb:Ac,Mb:function(a,b,c,d){Rc(a,b,c,d,25,"touchcancel");return 0},Ea:function(a,b,c,d){Rc(a,b,c,d,23,"touchend");return 0},Da:function(a,b,c,d){Rc(a,b,c,d,24,"touchmove");return 0},Fa:function(a,b,c,d){Rc(a,b,c,d,22,"touchstart");return 0},Ga:function(a,b){a=Ec[a];b=F(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?md(R):"OES_vertex_array_object"==b?nd(R):"WEBGL_draw_buffers"==b&&od(R);
return!!a.wc.getExtension(b)},Ha:function(){return S?S.handle:0},rb:function(a,b){var c=0;Uc().forEach(function(d,e){var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)w[e++>>0]=d.charCodeAt(f);w[e>>0]=0;c+=d.length+1});return 0},sb:function(a,b){var c=Uc();x[a>>2]=c.length;var d=0;c.forEach(function(a){d+=a.length+1});x[b>>2]=d;return 0},Ba:function(a){re(a)},I:function(a){try{var b=yc(a);ic(b);return 0}catch(c){return"undefined"!==typeof P&&c instanceof H||q(c),c.mc}},wb:function(a,b,c,d){try{a:{for(var e=
yc(a),f=a=0;f<c;f++){var k=x[b+(8*f+4)>>2],r=e,p=x[b+8*f>>2],u=k,t=void 0,L=w;if(0>u||0>t)throw new H(28);if(null===r.fd)throw new H(8);if(1===(r.flags&2097155))throw new H(8);if(J(r.node.mode))throw new H(31);if(!r.ec.read)throw new H(28);var E="undefined"!==typeof t;if(!E)t=r.position;else if(!r.seekable)throw new H(70);var y=r.ec.read(r,L,p,u,t);E||(r.position+=y);var xb=y;if(0>xb){var ec=-1;break a}a+=xb;if(xb<k)break}ec=a}x[d>>2]=ec;return 0}catch(yb){return"undefined"!==typeof P&&yb instanceof
H||q(yb),yb.mc}},lb:function(a,b,c,d,e){try{var f=yc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;jc(f,a,d);z=[f.position>>>0,(A=f.position,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[e>>2]=z[0];x[e+4>>2]=z[1];f.vc&&0===a&&0===d&&(f.vc=null);return 0}catch(k){return"undefined"!==typeof P&&k instanceof H||q(k),k.mc}},vb:function(a,b,c,d){try{a:{for(var e=yc(a),f=a=0;f<c;f++){var k=kc(e,w,x[b+8*f>>2],x[b+(8*f+
4)>>2],void 0);if(0>k){var r=-1;break a}a+=k}r=a}x[d>>2]=r;return 0}catch(p){return"undefined"!==typeof P&&p instanceof H||q(p),p.mc}},q:function(a){R.activeTexture(a)},Q:function(a,b){R.attachShader(T[a],U[b])},c:function(a,b){35051==a?R.Nd=b:35052==a&&(R.vd=b);R.bindBuffer(a,Yc[b])},va:function(a,b,c){R.bindBufferBase(a,b,Yc[c])},m:function(a,b){R.bindFramebuffer(a,Zc[b])},Eb:function(a,b){R.bindRenderbuffer(a,$c[b])},aa:function(a,b){R.bindSampler(a,dd[b])},d:function(a,b){R.bindTexture(a,ad[b])},
k:function(a){R.bindVertexArray(cd[a])},Ra:function(a){R.blendEquation(a)},Ua:function(a,b){R.blendEquationSeparate(a,b)},$:function(a,b){R.blendFunc(a,b)},Ta:function(a,b,c,d){R.blendFuncSeparate(a,b,c,d)},p:function(a,b,c,d){S.od?c?R.bufferData(a,D,d,c,b):R.bufferData(a,b,d):R.bufferData(a,c?D.subarray(c,c+b):b,d)},n:function(a,b,c,d){S.od?R.bufferSubData(a,b,D,d,c):R.bufferSubData(a,b,D.subarray(d,d+c))},ya:function(a){return R.checkFramebufferStatus(a)},Na:function(a){R.clear(a)},wa:function(a,
b,c){R.clearBufferfv(a,b,B,c>>2)},Oa:function(a,b,c,d){R.clearColor(a,b,c,d)},R:function(a){R.compileShader(U[a])},da:function(){var a=hd(T),b=R.createProgram();b.name=a;T[a]=b;return a},F:function(a){var b=hd(U);U[b]=R.createShader(a);return b},s:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Yc[d];e&&(R.deleteBuffer(e),e.name=0,Yc[d]=null,d==pd&&(pd=0),d==qd&&(qd=0),d==R.Nd&&(R.Nd=0),d==R.vd&&(R.vd=0))}},Ib:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Zc[d];e&&(R.deleteFramebuffer(e),
e.name=0,Zc[d]=null)}},ea:function(a){if(a){var b=T[a];b?(R.deleteProgram(b),b.name=0,T[a]=null,ed[a]=null):V(1281)}},Gb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=$c[d];e&&(R.deleteRenderbuffer(e),e.name=0,$c[d]=null)}},G:function(a){if(a){var b=U[a];b?(R.deleteShader(b),U[a]=null):V(1281)}},C:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=ad[d];e&&(R.deleteTexture(e),e.name=0,ad[d]=null)}},L:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];R.deleteVertexArray(cd[d]);cd[d]=
null}},xa:function(a){R.depthMask(!!a)},T:function(a,b){R.detachShader(T[a],U[b])},i:function(a){R.disable(a)},X:function(a,b,c){R.drawArrays(a,b,c)},Bb:function(a,b){for(var c=rd[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];R.drawBuffers(c)},Va:function(a,b,c,d){R.drawElements(a,b,c,d)},j:function(a){R.enable(a)},w:function(a){R.enableVertexAttribArray(a)},Cb:function(a,b,c,d){R.framebufferRenderbuffer(a,b,c,$c[d])},W:function(a,b,c,d,e){R.framebufferTexture2D(a,b,c,ad[d],e)},r:function(a,b){sd(a,b,"createBuffer",
Yc)},za:function(a,b){sd(a,b,"createFramebuffer",Zc)},Fb:function(a,b){sd(a,b,"createRenderbuffer",$c)},o:function(a,b){sd(a,b,"createTexture",ad)},N:function(a,b){sd(a,b,"createVertexArray",cd)},La:function(a){R.generateMipmap(a)},Ab:function(a,b,c,d){if(d)switch(a=T[a],c){case 35393:a=R.getActiveUniformBlockName(a,b);x[d>>2]=a.length+1;break;default:if(a=R.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)x[d>>2]=a;else for(b=0;b<a.length;b++)x[d+4*b>>2]=a[b]}else V(1281)},O:function(a,
b){return R.getAttribLocation(T[a],F(b))},a:function(a,b){td(a,b)},Y:function(a,b,c,d){a=R.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ia(a,D,d,b):0;c&&(x[c>>2]=b)},A:function(a,b,c){if(c)if(a>=Wc)V(1281);else{var d=ed[a];if(d)if(35716==b)a=R.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.Bd;else if(35722==b){if(-1==d.Lc){a=T[a];var e=R.getProgramParameter(a,35721);for(b=d.Lc=0;b<e;++b)d.Lc=Math.max(d.Lc,R.getActiveAttrib(a,
b).name.length+1)}x[c>>2]=d.Lc}else if(35381==b){if(-1==d.Mc)for(a=T[a],e=R.getProgramParameter(a,35382),b=d.Mc=0;b<e;++b)d.Mc=Math.max(d.Mc,R.getActiveUniformBlockName(a,b).length+1);x[c>>2]=d.Mc}else x[c>>2]=R.getProgramParameter(T[a],b);else V(1282)}else V(1281)},Z:function(a,b,c,d){a=R.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ia(a,D,d,b):0;c&&(x[c>>2]=b)},B:function(a,b,c){c?35716==b?(a=R.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1):35720==
b?(a=R.getShaderSource(U[a]),x[c>>2]=null===a||0==a.length?0:a.length+1):x[c>>2]=R.getShaderParameter(U[a],b):V(1281)},z:function(a){if(fd[a])return fd[a];switch(a){case 7939:var b=R.getSupportedExtensions()||[];b=b.concat(b.map(function(a){return"GL_"+a}));b=ud(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=R.getParameter(a))||V(1280);b=ud(b);break;case 7938:b=R.getParameter(R.VERSION);b=2<=S.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=ud(b);break;case 35724:b=R.getParameter(R.SHADING_LANGUAGE_VERSION);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ud(b);break;default:return V(1280),0}return fd[a]=b},ua:function(a,b){return R.getUniformBlockIndex(T[a],F(b))},P:function(a,b){b=F(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=ed[a]&&ed[a].me[b])&&0<=c&&c<a[0]?a[1]+c:-1},E:function(a){return R.isEnabled(a)},ca:function(a){R.linkProgram(T[a]);
var b=T[a];a=ed[a]={me:{},Bd:0,Lc:-1,Mc:-1};for(var c=a.me,d=R.getProgramParameter(b,35718),e=0;e<d;++e){var f=R.getActiveUniform(b,e),k=f.name;a.Bd=Math.max(a.Bd,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var r=R.getUniformLocation(b,k);if(r){var p=hd(bd);c[k]=[f.size,p];bd[p]=r;for(var u=1;u<f.size;++u)r=R.getUniformLocation(b,k+"["+u+"]"),p=hd(bd),bd[p]=r}}},Pa:function(a,b){3317==a&&(gd=b);R.pixelStorei(a,b)},Db:function(a,b,c,d){R.renderbufferStorage(a,b,c,d)},ba:function(a,
b,c,d){R.scissor(a,b,c,d)},S:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?x[d+4*f>>2]:-1;e+=F(x[c+4*f>>2],0>k?void 0:k)}R.shaderSource(U[a],e)},D:function(a,b,c,d,e,f,k,r,p){S.od?R.vd?R.texImage2D(a,b,c,d,e,f,k,r,p):0!=p?R.texImage2D(a,b,c,d,e,f,k,r,yd(r),p>>(zd[r]|0)):R.texImage2D(a,b,c,d,e,f,k,r,null):R.texImage2D(a,b,c,d,e,f,k,r,p?xd(r,k,d,e,p):null)},V:function(a,b,c){R.texParameterf(a,b,c)},f:function(a,b,c){R.texParameteri(a,b,c)},_:function(a,b){R.uniform1i(bd[a],b)},ta:function(a,b,
c){a=T[a];R.uniformBlockBinding(a,b,c)},Qa:function(a,b,c,d){if(S.od)R.uniformMatrix4fv(bd[a],!!c,B,d>>2,16*b);else{if(256>=16*b)for(var e=jd[16*b-1],f=0;f<16*b;f+=16)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2],e[f+4]=B[d+(4*f+16)>>2],e[f+5]=B[d+(4*f+20)>>2],e[f+6]=B[d+(4*f+24)>>2],e[f+7]=B[d+(4*f+28)>>2],e[f+8]=B[d+(4*f+32)>>2],e[f+9]=B[d+(4*f+36)>>2],e[f+10]=B[d+(4*f+40)>>2],e[f+11]=B[d+(4*f+44)>>2],e[f+12]=B[d+(4*f+48)>>2],e[f+13]=B[d+(4*f+52)>>2],e[f+
14]=B[d+(4*f+56)>>2],e[f+15]=B[d+(4*f+60)>>2];else e=B.subarray(d>>2,d+64*b>>2);R.uniformMatrix4fv(bd[a],!!c,e)}},K:function(a){R.useProgram(T[a])},v:function(a,b,c,d,e,f){R.vertexAttribPointer(a,b,c,!!d,e,f)},b:function(a,b,c,d){R.viewport(a,b,c,d)},l:function(){},ma:function(a,b,c,d,e){var f;for(f=0;f<X.length&&null!==X[f];f++);if(0<f)throw"glfwCreateWindow only supports one window at time currently";var k=f+1;if(0>=a||0>=b)k=0;else{d?be():g.nd(a,b);for(f=0;f<X.length&&null==X[f];f++);f==X.length&&
(h.oc=g.createContext(h.canvas,!0,!0,{antialias:1<Bd[135181],depth:0<Bd[135173],stencil:0<Bd[135174],alpha:0<Bd[135172]}));h.oc?(a=new Ad(k,a,b,c,e),k-1==X.length?X.push(a):X[k-1]=a,Y=a,k=a.id):k=0}return k},Xa:function(){throw"glfwCreateWindowSurface is not implemented.";},Wa:function(){},ia:function(a){a:{if(a=W(a)){a.ud&&se(a.ud,a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}h.oc=void 0}a=void 0}return a},Za:function(){},db:function(){},pa:function(a,
b,c){v(b,g.Ac,"double");v(c,g.Bc,"double")},Sa:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.width,e=a.height;v(b,d,"i32");v(c,e,"i32")},jb:function(a,b){if(a=W(a)){switch(b){case 208897:a.bd[b]=g.Qc?212995:212993}return a.bd[b]}},gb:function(a,b){Od();if((a=Z[a])&&a.axes)return v(b,a.ve,"i32"),a.axes;v(b,0,"i32")},fb:function(a,b){Od();if((a=Z[a])&&a.buttons)return v(b,a.we,"i32"),a.buttons;v(b,0,"i32")},t:function(a,b){return(a=W(a))?a.keys[b]:0},Nb:function(a,b,c){v(b,0,"i32");v(c,0,"i32")},Ma:function(a){v(a,
1,"i32");Ed||(Ed=Ea([1,0,0,0],"i32"));return Ed},J:function(a,b){return(a=W(a))?0<(a.buttons&1<<b):0},u:function(){return zc()/1E3-Fd},Hb:function(){return 0},ha:function(a,b){return(a=W(a))?a.attributes[b]:0},oa:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.x,e=a.y;v(b,d,"i32");v(c,e,"i32")},M:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.width,e=a.height;v(b,d,"i32");v(c,e,"i32")},Ia:function(){if(X)return 1;Fd=zc()/1E3;Bd=Gd;X=[];Y=null;window.addEventListener("gamepadconnected",Nd,!0);window.addEventListener("gamepaddisconnected",
Pd,!0);window.addEventListener("keydown",Qd,!0);window.addEventListener("keypress",Jd,!0);window.addEventListener("keyup",Rd,!0);window.addEventListener("blur",Sd,!0);h.canvas.addEventListener("mousemove",Td,!0);h.canvas.addEventListener("mousedown",Zd,!0);h.canvas.addEventListener("mouseup",$d,!0);h.canvas.addEventListener("wheel",ae,!0);h.canvas.addEventListener("mousewheel",ae,!0);h.canvas.addEventListener("mouseenter",Vd,!0);h.canvas.addEventListener("mouseleave",Wd,!0);h.canvas.addEventListener("drop",
fe,!0);h.canvas.addEventListener("dragover",ge,!0);g.he.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.ke=Y.x,Y.le=Y.y,Y.je=Y.width,Y.ie=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.yd=!0):1==Y.yd?(Y.x=Y.ke,Y.y=Y.le,Y.width=Y.je,Y.height=Y.ie,Y.yd=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(g.nd(Y.width,Y.height,!0),Y&&Y.Hc&&te(Y.Hc,Y.id,Y.width,Y.height),Y&&Y.Sd&&te(Y.Sd,Y.id,Y.width,
Y.height))}});return 1},x:function(){},Kb:function(){},fa:function(a,b){if(a=W(a)){var c=a.Vc;a.Vc=b;b=c}else b=null;return b},eb:function(){},ib:function(){},yb:function(){},Lb:function(a,b){if(a=W(a)){var c=a.Yc;a.Yc=b;b=c}else b=null;return b},Ja:function(a){var b=Cd;Cd=a;return b},hb:function(a,b,c){if(a=W(a))switch(b){case 208897:switch(c){case 212993:a.bd[b]=c;h.canvas.removeEventListener("click",he,!0);h.canvas.exitPointerLock();break;case 212994:console.log("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented.");
break;case 212995:a.bd[b]=c;h.canvas.addEventListener("click",he,!0);h.canvas.requestPointerLock();break;default:console.log("glfwSetInputMode called with unknown value parameter value: "+c+".")}break;case 208898:console.log("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented.");break;case 208899:console.log("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented.");break;default:console.log("glfwSetInputMode called with unknown mode parameter value: "+b+".")}},
ka:function(a,b){if(a=W(a)){var c=a.dd;a.dd=b;b=c}else b=null;return b},cb:function(a){var b=Dd;Dd=a;return b},Ca:function(a,b){if(a=W(a)){var c=a.gd;a.gd=b;b=c}else b=null;return b},na:function(a,b){if(a=W(a)){var c=a.md;a.md=b;b=c}else b=null;return b},bb:function(a,b){if(a=W(a)){var c=a.ud;a.ud=b;b=c}else b=null;return b},U:function(a,b,c){if(a=W(a))a.x=b,a.y=c},ab:function(a,b){a=W(a);if(!a)return null;var c=a.pe;a.pe=b;return c},_a:function(a,b,c){if(a=W(a))Y.id==a.id&&(b==screen.width&&c==screen.height?
be():(g.exitFullscreen(),g.nd(b,c),a.width=b,a.height=c)),a.Hc&&te(a.Hc,a.id,b,c)},la:function(a,b){if(a=W(a)){var c=a.Hc;a.Hc=b;b=c}else b=null;return b},Ya:function(a,b){if(a=W(a))a.title=F(b),Y.id==a.id&&(document.title=a.title)},$a:function(){},ga:function(){},ja:function(a){a=Math.abs(a);0==a?Bc(0,0):Bc(1,a)},Aa:function(){window.removeEventListener("gamepadconnected",Nd,!0);window.removeEventListener("gamepaddisconnected",Pd,!0);window.removeEventListener("keydown",Qd,!0);window.removeEventListener("keypress",
Jd,!0);window.removeEventListener("keyup",Rd,!0);window.removeEventListener("blur",Sd,!0);h.canvas.removeEventListener("mousemove",Td,!0);h.canvas.removeEventListener("mousedown",Zd,!0);h.canvas.removeEventListener("mouseup",$d,!0);h.canvas.removeEventListener("wheel",ae,!0);h.canvas.removeEventListener("mousewheel",ae,!0);h.canvas.removeEventListener("mouseenter",Vd,!0);h.canvas.removeEventListener("mouseleave",Wd,!0);h.canvas.removeEventListener("drop",fe,!0);h.canvas.removeEventListener("dragover",
ge,!0);h.canvas.width=h.canvas.height=1;Y=X=null},g:function(a,b){Bd[a]=b},memory:Ca,tb:function(){return 0},ob:function(a,b,c,d){return ne(a,b,c,d)},table:Da,Ka:function(a){var b=Date.now()/1E3|0;a&&(x[a>>2]=b);return b}},ve=function(){function a(a){h.asm=a.exports;cb("wasm-instantiate")}function b(b){a(b.instance)}function c(a){return hb().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){l("failed to asynchronously prepare wasm: "+a);q(a)})}var d={env:ue,wasi_unstable:ue};
bb("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(ua||"function"!==typeof WebAssembly.instantiateStreaming||db()||"function"!==typeof fetch)return c(b);fetch(eb,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){l("wasm streaming compile failed: "+a);l("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();
h.asm=ve;var jb=h.___wasm_call_ctors=function(){return h.asm.Ob.apply(null,arguments)},Fa=h._malloc=function(){return h.asm.Pb.apply(null,arguments)},ee=h._free=function(){return h.asm.Qb.apply(null,arguments)};h.___errno_location=function(){return h.asm.Rb.apply(null,arguments)};h._main=function(){return h.asm.Sb.apply(null,arguments)};
var qe=h.__ZSt18uncaught_exceptionv=function(){return h.asm.Tb.apply(null,arguments)},La=h.stackAlloc=function(){return h.asm.Ub.apply(null,arguments)},se=h.dynCall_vi=function(){return h.asm.Vb.apply(null,arguments)},Kd=h.dynCall_vii=function(){return h.asm.Wb.apply(null,arguments)},te=h.dynCall_viii=function(){return h.asm.Xb.apply(null,arguments)},Yd=h.dynCall_viiii=function(){return h.asm.Yb.apply(null,arguments)},Sc=h.dynCall_iiii=function(){return h.asm.Zb.apply(null,arguments)},Ud=h.dynCall_vidd=
function(){return h.asm._b.apply(null,arguments)},Md=h.dynCall_viiiii=function(){return h.asm.$b.apply(null,arguments)};h.dynCall_v=function(){return h.asm.ac.apply(null,arguments)};h.asm=ve;h.getMemory=function(a){if(Xa)var b=Fa(a);else b=x[26084],a=b+a+15&-16,a>w.length&&q(),x[26084]=a;return b};h.addRunDependency=bb;h.removeRunDependency=cb;h.FS_createFolder=oc;h.FS_createPath=pc;h.FS_createDataFile=rc;h.FS_createPreloadedFile=vc;h.FS_createLazyFile=uc;h.FS_createLink=sc;h.FS_createDevice=O;
h.FS_unlink=cc;h.calledRun=we;var we;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ab=function xe(){we||ye();we||(ab=xe)};
function ye(a){function b(){if(!we&&(we=!0,h.calledRun=!0,!C)){Xa=!0;h.noFSInit||mc||(mc=!0,lc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?O("/dev","stdin",h.stdin):bc("/dev/tty","/dev/stdin"),h.stdout?O("/dev","stdout",null,h.stdout):bc("/dev/tty","/dev/stdout"),h.stderr?O("/dev","stderr",null,h.stderr):bc("/dev/tty1","/dev/stderr"),fc("/dev/stdin","r"),fc("/dev/stdout","w"),fc("/dev/stderr","w"));Ra(Ta);Lb=!1;Ra(Ua);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(ze){var b=
a,d=h._main;b=b||[];var e=b.length+1,f=La(4*(e+1));x[f>>2]=Ka(da);for(var k=1;k<e;k++)x[(f>>2)+k]=Ka(b[k-1]);x[(f>>2)+e]=0;try{var r=d(e,f);re(r,!0)}catch(p){p instanceof pa||("SimulateInfiniteLoop"==p?va=!0:((b=p)&&"object"===typeof p&&p.stack&&(b=[p,p.stack]),l("exception thrown: "+b),ea(1,p)))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)b=h.postRun.shift(),Wa.unshift(b);Ra(Wa)}}a=a||ca;if(!(0<Za)){if(h.preRun)for("function"==typeof h.preRun&&
(h.preRun=[h.preRun]);h.preRun.length;)Ya();Ra(Sa);0<Za||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=ye;function re(a,b){if(!b||!va||0!==a){if(!va&&(C=!0,h.onExit))h.onExit(a);ea(a,new pa(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ze=!0;h.noInitialRun&&(ze=!1);va=!0;ye();
