var g;var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.wd||(h.wd=0,h.Ce=0);h.wd++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var e=b;c.total&&(e=c.total);if(c.loaded){d.Hc?h.yc[a].loaded=c.loaded:(d.Hc=!0,h.yc||(h.yc={}),h.yc[a]={loaded:c.loaded,total:e});var f=e=c=0,k;for(k in h.yc){var p=h.yc[k];c+=p.total;e+=p.loaded;f++}c=Math.ceil(c*h.wd/f);h.setStatus&&h.setStatus("Downloading data... ("+e+"/"+c+")")}else!h.yc&&h.setStatus&&h.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){h.Ce++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.we=c;c=a.files;for(var d=
0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();h.removeRunDependency("datafile_R:/emsOut/MinSizeRel/wglChAoSP.data")}h.FS_createPath("/","Shaders",!0,!0);h.FS_createPath("/","ChaoticAttractors",!0,!0);h.FS_createPath("/","colorMaps",!0,!0);h.FS_createPath("/","Fonts",!0,!0);h.FS_createPath("/","startData",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;h.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.we.subarray(this.start,
this.end))},finish:function(a){h.FS_createDataFile(this.name,null,a,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,e=0;e<d.length;++e)(new b(d[e].start,d[e].end,d[e].audio)).open("GET",d[e].filename);h.addRunDependency("datafile_R:/emsOut/MinSizeRel/wglChAoSP.data");h.de||(h.de={});h.de["R:/emsOut/MinSizeRel/wglChAoSP.data"]={Gh:!1};r?(c(r),r=null):k=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=h.locateFile?h.locateFile("wglChAoSP.data",""):"wglChAoSP.data",f=a.Ph,k=null,r=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;r||b(e,f,function(a){k?(k(a),k=null):r=a},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({remote_package_size:4182443,files:[{filename:"/Shaders/allParticles.0.frag",audio:0,end:12639,start:0},{filename:"/Shaders/allParticles.0.vert",audio:0,end:16723,start:12639},{filename:"/Shaders/allParticles.1.frag",audio:0,end:29419,start:16723},{filename:"/Shaders/allParticles.frag",
audio:0,end:42382,start:29419},{filename:"/Shaders/allParticles.vert",audio:0,end:46468,start:42382},{filename:"/Shaders/ambientOcclusionFrag.glsl",audio:0,end:54959,start:46468},{filename:"/Shaders/bilateralVersions.glsl",audio:0,end:79837,start:54959},{filename:"/Shaders/BillboardFrag.glsl",audio:0,end:80493,start:79837},{filename:"/Shaders/BillboardGeom.glsl",audio:0,end:82531,start:80493},{filename:"/Shaders/BillboardVert.glsl",audio:0,end:83730,start:82531},{filename:"/Shaders/cmTexturedFrag.glsl",
audio:0,end:85293,start:83730},{filename:"/Shaders/colorSpaces.glsl",audio:0,end:90267,start:85293},{filename:"/Shaders/fxaaFrag.glsl",audio:0,end:94088,start:90267},{filename:"/Shaders/lightModelsFrag.glsl",audio:0,end:104118,start:94088},{filename:"/Shaders/MergedRenderingFrag.glsl",audio:0,end:105036,start:104118},{filename:"/Shaders/mmFBO_all_vert.glsl",audio:0,end:105948,start:105036},{filename:"/Shaders/MotionBlurFS.glsl",audio:0,end:107046,start:105948},{filename:"/Shaders/oglAxesFrag.glsl",
audio:0,end:108746,start:107046},{filename:"/Shaders/oglAxesVert.glsl",audio:0,end:110931,start:108746},{filename:"/Shaders/ParticlesFrag.glsl",audio:0,end:116792,start:110931},{filename:"/Shaders/ParticlesVert.glsl",audio:0,end:119752,start:116792},{filename:"/Shaders/PointSpriteFragLight.glsl",audio:0,end:120482,start:119752},{filename:"/Shaders/PointSpriteVert.glsl",audio:0,end:122570,start:120482},{filename:"/Shaders/postRenderingFrag.glsl",audio:0,end:139134,start:122570},{filename:"/Shaders/postRenderingVert.glsl",
audio:0,end:141728,start:139134},{filename:"/Shaders/RadialBlur2PassFrag.glsl",audio:0,end:154560,start:141728},{filename:"/Shaders/shadowFrag.glsl",audio:0,end:155755,start:154560},{filename:"/ChaoticAttractors/Aizawa05.sca",audio:0,end:181023,start:155755},{filename:"/ChaoticAttractors/Aizawa06.sca",audio:0,end:206303,start:181023},{filename:"/ChaoticAttractors/Aizawa09.sca",audio:0,end:231583,start:206303},{filename:"/ChaoticAttractors/Aizawa10.sca",audio:0,end:256918,start:231583},{filename:"/ChaoticAttractors/Aizawa11.sca",
audio:0,end:282250,start:256918},{filename:"/ChaoticAttractors/Aizawa12.sca",audio:0,end:307615,start:282250},{filename:"/ChaoticAttractors/Aizawa13.sca",audio:0,end:332900,start:307615},{filename:"/ChaoticAttractors/aliDrago01.sca",audio:0,end:356975,start:332900},{filename:"/ChaoticAttractors/BicomplexJMod0_IIM1.sca",audio:0,end:381051,start:356975},{filename:"/ChaoticAttractors/BicomplexJMod3_IIM4.sca",audio:0,end:404722,start:381051},{filename:"/ChaoticAttractors/BicomplexJMod3_IIM6.sca",audio:0,
end:428205,start:404722},{filename:"/ChaoticAttractors/BicomplexJMod5_IIM.sca",audio:0,end:452114,start:428205},{filename:"/ChaoticAttractors/BicomplexJMod7_IIM.sca",audio:0,end:476005,start:452114},{filename:"/ChaoticAttractors/BicomplexMod_IIM02.sca",audio:0,end:500143,start:476005},{filename:"/ChaoticAttractors/biCplxExpl01a.sca",audio:0,end:525511,start:500143},{filename:"/ChaoticAttractors/biCplxExpl02.sca",audio:0,end:550871,start:525511},{filename:"/ChaoticAttractors/biTorus_09o4a.sca",audio:0,
end:576005,start:550871},{filename:"/ChaoticAttractors/biTorus_09o5.sca",audio:0,end:601135,start:576005},{filename:"/ChaoticAttractors/biTorus_09o8.sca",audio:0,end:626281,start:601135},{filename:"/ChaoticAttractors/dragon3b.sca",audio:0,end:652440,start:626281},{filename:"/ChaoticAttractors/dragon4a.sca",audio:0,end:678508,start:652440},{filename:"/ChaoticAttractors/dreamcatcher01.sca",audio:0,end:708443,start:678508},{filename:"/ChaoticAttractors/flower_0009nc.sca",audio:0,end:733515,start:708443},
{filename:"/ChaoticAttractors/flower_0009nd.sca",audio:0,end:758589,start:733515},{filename:"/ChaoticAttractors/flower_0009ng.sca",audio:0,end:784611,start:758589},{filename:"/ChaoticAttractors/Halvorsen01.sca",audio:0,end:809879,start:784611},{filename:"/ChaoticAttractors/JuliaBulbN7_01.sca",audio:0,end:834434,start:809879},{filename:"/ChaoticAttractors/juliaBulb_IIM02.sca",audio:0,end:858296,start:834434},{filename:"/ChaoticAttractors/Magnetic_stright01.sca",audio:0,end:883380,start:858296},{filename:"/ChaoticAttractors/Magnetic_stright01a.sca",
audio:0,end:908926,start:883380},{filename:"/ChaoticAttractors/Mag_0009e2b.sca",audio:0,end:934892,start:908926},{filename:"/ChaoticAttractors/Pn3D_o06_001.sca",audio:0,end:963068,start:934892},{filename:"/ChaoticAttractors/quatJulia_01.sca",audio:0,end:986701,start:963068},{filename:"/ChaoticAttractors/Rampe03a.sca",audio:0,end:1012043,start:986701},{filename:"/ChaoticAttractors/Rampe07old.sca",audio:0,end:1036059,start:1012043},{filename:"/ChaoticAttractors/t009e1.sca",audio:0,end:1062180,start:1036059},
{filename:"/ChaoticAttractors/Thomas01.sca",audio:0,end:1086065,start:1062180},{filename:"/ChaoticAttractors/torus_0009j.sca",audio:0,end:1111963,start:1086065},{filename:"/ChaoticAttractors/torus_0009k.sca",audio:0,end:1137175,start:1111963},{filename:"/ChaoticAttractors/torus_0009l.sca",audio:0,end:1162318,start:1137175},{filename:"/ChaoticAttractors/torus_0009m1.sca",audio:0,end:1187549,start:1162318},{filename:"/ChaoticAttractors/torus_0009m3.sca",audio:0,end:1212781,start:1187549},{filename:"/ChaoticAttractors/torus_0009m4.sca",
audio:0,end:1237607,start:1212781},{filename:"/ChaoticAttractors/torus_0009nb.sca",audio:0,end:1262848,start:1237607},{filename:"/colorMaps/palettes.json",audio:0,end:2248110,start:1262848},{filename:"/Fonts/Cousine-Regular.ttf",audio:0,end:2292022,start:2248110},{filename:"/Fonts/fontawesome-webfont.ttf",audio:0,end:2457570,start:2292022},{filename:"/Fonts/README.txt",audio:0,end:2457938,start:2457570},{filename:"/startData/Aizawa.sca",audio:0,end:2483209,start:2457938},{filename:"/startData/Arneodo.sca",
audio:0,end:2508451,start:2483209},{filename:"/startData/BicomplexJExplorer.sca",audio:0,end:2533752,start:2508451},{filename:"/startData/BicomplexJMod0_IIM.sca",audio:0,end:2556902,start:2533752},{filename:"/startData/BicomplexJMod1_IIM.sca",audio:0,end:2582309,start:2556902},{filename:"/startData/BicomplexJMod2_IIM.sca",audio:0,end:2606217,start:2582309},{filename:"/startData/BicomplexJMod3_IIM.sca",audio:0,end:2630081,start:2606217},{filename:"/startData/BicomplexJMod4_IIM.sca",audio:0,end:2654044,
start:2630081},{filename:"/startData/BicomplexJMod5_IIM.sca",audio:0,end:2679484,start:2654044},{filename:"/startData/BicomplexJMod6_IIM.sca",audio:0,end:2703482,start:2679484},{filename:"/startData/BicomplexJMod7_IIM.sca",audio:0,end:2728868,start:2703482},{filename:"/startData/BicomplexJ_IIM.sca",audio:0,end:2752790,start:2728868},{filename:"/startData/Bouali.sca",audio:0,end:2778121,start:2752790},{filename:"/startData/ChenLee.sca",audio:0,end:2803440,start:2778121},{filename:"/startData/Coullet.sca",
audio:0,end:2828907,start:2803440},{filename:"/startData/Dadras.sca",audio:0,end:2854317,start:2828907},{filename:"/startData/DequanLi.sca",audio:0,end:2879584,start:2854317},{filename:"/startData/dla3D.sca",audio:0,end:2904950,start:2879584},{filename:"/startData/FourWing.sca",audio:0,end:2929808,start:2904950},{filename:"/startData/FourWing2.sca",audio:0,end:2955116,start:2929808},{filename:"/startData/FourWing3.sca",audio:0,end:2980409,start:2955116},{filename:"/startData/GenesioTesi.sca",audio:0,
end:3005831,start:2980409},{filename:"/startData/Hadley.sca",audio:0,end:3031269,start:3005831},{filename:"/startData/Halvorsen.sca",audio:0,end:3055334,start:3031269},{filename:"/startData/juliaBulb4th_IIM.sca",audio:0,end:3080692,start:3055334},{filename:"/startData/juliaBulb_IIM.sca",audio:0,end:3104627,start:3080692},{filename:"/startData/KingsDream.sca",audio:0,end:3129939,start:3104627},{filename:"/startData/LiuChen.sca",audio:0,end:3155408,start:3129939},{filename:"/startData/Lorenz.sca",audio:0,
end:3179884,start:3155408},{filename:"/startData/MagneticFull.sca",audio:0,end:3205027,start:3179884},{filename:"/startData/MagneticLeft.sca",audio:0,end:3230122,start:3205027},{filename:"/startData/MagneticRight.sca",audio:0,end:3256847,start:3230122},{filename:"/startData/MagneticStraight.sca",audio:0,end:3281510,start:3256847},{filename:"/startData/Mira3D.sca",audio:0,end:3306862,start:3281510},{filename:"/startData/MultiChuaII.sca",audio:0,end:3332145,start:3306862},{filename:"/startData/NewtonLeipnik.sca",
audio:0,end:3357543,start:3332145},{filename:"/startData/NoseHoover.sca",audio:0,end:3382705,start:3357543},{filename:"/startData/Pickover.sca",audio:0,end:3405735,start:3382705},{filename:"/startData/PolynomialA.sca",audio:0,end:3431132,start:3405735},{filename:"/startData/PolynomialABS.sca",audio:0,end:3455361,start:3431132},{filename:"/startData/PolynomialB.sca",audio:0,end:3479813,start:3455361},{filename:"/startData/PolynomialC.sca",audio:0,end:3505428,start:3479813},{filename:"/startData/PolynomialPow.sca",
audio:0,end:3528747,start:3505428},{filename:"/startData/PolynomialSin.sca",audio:0,end:3554793,start:3528747},{filename:"/startData/PowerN3D.sca",audio:0,end:3594561,start:3554793},{filename:"/startData/quatJulia_IIM.sca",audio:0,end:3619976,start:3594561},{filename:"/startData/Rampe01.sca",audio:0,end:3644290,start:3619976},{filename:"/startData/Rampe01A.sca",audio:0,end:3668102,start:3644290},{filename:"/startData/Rampe02.sca",audio:0,end:3690053,start:3668102},{filename:"/startData/Rampe03.sca",
audio:0,end:3713829,start:3690053},{filename:"/startData/Rampe03A.sca",audio:0,end:3737672,start:3713829},{filename:"/startData/Rampe04.sca",audio:0,end:3762975,start:3737672},{filename:"/startData/Rampe05.sca",audio:0,end:3786405,start:3762975},{filename:"/startData/Rampe06.sca",audio:0,end:3811801,start:3786405},{filename:"/startData/Rampe07.sca",audio:0,end:3834133,start:3811801},{filename:"/startData/Rampe08.sca",audio:0,end:3857949,start:3834133},{filename:"/startData/Rampe09.sca",audio:0,end:3881340,
start:3857949},{filename:"/startData/Rampe10.sca",audio:0,end:3905106,start:3881340},{filename:"/startData/RayleighBenard.sca",audio:0,end:3930528,start:3905106},{filename:"/startData/Robinson.sca",audio:0,end:3954385,start:3930528},{filename:"/startData/Rossler.sca",audio:0,end:3979540,start:3954385},{filename:"/startData/Rucklidge.sca",audio:0,end:4005863,start:3979540},{filename:"/startData/Sakarya.sca",audio:0,end:4031387,start:4005863},{filename:"/startData/SinCos.sca",audio:0,end:4055921,start:4031387},
{filename:"/startData/SprottLinzF.sca",audio:0,end:4081293,start:4055921},{filename:"/startData/Thomas.sca",audio:0,end:4106460,start:4081293},{filename:"/startData/TSUCS.sca",audio:0,end:4131726,start:4106460},{filename:"/startData/YuWang.sca",audio:0,end:4157026,start:4131726},{filename:"/startData/ZhouChen.sca",audio:0,end:4182443,start:4157026}],package_uuid:"4bf2ba08-f547-43d1-93e7-5a06861f7b6c"});var aa={},ba;for(ba in h)h.hasOwnProperty(ba)&&(aa[ba]=h[ba]);var ca=[],da="./this.program";
function ea(a,b){throw b;}var fa=!1,m=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;m="function"===typeof importScripts;ha=(ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!m;ja=!fa&&!ha&&!m;var n="",ka,la,ma;
if(ha){n=__dirname+"/";var na,oa;ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);a=na.readFileSync(a);return b?a:a.toString()};ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));ca=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=h);process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;});process.on("unhandledRejection",q);ea=function(a){process.exit(a)};
h.inspect=function(){return"[Emscripten Module object]"}}else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||m)m?n=self.location.href:document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=h.print||console.log.bind(console),l=h.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(h[ba]=aa[ba]);aa=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);
function ra(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:if("*"===a[a.length-1])return 4;if("i"===a[0]){var b=parseInt(a.substr(1));assert(0===b%8,"getNativeTypeSize invalid bits "+b+", type "+a);return b/8}return 0}}function sa(a){ta||(ta={});ta[a]||(ta[a]=1,l(a))}var ta,ua;h.wasmBinary&&(ua=h.wasmBinary);var va;h.noExitRuntime&&(va=h.noExitRuntime);"object"!==typeof WebAssembly&&l("no native wasm support detected");
function v(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":w[a>>0]=b;break;case "i8":w[a>>0]=b;break;case "i16":wa[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":z=[b>>>0,(A=b,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[a>>2]=z[0];x[a+4>>2]=z[1];break;case "float":B[a>>2]=b;break;case "double":Ba[a>>3]=b;break;default:q("invalid type for setValue: "+c)}}
var Ca,Da=new WebAssembly.Table({initial:859,maximum:859,element:"anyfunc"}),C=!1;function assert(a,b){a||q("Assertion failed: "+b)}
function Ea(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;var e="string"===typeof b?b:null;var f=Fa(Math.max(d,e?1:b.length));if(c){a=f;assert(0==(f&3));for(b=f+(d&-4);a<b;a+=4)x[a>>2]=0;for(b=f+d;a<b;)w[a++>>0]=0;return f}if("i8"===e)return a.subarray||a.slice?E.set(a,f):E.set(new Uint8Array(a),f),f;c=0;for(var k,r,p;c<d;){var u=a[c];k=e||b[c];0===k?c++:("i64"==k&&(k="i32"),v(f+c,u,k),p!==k&&(r=ra(k),p=k),c+=r)}return f}
var Ga="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ha(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ga)return Ga.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?Ha(E,a,b):""}
function Ia(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var r=a.charCodeAt(++f);k=65536+((k&1023)<<10)|r&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Ja(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ka(a){var b=Ja(a)+1,c=La(b);Ia(a,w,c,b);return c}function Ma(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,w,E,wa,Na,x,Oa,B,Ba;
function Pa(a){buffer=a;h.HEAP8=w=new Int8Array(a);h.HEAP16=wa=new Int16Array(a);h.HEAP32=x=new Int32Array(a);h.HEAPU8=E=new Uint8Array(a);h.HEAPU16=Na=new Uint16Array(a);h.HEAPU32=Oa=new Uint32Array(a);h.HEAPF32=B=new Float32Array(a);h.HEAPF64=Ba=new Float64Array(a)}var Qa=h.TOTAL_MEMORY||16777216;h.wasmMemory?Ca=h.wasmMemory:Ca=new WebAssembly.Memory({initial:Qa/65536});Ca&&(buffer=Ca.buffer);Qa=buffer.byteLength;Pa(buffer);x[26228]=5347952;
function Ra(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.oc;"number"===typeof c?void 0===b.rc?h.dynCall_v(c):h.dynCall_vi(c,b.rc):c(void 0===b.rc?null:b.rc)}}}var Sa=[],Ta=[],Ua=[],Va=[],Wa=[],Xa=!1;function Ya(){var a=h.preRun.shift();Sa.unshift(a)}var xa=Math.abs,Aa=Math.ceil,za=Math.floor,ya=Math.min,Za=0,$a=null,ab=null;function bb(){Za++;h.monitorRunDependencies&&h.monitorRunDependencies(Za)}
function cb(){Za--;h.monitorRunDependencies&&h.monitorRunDependencies(Za);if(0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab)){var a=ab;ab=null;a()}}h.preloadedImages={};h.preloadedAudios={};function q(a){if(h.onAbort)h.onAbort(a);qa(a);l(a);C=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}function db(){var a=eb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var eb="wglChAoSP.wasm";
if(!db()){var fb=eb;eb=h.locateFile?h.locateFile(fb,n):n+fb}function gb(){try{if(ua)return new Uint8Array(ua);if(ma)return ma(eb);throw"both async and sync fetching of the wasm failed";}catch(a){q(a)}}function hb(){return ua||!fa&&!m||"function"!==typeof fetch?new Promise(function(a){a(gb())}):fetch(eb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+eb+"'";return a.arrayBuffer()}).catch(function(){return gb()})}var A,z;Ta.push({oc:function(){ib()}});
function jb(a){h.___errno_location&&(x[h.___errno_location()>>2]=a)}function kb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function lb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function mb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function nb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function ob(){var a=Array.prototype.slice.call(arguments,0);return lb(a.join("/"))}function G(a,b){return lb(a+"/"+b)}
function pb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var qb=[];function rb(a,b){qb[a]={input:[],output:[],Dc:b};sb(a,tb)}
var tb={open:function(a){var b=qb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Dc.flush(a.tty)},flush:function(a){a.tty.Dc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Dc.Ud)throw new H(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.Dc.Ud(a.tty)}catch(r){throw new H(29);}if(void 0===k&&0===e)throw new H(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Dc.Cd)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.Dc.Cd(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},vb={Ud:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.Hc?Buffer.Hc(256):new Buffer(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ub(b,!0)}return a.input.shift()},Cd:function(a,b){null===b||10===b?(qa(Ha(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ha(a.output,0)),a.output=[])}},wb={Cd:function(a,b){null===b||10===b?(l(Ha(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(Ha(a.output,0)),a.output=[])}},I={mc:null,jc:function(){return I.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.mc||(I.mc={dir:{node:{nc:I.cc.nc,hc:I.cc.hc,lookup:I.cc.lookup,Mc:I.cc.Mc,rename:I.cc.rename,unlink:I.cc.unlink,rmdir:I.cc.rmdir,readdir:I.cc.readdir,symlink:I.cc.symlink},stream:{pc:I.dc.pc}},file:{node:{nc:I.cc.nc,hc:I.cc.hc},stream:{pc:I.dc.pc,read:I.dc.read,write:I.dc.write,Gd:I.dc.Gd,$d:I.dc.$d,jd:I.dc.jd}},link:{node:{nc:I.cc.nc,hc:I.cc.hc,readlink:I.cc.readlink},stream:{}},Ld:{node:{nc:I.cc.nc,
hc:I.cc.hc},stream:zb}});c=Ab(a,b,c,d);J(c.mode)?(c.cc=I.mc.dir.node,c.dc=I.mc.dir.stream,c.bc={}):32768===(c.mode&61440)?(c.cc=I.mc.file.node,c.dc=I.mc.file.stream,c.ec=0,c.bc=null):40960===(c.mode&61440)?(c.cc=I.mc.link.node,c.dc=I.mc.link.stream):8192===(c.mode&61440)&&(c.cc=I.mc.Ld.node,c.dc=I.mc.Ld.stream);c.timestamp=Date.now();a&&(a.bc[b]=c);return c},Hh:function(a){if(a.bc&&a.bc.subarray){for(var b=[],c=0;c<a.ec;++c)b.push(a.bc[c]);return b}return a.bc},Ih:function(a){return a.bc?a.bc.subarray?
a.bc.subarray(0,a.ec):new Uint8Array(a.bc):new Uint8Array},Od:function(a,b){var c=a.bc?a.bc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.bc,a.bc=new Uint8Array(b),0<a.ec&&a.bc.set(c.subarray(0,a.ec),0))},Re:function(a,b){if(a.ec!=b)if(0==b)a.bc=null,a.ec=0;else{if(!a.bc||a.bc.subarray){var c=a.bc;a.bc=new Uint8Array(new ArrayBuffer(b));c&&a.bc.set(c.subarray(0,Math.min(b,a.ec)))}else if(a.bc||(a.bc=[]),a.bc.length>b)a.bc.length=b;else for(;a.bc.length<b;)a.bc.push(0);
a.ec=b}},cc:{nc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ec:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.sc=4096;b.blocks=Math.ceil(b.size/b.sc);return b},hc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&
I.Re(a,b.size)},lookup:function(){throw Bb[44];},Mc:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(J(a.mode)){try{var d=Cb(b,c)}catch(f){}if(d)for(var e in d.bc)throw new H(55);}delete a.parent.bc[a.name];a.name=c;b.bc[c]=a;a.parent=b},unlink:function(a,b){delete a.bc[b]},rmdir:function(a,b){var c=Cb(a,b),d;for(d in c.bc)throw new H(55);delete a.bc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.bc)a.bc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=
I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},dc:{read:function(a,b,c,d,e){var f=a.node.bc;if(e>=a.node.ec)return 0;a=Math.min(a.node.ec-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){f=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.bc||a.bc.subarray)){if(f)return a.bc=b.subarray(c,c+d),a.ec=d;if(0===a.ec&&0===e)return a.bc=
new Uint8Array(b.subarray(c,c+d)),a.ec=d;if(e+d<=a.ec)return a.bc.set(b.subarray(c,c+d),e),d}I.Od(a,e+d);if(a.bc.subarray&&b.subarray)a.bc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.bc[e+f]=b[c+f];a.ec=Math.max(a.ec,e+d);return d},pc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ec);if(0>b)throw new H(28);return b},Gd:function(a,b,c){I.Od(a.node,b+c);a.node.ec=Math.max(a.node.ec,b+c)},$d:function(a,b,c,d,e,f,k){if(32768!==(a.node.mode&61440))throw new H(43);
c=a.node.bc;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.ec)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==w.buffer;d=Fa(d);if(!d)throw new H(48);(e?w:b).set(c,d)}else a=!1,d=c.byteOffset;return{Oh:d,re:a}},jd:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);if(e&2)return 0;I.dc.write(a,b,0,d,c,!1);return 0}}},Db={Yg:63,xg:44,lh:71,Uf:27,Wf:29,Ug:60,gf:1,yg:45,rf:8,Af:12,nf:6,vh:6,Cg:48,hf:2,Nf:21,Lg:105,yf:10,Mf:20,wh:75,wg:43,
Ng:54,Yf:31,Vf:28,rg:41,jg:33,Sg:59,sh:74,Of:22,Hg:51,kh:70,hh:69,kg:34,$g:64,Jf:18,eh:68,Dg:49,Rf:24,Bf:106,$f:156,ag:107,bg:108,hg:109,th:110,ug:111,Zf:112,Gf:16,zg:46,qf:113,uf:114,xh:115,sg:104,vf:103,wf:102,Hf:16,xf:101,Jg:100,vg:116,ph:117,Ig:118,Eg:119,Fg:120,gh:121,Ag:47,lf:122,mh:123,Cf:124,ah:65,mg:36,Kf:125,tf:9,Tg:126,sf:127,fh:128,cg:129,dg:130,gg:131,fg:132,eg:133,Kg:52,Og:55,ng:37,ig:32,Vg:138,Zg:139,Ff:15,tg:42,mf:5,dh:67,Qg:57,Gg:50,ih:140,Ef:14,jf:3,Df:13,qg:40,og:38,qh:73,Pf:142,
Qf:23,Tf:26,pf:7,If:17,lg:35,bh:66,jh:137,kf:4,pg:39,Xf:30,Mg:53,rh:141,uh:136,Lf:19,nh:72,Rg:138,Bg:148,Sf:25,Wg:61,zf:11,Pg:56,Xg:62,oh:135},K={bd:!1,Ye:function(){K.bd=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);K.Pd={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Hd:function(a){return Buffer.alloc?Buffer.from(a):new Buffer(a)},fc:function(a){a=a.code;assert(a in Db);return Db[a]},jc:function(a){assert(ia);
return K.createNode(null,"/",K.Td(a.Bd.root),0)},createNode:function(a,b,c){if(!J(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new H(28);a=Ab(a,b,c);a.cc=K.cc;a.dc=K.dc;return a},Td:function(a){try{var b=fs.lstatSync(a);K.bd&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new H(K.fc(c));}return b.mode},kc:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.jc.Bd.root);b.reverse();return ob.apply(null,b)},De:function(a){a&=-2656257;var b=0,c;for(c in K.Pd)a&
c&&(b|=K.Pd[c],a^=c);if(a)throw new H(28);return b},cc:{nc:function(a){a=K.kc(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new H(K.fc(c));}K.bd&&!b.sc&&(b.sc=4096);K.bd&&!b.blocks&&(b.blocks=(b.size+b.sc-1)/b.sc|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,sc:b.sc,blocks:b.blocks}},hc:function(a,b){var c=K.kc(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&
fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new H(K.fc(d));}},lookup:function(a,b){var c=G(K.kc(a),b);c=K.Td(c);return K.createNode(a,b,c)},Mc:function(a,b,c,d){a=K.createNode(a,b,c,d);b=K.kc(a);try{J(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new H(K.fc(e));}return a},rename:function(a,b,c){a=K.kc(a);b=G(K.kc(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new H(K.fc(d));}},unlink:function(a,b){a=G(K.kc(a),
b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new H(K.fc(c));}},rmdir:function(a,b){a=G(K.kc(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new H(K.fc(c));}},readdir:function(a){a=K.kc(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new H(K.fc(b));}},symlink:function(a,b,c){a=G(K.kc(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new H(K.fc(d));}},readlink:function(a){var b=K.kc(a);try{return b=fs.readlinkSync(b),b=Eb.relative(Eb.resolve(a.jc.Bd.root),
b)}catch(c){if(!c.code)throw c;throw new H(K.fc(c));}}},dc:{open:function(a){var b=K.kc(a.node);try{32768===(a.node.mode&61440)&&(a.Oc=fs.openSync(b,K.De(a.flags)))}catch(c){if(!c.code)throw c;throw new H(K.fc(c));}},close:function(a){try{32768===(a.node.mode&61440)&&a.Oc&&fs.closeSync(a.Oc)}catch(b){if(!b.code)throw b;throw new H(K.fc(b));}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.Oc,K.Hd(b.buffer),c,d,e)}catch(f){throw new H(K.fc(f));}},write:function(a,b,c,d,e){try{return fs.writeSync(a.Oc,
K.Hd(b.buffer),c,d,e)}catch(f){throw new H(K.fc(f));}},pc:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Oc).size}catch(d){throw new H(K.fc(d));}if(0>b)throw new H(28);return b}}},Fb=null,Gb={},Hb=[],Ib=1,Jb=null,Kb=!0,Lb={},H=null,Bb={};
function M(a,b){a=pb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Qd:!0,Dd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Dd)throw new H(32);a=kb(a.split("/").filter(function(a){return!!a}),!1);var e=Fb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Cb(e,a[d]);c=G(c,a[d]);e.Nc&&(!f||f&&b.Qd)&&(e=e.Nc.root);if(!f||b.Zc)for(f=0;40960===(e.mode&61440);)if(e=Mb(c),c=pb(mb(c),e),e=M(c,{Dd:b.Dd}).node,40<f++)throw new H(32);}return{path:c,node:e}}
function Nb(a){for(var b;;){if(a===a.parent)return a=a.jc.ae,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Jb.length}function Pb(a){var b=Ob(a.parent.id,a.name);a.Bc=Jb[b];Jb[b]=a}function Cb(a,b){var c;if(c=(c=Qb(a,"x"))?c:a.cc.lookup?0:2)throw new H(c,a);for(c=Jb[Ob(a.id,b)];c;c=c.Bc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.cc.lookup(a,b)}
function Ab(a,b,c,d){Rb||(Rb=function(a,b,c,d){a||(a=this);this.parent=a;this.jc=a.jc;this.Nc=null;this.id=Ib++;this.name=b;this.mode=c;this.cc={};this.dc={};this.rdev=d},Rb.prototype={},Object.defineProperties(Rb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ne:{get:function(){return J(this.mode)}},Me:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Rb(a,b,c,d);Pb(a);return a}function J(a){return 16384===(a&61440)}var Sb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Qb(a,b){if(Kb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Ub(a,b){try{return Cb(a,b),20}catch(c){}return Qb(a,"wx")}function Vb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Hb[a])return a;throw new H(33);}function Wb(a,b){Xb||(Xb=function(){},Xb.prototype={},Object.defineProperties(Xb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Xb,d;for(d in a)c[d]=a[d];a=c;b=Vb(b);a.fd=b;return Hb[b]=a}var zb={open:function(a){a.dc=Gb[a.node.rdev].dc;a.dc.open&&a.dc.open(a)},pc:function(){throw new H(70);}};
function sb(a,b){Gb[a]={dc:b}}function Yb(a,b){var c="/"===b,d=!b;if(c&&Fb)throw new H(10);if(!c&&!d){var e=M(b,{Qd:!1});b=e.path;e=e.node;if(e.Nc)throw new H(10);if(!J(e.mode))throw new H(54);}b={type:a,Bd:{},ae:b,Pe:[]};a=a.jc(b);a.jc=b;b.root=a;c?Fb=a:e&&(e.Nc=b,e.jc&&e.jc.Pe.push(b))}function Zb(a,b,c){var d=M(a,{parent:!0}).node;a=nb(a);if(!a||"."===a||".."===a)throw new H(28);var e=Ub(d,a);if(e)throw new H(e);if(!d.cc.Mc)throw new H(63);return d.cc.Mc(d,a,b,c)}
function N(a,b){return Zb(a,(void 0!==b?b:511)&1023|16384,0)}function $b(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Zb(a,b|8192,c)}function ac(a,b){if(!pb(a))throw new H(44);var c=M(b,{parent:!0}).node;if(!c)throw new H(44);b=nb(b);var d=Ub(c,b);if(d)throw new H(d);if(!c.cc.symlink)throw new H(63);return c.cc.symlink(c,b,a)}
function bc(a){var b=M(a,{parent:!0}).node,c=nb(a),d=Cb(b,c);a:{try{var e=Cb(b,c)}catch(k){e=k.lc;break a}var f=Qb(b,"wx");e=f?f:J(e.mode)?31:0}if(e)throw new H(e);if(!b.cc.unlink)throw new H(63);if(d.Nc)throw new H(10);try{Lb.willDeletePath&&Lb.willDeletePath(a)}catch(k){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.cc.unlink(b,c);b=Ob(d.parent.id,d.name);if(Jb[b]===d)Jb[b]=d.Bc;else for(b=Jb[b];b;){if(b.Bc===d){b.Bc=d.Bc;break}b=b.Bc}try{if(Lb.onDeletePath)Lb.onDeletePath(a)}catch(k){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Mb(a){a=M(a).node;if(!a)throw new H(44);if(!a.cc.readlink)throw new H(28);return pb(Nb(a.parent),a.cc.readlink(a))}function cc(a,b){var c;"string"===typeof a?c=M(a,{Zc:!0}).node:c=a;if(!c.cc.hc)throw new H(63);c.cc.hc(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function ec(a,b,c,d){if(""===a)throw new H(44);if("string"===typeof b){var e=Sb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=lb(a);try{f=M(a,{Zc:!(b&131072)}).node}catch(r){}}e=!1;if(b&64)if(f){if(b&128)throw new H(20);}else f=Zb(a,c,0),e=!0;if(!f)throw new H(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!J(f.mode))throw new H(54);if(!e&&(c=f?40960===(f.mode&61440)?32:J(f.mode)&&
("r"!==Tb(b)||b&512)?31:Qb(f,Tb(b)):44))throw new H(c);if(b&512){c=f;var k;"string"===typeof c?k=M(c,{Zc:!0}).node:k=c;if(!k.cc.hc)throw new H(63);if(J(k.mode))throw new H(31);if(32768!==(k.mode&61440))throw new H(28);if(c=Qb(k,"w"))throw new H(c);k.cc.hc(k,{size:0,timestamp:Date.now()})}b&=-641;d=Wb({node:f,path:Nb(f),flags:b,seekable:!0,position:0,dc:f.dc,df:[],error:!1},d);d.dc.open&&d.dc.open(d);!h.logReadFiles||b&1||(fc||(fc={}),a in fc||(fc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Lb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Lb.onOpenFile(a,f))}catch(r){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+r.message)}return d}function hc(a){if(null===a.fd)throw new H(8);a.uc&&(a.uc=null);try{a.dc.close&&a.dc.close(a)}catch(b){throw b;}finally{Hb[a.fd]=null}a.fd=null}
function ic(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.dc.pc)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.dc.pc(a,b,c);a.df=[];return a.position}
function jc(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(J(a.node.mode))throw new H(31);if(!a.dc.write)throw new H(28);a.flags&1024&&ic(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new H(70);b=a.dc.write(a,b,c,d,e,f);k||(a.position+=b);try{if(a.path&&Lb.onWriteToFile)Lb.onWriteToFile(a.path)}catch(r){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+r.message)}return b}
function kc(){H||(H=function(a,b){this.node=b;this.Ve=function(a){this.lc=a};this.Ve(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(function(a){Bb[a]=new H(a);Bb[a].stack="<generic error, no stack>"}))}var lc;function mc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function nc(a,b,c,d){a=G("string"===typeof a?a:Nb(a),b);return N(a,mc(c,d))}
function oc(a,b){a="string"===typeof a?a:Nb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a,c);try{N(d)}catch(e){}a=d}}return d}function pc(a,b,c,d){a=G("string"===typeof a?a:Nb(a),b);c=mc(c,d);return Zb(a,(void 0!==c?c:438)&4095|32768,0)}
function qc(a,b,c,d,e,f){a=b?G("string"===typeof a?a:Nb(a),b):a;d=mc(d,e);e=Zb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}cc(e,d|146);a=ec(e,"w");jc(a,c,0,c.length,0,f);hc(a);cc(e,d)}return e}
function O(a,b,c,d){a=G("string"===typeof a?a:Nb(a),b);b=mc(!!c,!!d);O.Yd||(O.Yd=64);var e=O.Yd++<<8|0;sb(e,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,e){for(var f=0,k=0;k<e;k++){try{var p=c()}catch(D){throw new H(29);}if(void 0===p&&0===f)throw new H(6);if(null===p||void 0===p)break;f++;b[d+k]=p}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){for(var f=0;f<e;f++)try{d(b[c+f])}catch(t){throw new H(29);}e&&(a.node.timestamp=
Date.now());return f}});return $b(a,b,e)}function rc(a,b,c){a=G("string"===typeof a?a:Nb(a),b);return ac(c,a)}
function sc(a){if(a.Me||a.Ne||a.link||a.bc)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.bc=ub(ka(a.url),!0),a.ec=a.bc.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||jb(29);return b}
function tc(a,b,c,d,e){function f(){this.zd=!1;this.Vc=[]}f.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Vd(a/this.chunkSize|0)[b]}};f.prototype.Ue=function(a){this.Vd=a};f.prototype.Id=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,e=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var f=1048576;e||(f=b);var k=this;k.Ue(function(a){var d=a*f,e=(a+1)*f-1;e=Math.min(e,b-1);if("undefined"===typeof k.Vc[a]){var y=k.Vc;if(d>e)throw Error("invalid range ("+d+", "+e+") or no bytes requested!");if(e>b-1)throw Error("only "+b+" bytes available! programmer error!");var p=new XMLHttpRequest;p.open("GET",c,!1);b!==f&&p.setRequestHeader("Range","bytes="+d+"-"+e);"undefined"!=typeof Uint8Array&&(p.responseType="arraybuffer");
p.overrideMimeType&&p.overrideMimeType("text/plain; charset=x-user-defined");p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);d=void 0!==p.response?new Uint8Array(p.response||[]):ub(p.responseText||"",!0);y[a]=d}if("undefined"===typeof k.Vc[a])throw Error("doXHR failed!");return k.Vc[a]});if(a||!b)f=b=1,f=b=this.Vd(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.qe=b;this.pe=
f;this.zd=!0};if("undefined"!==typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.zd||this.Id();return this.qe}},chunkSize:{get:function(){this.zd||this.Id();return this.pe}}});var r=void 0}else r=c,k=void 0;var p=pc(a,b,d,e);k?p.bc=k:r&&(p.bc=null,p.url=r);Object.defineProperties(p,{ec:{get:function(){return this.bc.length}}});var u=
{};Object.keys(p.dc).forEach(function(a){var b=p.dc[a];u[a]=function(){if(!sc(p))throw new H(29);return b.apply(null,arguments)}});u.read=function(a,b,c,d,e){if(!sc(p))throw new H(29);a=a.node.bc;if(e>=a.length)return 0;d=Math.min(a.length-e,d);if(a.slice)for(var f=0;f<d;f++)b[c+f]=a[e+f];else for(f=0;f<d;f++)b[c+f]=a.get(e+f);return d};p.dc=u;return p}
function uc(a,b,c,d,e,f,k,r,p,u){function t(c){function y(c){u&&u();r||qc(a,b,c,d,e,p);f&&f();cb(D)}var t=!1;h.preloadPlugins.forEach(function(a){!t&&a.canHandle(L)&&(a.handle(c,L,y,function(){k&&k();cb(D)}),t=!0)});t||y(c)}g.Wd();var L=b?pb(G(a,b)):a,D="cp "+L;bb(D);"string"==typeof c?g.te(c,function(a){t(a)},k):t(c)}var P={},Rb,Xb,fc,vc={},wc=0;function Q(){wc+=4;return x[wc-4>>2]}function xc(a){void 0===a&&(a=Q());a=Hb[a];if(!a)throw new H(8);return a}function yc(){q()}
g={ac:{qc:null,method:"",xc:0,oc:null,rc:0,od:0,pd:0,wc:0,ee:[],pause:function(){g.ac.qc=null;g.ac.xc++},resume:function(){g.ac.xc++;var a=g.ac.od,b=g.ac.pd,c=g.ac.oc;g.ac.oc=null;zc(c,0,!1,g.ac.rc,!0);Ac(a,b);g.ac.qc()},ef:function(){if(h.setStatus){var a=h.statusMessage||"Please wait...",b=g.ac.Ed,c=g.ac.Eh;b?b<c?h.setStatus(a+" ("+(c-b)+"/"+c+")"):h.setStatus(a):h.setStatus("")}},Se:function(a){if(!(C||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(b){if(b instanceof pa)return;b&&"object"===
typeof b&&b.stack&&l("exception thrown: "+[b,b.stack]);throw b;}h.postMainLoop&&h.postMainLoop()}}},Jc:!1,Pc:!1,Oe:[],workers:[],Wd:function(){function a(){g.Pc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!g.Ke){g.Ke=!0;try{g.$c=!0}catch(c){g.$c=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}g.BlobBuilder=
"undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:g.$c?null:console.log("warning: no BlobBuilder");g.Tc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.ce||"undefined"!==typeof g.Tc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.ce=!0);h.preloadPlugins.push({canHandle:function(a){return!h.ce&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,
b,e,f){var c=null;if(g.$c)try{c=new Blob([a],{type:g.yd(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:g.yd(b)}))}catch(u){sa("Blob constructor present but fails: "+u+"; falling back to blob builder")}c||(c=new g.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=g.Tc.createObjectURL(c),p=new Image;p.onload=function(){assert(p.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=p.width;c.height=p.height;c.getContext("2d").drawImage(p,
0,0);h.preloadedImages[b]=c;g.Tc.revokeObjectURL(d);e&&e(a)};p.onerror=function(){console.log("Image "+d+" could not be decoded");f&&f()};p.src=d}});h.preloadPlugins.push({canHandle:function(a){return!h.Mh&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,f){function c(c){p||(p=!0,h.preloadedAudios[b]=c,e&&e(a))}function d(){p||(p=!0,h.preloadedAudios[b]=new Audio,f&&f())}var p=!1;if(g.$c){try{var u=new Blob([a],{type:g.yd(b)})}catch(L){return d()}u=g.Tc.createObjectURL(u);var t=
new Audio;t.addEventListener("canplaythrough",function(){c(t)},!1);t.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,f=0,k=0;k<a.length;k++)for(e=e<<8|a[k],f+=8;6<=f;){var r=e>>f-6&63;f-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[r]}2==f?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==f&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&
15)<<2],d+="=");t.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(t)}};t.src=u;g.Te(function(){c(t)},1E4)}else return d()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",
a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",function(a){!g.Pc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&h.tc&&a==h.canvas)return h.tc;var e;if(b){var f={antialias:!1,alpha:!1,Zd:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)f[k]=
d[k];if("undefined"!==typeof Bc&&(e=Cc(a,f)))var r=Dc[e].vc}else r=a.getContext("2d");if(!r)return null;c&&(b||assert("undefined"===typeof R,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.tc=r,b&&(S=Dc[e],h.tc=R=S&&S.vc),h.Xh=b,g.Oe.forEach(function(a){a()}),g.Wd());return r},Ch:function(){},Sd:!1,dd:void 0,Ec:void 0,requestFullscreen:function(a,b,c){function d(){g.Jc=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||
document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=g.exitFullscreen,g.dd&&e.requestPointerLock(),g.Jc=!0,g.Ec?g.We():g.Sc(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),g.Ec?g.Xe():g.Sc(e));if(h.onFullScreen)h.onFullScreen(g.Jc);if(h.onFullscreen)h.onFullscreen(g.Jc)}g.dd=a;g.Ec=b;g.ne=c;"undefined"===typeof g.dd&&(g.dd=!0);"undefined"===typeof g.Ec&&(g.Ec=!1);"undefined"===typeof g.ne&&(g.ne=null);var e=h.canvas;g.Sd||(g.Sd=!0,document.addEventListener("fullscreenchange",
d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:
null);c?f.requestFullscreen({Yh:c}):f.requestFullscreen()},fe:function(a,b,c){l("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");g.fe=function(a,b,c){return g.requestFullscreen(a,b,c)};return g.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!g.Jc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},Cc:0,Be:function(a){var b=
Date.now();if(0===g.Cc)g.Cc=b+1E3/60;else for(;b+2>=g.Cc;)g.Cc+=1E3/60;setTimeout(a,Math.max(g.Cc-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=g.Be;b(a)}},Rh:function(a){return function(){if(!C)return a.apply(null,arguments)}},Ic:!0,Qc:[],Nh:function(){g.Ic=!1},Qh:function(){g.Ic=!0;if(0<g.Qc.length){var a=g.Qc;g.Qc=[];a.forEach(function(a){a()})}},Sh:function(a){return g.requestAnimationFrame(function(){C||(g.Ic?a():g.Qc.push(a))})},
Te:function(a,b){va=!0;return setTimeout(function(){C||(g.Ic?a():g.Qc.push(a))},b)},Th:function(a,b){va=!0;return setInterval(function(){C||g.Ic&&a()},b)},yd:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Fe:function(a){return a.movementX||
a.mozMovementX||a.webkitMovementX||0},Ge:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},Ee:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},zc:0,Ac:0,gd:0,hd:0,touches:{},Xd:{},
Jd:function(a){if(g.Pc)"mousemove"!=a.type&&"mozMovementX"in a?g.gd=g.hd=0:(g.gd=g.Fe(a),g.hd=g.Ge(a)),g.zc+=g.gd,g.Ac+=g.hd;else{var b=h.canvas.getBoundingClientRect(),c=h.canvas.width,d=h.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var k=a.Wh;if(void 0!==k)if(e=k.pageX-(e+b.left),f=k.pageY-(f+b.top),e*=c/b.width,f*=
d/b.height,b={x:e,y:f},"touchstart"===a.type)g.Xd[k.identifier]=b,g.touches[k.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=g.touches[k.identifier])||(a=b),g.Xd[k.identifier]=a,g.touches[k.identifier]=b}else k=a.pageX-(e+b.left),a=a.pageY-(f+b.top),k*=c/b.width,a*=d/b.height,g.gd=k-g.zc,g.hd=a-g.Ac,g.zc=k,g.Ac=a}},te:function(a,b,c,d){var e=d?"":"al "+a;la(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));e&&cb(e)},function(){if(c)c();
else throw'Loading data file "'+a+'" failed.';});e&&bb(e)},ge:[],Fd:function(){var a=h.canvas;g.ge.forEach(function(b){b(a.width,a.height)})},md:function(a,b,c){g.Sc(h.canvas,a,b);c||g.Fd()},ai:0,$h:0,We:function(){g.Sc(h.canvas);g.Fd()},Xe:function(){g.Sc(h.canvas);g.Fd()},Sc:function(a,b,c){b&&c?(a.ff=b,a.Ie=c):(b=a.ff,c=a.Ie);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||
document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}g.Ec?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||
e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},Zh:{},be:0,Jh:function(){var a=g.be;g.be++;return a}};
function Ac(a,b){g.ac.od=a;g.ac.pd=b;if(g.ac.oc)if(0==a)g.ac.qc=function(){var a=Math.max(0,g.ac.Ze+b-yc())|0;setTimeout(g.ac.kd,a)},g.ac.method="timeout";else if(1==a)g.ac.qc=function(){g.requestAnimationFrame(g.ac.kd)},g.ac.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);m?(void 0===h.setImmediates&&(h.setImmediates=
[]),h.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}g.ac.qc=function(){setImmediate(g.ac.kd)};g.ac.method="immediate"}}
function zc(a,b,c,d,e){va=!0;assert(!g.ac.oc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");g.ac.oc=a;g.ac.rc=d;var f="undefined"!==typeof d?function(){h.dynCall_vi(a,d)}:function(){h.dynCall_v(a)};var k=g.ac.xc;g.ac.kd=function(){if(!C)if(0<g.ac.ee.length){var a=Date.now(),b=g.ac.ee.shift();b.oc(b.rc);if(g.ac.Ed){var c=g.ac.Ed,d=0==c%1?c-1:Math.floor(c);
g.ac.Ed=b.Ah?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");g.ac.ef();k<g.ac.xc||setTimeout(g.ac.kd,0)}else k<g.ac.xc||(g.ac.wc=g.ac.wc+1|0,1==g.ac.od&&1<g.ac.pd&&0!=g.ac.wc%g.ac.pd?g.ac.qc():(0==g.ac.od&&(g.ac.Ze=yc()),"undefined"!==typeof Bc&&S&&!Bc.Bh&&!S.attributes.Fh&&S.vc.ye&&S.vc.ye(),"timeout"===g.ac.method&&h.tc&&(l("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
g.ac.method=""),g.ac.Se(f),k<g.ac.xc||g.ac.qc()))};e||(b&&0<b?Ac(0,1E3/b):Ac(1,1),g.ac.qc());if(c)throw"SimulateInfiniteLoop";}var Ec=0,Fc=!1;function Gc(){for(var a=Hc.length-1;0<=a;--a)Ic(a);Hc=[];Jc=[]}var Jc=[];function Kc(){if(Lc&&Mc.se)for(var a=0;a<Jc.length;++a){var b=Jc[a];Jc.splice(a,1);--a;b.Uh.apply(this,b.zh)}}var Lc=0,Mc=null,Hc=[];function Ic(a){var b=Hc[a];b.target.removeEventListener(b.Yc,b.Ae,b.me);Hc.splice(a,1)}
function Nc(a){function b(b){++Lc;Mc=a;Kc();a.He(b);Kc();--Lc}if(a.xe)a.Ae=b,a.target.addEventListener(a.Yc,b,a.me),Hc.push(a),Fc||(Va.push(Gc),Fc=!0);else for(var c=0;c<Hc.length;++c)Hc[c].target==a.target&&Hc[c].Yc==a.Yc&&Ic(c--)}function Oc(a){return a===a+0?F(a):a}var Pc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function Qc(a,b,c,d,e,f){Ec||(Ec=Fa(1684));a=Pc[a]||("undefined"!==typeof document?document.querySelector(Oc(a)):void 0);Nc({target:a,se:"touchstart"==f||"touchend"==f,Yc:f,xe:d,He:function(c){c=c||event;for(var f={},k=0;k<c.touches.length;++k){var u=c.touches[k];u.Kd=!1;f[u.identifier]=u}for(k=0;k<c.changedTouches.length;++k)u=c.changedTouches[k],f[u.identifier]=u,u.Kd=!0;for(k=0;k<c.targetTouches.length;++k)u=c.targetTouches[k],f[u.identifier].Qe=!0;var t=u=Ec;x[t+4>>2]=c.ctrlKey;x[t+8>>2]=c.shiftKey;
x[t+12>>2]=c.altKey;x[t+16>>2]=c.metaKey;t+=20;var L=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},D=0;for(k in f){var y=f[k];x[t>>2]=y.identifier;x[t+4>>2]=y.screenX;x[t+8>>2]=y.screenY;x[t+12>>2]=y.clientX;x[t+16>>2]=y.clientY;x[t+20>>2]=y.pageX;x[t+24>>2]=y.pageY;x[t+28>>2]=y.Kd;x[t+32>>2]=y.Qe;x[t+36>>2]=y.clientX-L.left;x[t+40>>2]=y.clientY-L.top;t+=52;if(32<=++D)break}x[u>>2]=D;Rc(d,e,u,b)&&c.preventDefault()},me:c})}var Sc={};
function Tc(){if(!Uc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da},b;for(b in Sc)a[b]=Sc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Uc=c}return Uc}var Uc,Vc=1,Wc=0,Xc=[],T=[],Yc=[],Zc=[],$c=[],ad=[],U=[],bd=[],Dc={},S=null,cd=[],dd={},ed={},fd=4;function V(a){Wc||(Wc=a)}function gd(a){for(var b=Vc++,c=a.length;c<b;c++)a[c]=null;return b}
var hd=null,id=[0];function Cc(a,b){return(a=1<b.Zd?a.getContext("webgl2",b):a.getContext("webgl",b)||a.getContext("experimental-webgl",b))?jd(a,b):0}function jd(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=Fa(8),e={handle:d,attributes:b,version:b.Zd,vc:a};e.nd=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.yh=e);Dc[d]=e;("undefined"===typeof b.ze||b.ze)&&kd(e);return d}
function ld(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,f){b.drawArraysInstancedANGLE(a,d,e,f)},a.drawElementsInstanced=function(a,d,e,f,k){b.drawElementsInstancedANGLE(a,d,e,f,k)})}
function md(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function nd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function kd(a){a||(a=S);if(!a.Je){a.Je=!0;var b=a.vc;2>a.version&&(ld(b),md(b),nd(b));b.Dh=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var Bc={},od,pd,qd=[];function rd(a,b,c,d){for(var e=0;e<a;e++){var f=R[c](),k=f&&gd(d);f?(f.name=k,d[k]=f):V(1282);x[b+4*e>>2]=k}}
function sd(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=R.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>S.version){V(1282);return}c=2*(R.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){V(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=R.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:V(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)x[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V(1280);l("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:V(1280);l("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}x[b>>2]=c}else V(1281)}
function td(a){var b=Ja(a)+1,c=Fa(b);Ia(a,E,c,b);return c}var ud={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},vd={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function wd(a,b,c,d,e){if(b=ud[b]*vd[a]){var f=fd;c=e+d*(c*b+f-1&-f);switch(a){case 5120:return w.subarray(e,c);case 5121:return E.subarray(e,c);case 5122:return wa.subarray(e>>1,c>>1);case 5124:return x.subarray(e>>2,c>>2);case 5126:return B.subarray(e>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:return Oa.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Na.subarray(e>>1,c>>1);default:V(1280)}}else V(1280)}
function xd(a){switch(a){case 5120:return w;case 5121:return E;case 5122:return wa;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return Na;case 5124:return x;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return Oa;case 5126:return B}}var yd={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1};
function zd(a,b,c,d,e){this.id=a;this.y=this.x=0;this.xd=!1;this.ke=this.je=0;this.width=b;this.height=c;this.ie=b;this.he=c;this.title=d;this.share=e;this.attributes=Ad;this.ad={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.vd=[];this.Uc=this.cd=this.Nd=this.ld=this.Wc=this.Xc=this.ed=this.Rd=this.td=this.Gc=this.oe=this.title=null}function W(a){return 0>=a||!X?null:X[a-1]}
var Bd=null,Cd=null,Y=null,X=null,Dd=null,Ed=null,Ad=null,Fd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Gd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Hd(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Id(a){Y&&Y.Uc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||Jd(Y.Uc,Y.id,a))}function Kd(a,b){if(Y){var c=Gd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.vd[a]=b;Y.cd&&(d&&(b=2),Ld(Y.cd,Y.id,c,a,b,Hd()))}}}
function Md(){Nd()}function Od(){Nd()}function Pd(a){Kd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Qd(a){Kd(a.keyCode,0)}function Rd(){if(Y)for(var a=0;a<Y.vd.length;++a)Y.vd[a]&&Kd(a,0)}function Sd(a){Y&&(g.Jd(a),a.target==h.canvas&&Y.Xc&&Td(Y.Xc,Y.id,g.zc,g.Ac))}function Ud(a){Y&&a.target==h.canvas&&Y.Wc&&Jd(Y.Wc,Y.id,1)}function Vd(a){Y&&a.target==h.canvas&&Y.Wc&&Jd(Y.Wc,Y.id,0)}
function Wd(a,b){if(Y&&(g.Jd(a),a.target==h.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.ed&&Xd(Y.ed,Y.id,c,b,Hd())}}function Yd(a){Y&&Wd(a,1)}function Zd(a){Y&&Wd(a,0)}function $d(a){g.Ee(a);if(Y&&Y.ld&&a.target==h.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;Td(Y.ld,Y.id,b,c);a.preventDefault()}}
function ae(){(h.canvas.requestFullscreen||h.canvas.mozRequestFullScreen||h.canvas.webkitRequestFullScreen||function(){}).apply(h.canvas,[])}var Z={},be=null,ce=null;
function Nd(){if(g.ac.wc!==ce||!g.ac.wc){be=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;ce=g.ac.wc;for(var a=0;a<be.length;++a){var b=be[a];if(b){Z[a]||(console.log("glfw joystick connected:",a),Z[a]={id:Ea(ub(b.id),"i8"),ve:b.buttons.length,ue:b.axes.length,buttons:Ea(Array(b.buttons.length),"i8"),axes:Ea(Array(4*b.axes.length),"float")});for(var c=Z[a],d=0;d<b.buttons.length;++d)v(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)v(c.axes+
4*d,b.axes[d],"float")}else Z[a]&&(console.log("glfw joystick disconnected",a),de(Z[a].id),de(Z[a].buttons),de(Z[a].axes),delete Z[a])}}}function ee(a){if(Y&&Y.Nd&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1}function fe(a){if(Y&&Y.Nd)return a.preventDefault(),!1}function ge(a){!g.Pc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),a.preventDefault())}function he(a){return 0===a%4&&(0!==a%100||0===a%400)}
function ie(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var je=[31,29,31,30,31,30,31,31,30,31,30,31],ke=[31,28,31,30,31,30,31,31,30,31,30,31];function le(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(he(a.getFullYear())?je:ke)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function me(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function r(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function p(a){a=le(new Date(a.ic+1900,0,1),a.sd);var b=r(new Date(a.getFullYear()+1,0,4));return 0>=k(r(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var u=x[d+40>>2];d={bf:x[d>>2],af:x[d+4>>2],qd:x[d+8>>2],Rc:x[d+12>>2],Fc:x[d+16>>2],ic:x[d+20>>2],rd:x[d+24>>2],sd:x[d+28>>2],Vh:x[d+32>>2],$e:x[d+36>>2],
cf:u?F(u):""};c=F(c);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in u)c=c.replace(new RegExp(t,"g"),u[t]);var L="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
D="January February March April May June July August September October November December".split(" ");u={"%a":function(a){return L[a.rd].substring(0,3)},"%A":function(a){return L[a.rd]},"%b":function(a){return D[a.Fc].substring(0,3)},"%B":function(a){return D[a.Fc]},"%C":function(a){return f((a.ic+1900)/100|0,2)},"%d":function(a){return f(a.Rc,2)},"%e":function(a){return e(a.Rc,2," ")},"%g":function(a){return p(a).toString().substring(2)},"%G":function(a){return p(a)},"%H":function(a){return f(a.qd,
2)},"%I":function(a){a=a.qd;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.Rc+ie(he(a.ic+1900)?je:ke,a.Fc-1),3)},"%m":function(a){return f(a.Fc+1,2)},"%M":function(a){return f(a.af,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.qd&&12>a.qd?"AM":"PM"},"%S":function(a){return f(a.bf,2)},"%t":function(){return"\t"},"%u":function(a){return a.rd||7},"%U":function(a){var b=new Date(a.ic+1900,0,1),c=0===b.getDay()?b:le(b,7-b.getDay());a=new Date(a.ic+1900,a.Fc,a.Rc);return 0>
k(c,a)?f(Math.ceil((31-c.getDate()+(ie(he(a.getFullYear())?je:ke,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=r(new Date(a.ic+1900,0,4)),c=r(new Date(a.ic+1901,0,4)),d=le(new Date(a.ic+1900,0,1),a.sd);return 0>k(d,b)?"53":0>=k(c,d)?"01":f(Math.ceil((b.getFullYear()<a.ic+1900?a.sd+32-b.getDate():a.sd+1-b.getDate())/7),2)},"%w":function(a){return a.rd},"%W":function(a){var b=new Date(a.ic,0,1),c=1===b.getDay()?b:le(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.ic+
1900,a.Fc,a.Rc);return 0>k(c,a)?f(Math.ceil((31-c.getDate()+(ie(he(a.getFullYear())?je:ke,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.ic+1900).toString().substring(2)},"%Y":function(a){return a.ic+1900},"%z":function(a){a=a.$e;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.cf},"%%":function(){return"%"}};for(t in u)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),u[t](d)));t=ub(c,!1);if(t.length>
b)return 0;w.set(t,a);return t.length-1}kc();Jb=Array(4096);Yb(I,"/");N("/tmp");N("/home");N("/home/web_user");
(function(){N("/dev");sb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});$b("/dev/null",259);rb(1280,vb);rb(1536,wb);$b("/dev/tty",1280);$b("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){q("random_device")});O("/dev","random",b);O("/dev","urandom",b);
N("/dev/shm");N("/dev/shm/tmp")})();N("/proc");N("/proc/self");N("/proc/self/fd");Yb({jc:function(){var a=Ab("/proc/self","fd",16895,73);a.cc={lookup:function(a,c){var b=Hb[+c];if(!b)throw new H(8);a={parent:null,jc:{ae:"fake"},cc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");h.FS_createFolder=nc;h.FS_createPath=oc;h.FS_createDataFile=qc;h.FS_createPreloadedFile=uc;h.FS_createLazyFile=tc;h.FS_createLink=rc;h.FS_createDevice=O;h.FS_unlink=bc;
if(ia){var fs=require("fs"),Eb=require("path");K.Ye()}ha?yc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?yc=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?yc=function(){return performance.now()}:yc=Date.now;h.requestFullScreen=function(a,b,c){l("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");h.requestFullScreen=h.requestFullscreen;g.fe(a,b,c)};
h.requestFullscreen=function(a,b,c){g.requestFullscreen(a,b,c)};h.requestAnimationFrame=function(a){g.requestAnimationFrame(a)};h.setCanvasSize=function(a,b,c){g.md(a,b,c)};h.pauseMainLoop=function(){g.ac.pause()};h.resumeMainLoop=function(){g.ac.resume()};h.getUserMedia=function(){g.getUserMedia()};h.createContext=function(a,b,c,d){return g.createContext(a,b,c,d)};var R;hd=new Float32Array(256);for(var ne=0;256>ne;ne++)id[ne]=hd.subarray(0,ne+1);for(var oe=0;32>oe;oe++)qd.push(Array(oe));
function ub(a,b){var c=Array(Ja(a)+1);a=Ia(a,c,0,c.length);b&&(c.length=a);return c}
var te={e:function(a){return Fa(a)},h:function(a){"uncaught_exception"in pe?pe.Hc++:pe.Hc=1;throw a;},ta:function(){},pb:function(){jb(63);return-1},yb:function(a,b){wc=b;try{var c=xc(),d=Q(),e=Q();if(!c.uc){var f=M(c.path,{Zc:!0}).node;if(!f.cc.readdir)throw new H(54);var k=f.cc.readdir(f);c.uc=k}a=0;for(var r=ic(c,0,1),p=Math.floor(r/280);p<c.uc.length&&a+280<=e;){var u=c.uc[p];if("."===u[0]){var t=1;var L=4}else{var D=Cb(c.node,u);t=D.id;L=8192===(D.mode&61440)?2:J(D.mode)?4:40960===(D.mode&61440)?
10:8}z=[t>>>0,(A=t,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[d+a>>2]=z[0];x[d+a+4>>2]=z[1];z=[280*(p+1)>>>0,(A=280*(p+1),1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>0:0)];x[d+a+8>>2]=z[0];x[d+a+12>>2]=z[1];wa[d+a+16>>1]=280;w[d+a+18>>0]=L;Ia(u,E,d+a+19,256);a+=280;p+=1}ic(c,280*p,0);return a}catch(y){return"undefined"!==typeof P&&y instanceof H||q(y),-y.lc}},sa:function(a,b){wc=b;try{var c=xc();switch(Q()){case 0:var d=
Q();return 0>d?-28:ec(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Q(),c.flags|=d,0;case 12:return d=Q(),wa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return jb(28),-1;default:return-28}}catch(e){return"undefined"!==typeof P&&e instanceof H||q(e),-e.lc}},ua:function(a,b){wc=b;try{var c=F(Q()),d=Q(),e=Q();return ec(c,d,e).fd}catch(f){return"undefined"!==typeof P&&f instanceof H||q(f),-f.lc}},wb:function(a,b){wc=b;try{var c=xc(),d=Q();
switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var e=Q();return x[e>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=e=Q();if(!c.dc.Le)throw new H(59);return c.dc.Le(c,d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:q("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof P&&f instanceof H||q(f),-f.lc}},ob:function(a,b){wc=b;try{var c=Q(),d=Q();if(-1===
c||0===d)var e=-28;else{var f=vc[c];if(f&&d===f.Kh){var k=Hb[f.fd],r=f.flags,p=new Uint8Array(E.subarray(c,c+d));k&&k.dc.jd&&k.dc.jd(k,p,0,d,r);vc[c]=null;f.re&&de(f.Lh)}e=0}return e}catch(u){return"undefined"!==typeof P&&u instanceof H||q(u),-u.lc}},z:function(){},I:function(){q()},tb:function(a,b){if(0===a)a=Date.now();else if(1===a&&(ha||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=yc();else return jb(28),-1;x[b>>2]=a/1E3|0;x[b+
4>>2]=a%1E3*1E6|0;return 0},lb:function(a,b,c){E.set(E.subarray(b,b+c),a)},mb:function(a){if(2147418112<a)return!1;for(var b=Math.max(w.length,16777216);b<a;)536870912>=b?b=Ma(2*b):b=Math.min(Ma((3*b+2147483648)/4),2147418112);a:{try{Ca.grow(b-buffer.byteLength+65535>>16);Pa(Ca.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},Ib:zc,Lb:function(a,b,c,d){Qc(a,b,c,d,25,"touchcancel");return 0},Ea:function(a,b,c,d){Qc(a,b,c,d,23,"touchend");return 0},Da:function(a,b,c,d){Qc(a,b,c,d,24,"touchmove");
return 0},Fa:function(a,b,c,d){Qc(a,b,c,d,22,"touchstart");return 0},Ga:function(a,b){a=Dc[a];b=F(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?ld(R):"OES_vertex_array_object"==b?md(R):"WEBGL_draw_buffers"==b&&nd(R);return!!a.vc.getExtension(b)},Ha:function(){return S?S.handle:0},qb:function(a,b){var c=0;Tc().forEach(function(d,e){var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)w[e++>>0]=d.charCodeAt(f);w[e>>0]=0;c+=d.length+1});return 0},rb:function(a,b){var c=Tc();x[a>>2]=
c.length;var d=0;c.forEach(function(a){d+=a.length+1});x[b>>2]=d;return 0},Ba:function(a){qe(a)},J:function(a){try{var b=xc(a);hc(b);return 0}catch(c){return"undefined"!==typeof P&&c instanceof H||q(c),c.lc}},vb:function(a,b,c,d){try{a:{for(var e=xc(a),f=a=0;f<c;f++){var k=x[b+(8*f+4)>>2],r=e,p=x[b+8*f>>2],u=k,t=void 0,L=w;if(0>u||0>t)throw new H(28);if(null===r.fd)throw new H(8);if(1===(r.flags&2097155))throw new H(8);if(J(r.node.mode))throw new H(31);if(!r.dc.read)throw new H(28);var D="undefined"!==
typeof t;if(!D)t=r.position;else if(!r.seekable)throw new H(70);var y=r.dc.read(r,L,p,u,t);D||(r.position+=y);var xb=y;if(0>xb){var dc=-1;break a}a+=xb;if(xb<k)break}dc=a}x[d>>2]=dc;return 0}catch(yb){return"undefined"!==typeof P&&yb instanceof H||q(yb),yb.lc}},kb:function(a,b,c,d,e){try{var f=xc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;ic(f,a,d);z=[f.position>>>0,(A=f.position,1<=+xa(A)?0<A?(ya(+za(A/4294967296),4294967295)|0)>>>0:~~+Aa((A-+(~~A>>>0))/4294967296)>>>
0:0)];x[e>>2]=z[0];x[e+4>>2]=z[1];f.uc&&0===a&&0===d&&(f.uc=null);return 0}catch(k){return"undefined"!==typeof P&&k instanceof H||q(k),k.lc}},ub:function(a,b,c,d){try{a:{for(var e=xc(a),f=a=0;f<c;f++){var k=jc(e,w,x[b+8*f>>2],x[b+(8*f+4)>>2],void 0);if(0>k){var r=-1;break a}a+=k}r=a}x[d>>2]=r;return 0}catch(p){return"undefined"!==typeof P&&p instanceof H||q(p),p.lc}},f:function(a){R.activeTexture(a)},R:function(a,b){R.attachShader(T[a],U[b])},d:function(a,b){35051==a?R.Md=b:35052==a&&(R.ud=b);R.bindBuffer(a,
Xc[b])},xa:function(a,b,c){R.bindBufferBase(a,b,Xc[c])},i:function(a,b){R.bindFramebuffer(a,Yc[b])},Db:function(a,b){R.bindRenderbuffer(a,Zc[b])},ca:function(a,b){R.bindSampler(a,cd[b])},a:function(a,b){R.bindTexture(a,$c[b])},n:function(a){R.bindVertexArray(bd[a])},Ra:function(a){R.blendEquation(a)},Ua:function(a,b){R.blendEquationSeparate(a,b)},ba:function(a,b){R.blendFunc(a,b)},Ta:function(a,b,c,d){R.blendFuncSeparate(a,b,c,d)},r:function(a,b,c,d){S.nd?c?R.bufferData(a,E,d,c,b):R.bufferData(a,
b,d):R.bufferData(a,c?E.subarray(c,c+b):b,d)},p:function(a,b,c,d){S.nd?R.bufferSubData(a,b,E,d,c):R.bufferSubData(a,b,E.subarray(d,d+c))},ya:function(a){return R.checkFramebufferStatus(a)},Na:function(a){R.clear(a)},A:function(a,b,c){R.clearBufferfv(a,b,B,c>>2)},Oa:function(a,b,c,d){R.clearColor(a,b,c,d)},S:function(a){R.compileShader(U[a])},fa:function(){var a=gd(T),b=R.createProgram();b.name=a;T[a]=b;return a},G:function(a){var b=gd(U);U[b]=R.createShader(a);return b},t:function(a,b){for(var c=
0;c<a;c++){var d=x[b+4*c>>2],e=Xc[d];e&&(R.deleteBuffer(e),e.name=0,Xc[d]=null,d==od&&(od=0),d==pd&&(pd=0),d==R.Md&&(R.Md=0),d==R.ud&&(R.ud=0))}},Hb:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Yc[d];e&&(R.deleteFramebuffer(e),e.name=0,Yc[d]=null)}},ga:function(a){if(a){var b=T[a];b?(R.deleteProgram(b),b.name=0,T[a]=null,dd[a]=null):V(1281)}},Fb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Zc[d];e&&(R.deleteRenderbuffer(e),e.name=0,Zc[d]=null)}},H:function(a){if(a){var b=U[a];
b?(R.deleteShader(b),U[a]=null):V(1281)}},E:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=$c[d];e&&(R.deleteTexture(e),e.name=0,$c[d]=null)}},M:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];R.deleteVertexArray(bd[d]);bd[d]=null}},W:function(a){R.depthMask(!!a)},U:function(a,b){R.detachShader(T[a],U[b])},m:function(a){R.disable(a)},Z:function(a,b,c){R.drawArrays(a,b,c)},Ab:function(a,b){for(var c=qd[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];R.drawBuffers(c)},Va:function(a,b,c,d){R.drawElements(a,
b,c,d)},j:function(a){R.enable(a)},x:function(a){R.enableVertexAttribArray(a)},Bb:function(a,b,c,d){R.framebufferRenderbuffer(a,b,c,Zc[d])},Y:function(a,b,c,d,e){R.framebufferTexture2D(a,b,c,$c[d],e)},s:function(a,b){rd(a,b,"createBuffer",Xc)},za:function(a,b){rd(a,b,"createFramebuffer",Yc)},Eb:function(a,b){rd(a,b,"createRenderbuffer",Zc)},k:function(a,b){rd(a,b,"createTexture",$c)},O:function(a,b){rd(a,b,"createVertexArray",bd)},La:function(a){R.generateMipmap(a)},zb:function(a,b,c,d){if(d)switch(a=
T[a],c){case 35393:a=R.getActiveUniformBlockName(a,b);x[d>>2]=a.length+1;break;default:if(a=R.getActiveUniformBlockParameter(a,b,c))if("number"==typeof a)x[d>>2]=a;else for(b=0;b<a.length;b++)x[d+4*b>>2]=a[b]}else V(1281)},P:function(a,b){return R.getAttribLocation(T[a],F(b))},b:function(a,b){sd(a,b)},_:function(a,b,c,d){a=R.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ia(a,E,d,b):0;c&&(x[c>>2]=b)},C:function(a,b,c){if(c)if(a>=Vc)V(1281);else{var d=dd[a];if(d)if(35716==b)a=R.getProgramInfoLog(T[a]),
null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.Ad;else if(35722==b){if(-1==d.Kc){a=T[a];var e=R.getProgramParameter(a,35721);for(b=d.Kc=0;b<e;++b)d.Kc=Math.max(d.Kc,R.getActiveAttrib(a,b).name.length+1)}x[c>>2]=d.Kc}else if(35381==b){if(-1==d.Lc)for(a=T[a],e=R.getProgramParameter(a,35382),b=d.Lc=0;b<e;++b)d.Lc=Math.max(d.Lc,R.getActiveUniformBlockName(a,b).length+1);x[c>>2]=d.Lc}else x[c>>2]=R.getProgramParameter(T[a],b);else V(1282)}else V(1281)},$:function(a,b,c,d){a=
R.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ia(a,E,d,b):0;c&&(x[c>>2]=b)},D:function(a,b,c){c?35716==b?(a=R.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1):35720==b?(a=R.getShaderSource(U[a]),x[c>>2]=null===a||0==a.length?0:a.length+1):x[c>>2]=R.getShaderParameter(U[a],b):V(1281)},B:function(a){if(ed[a])return ed[a];switch(a){case 7939:var b=R.getSupportedExtensions()||[];b=b.concat(b.map(function(a){return"GL_"+a}));b=td(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
R.getParameter(a))||V(1280);b=td(b);break;case 7938:b=R.getParameter(R.VERSION);b=2<=S.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=td(b);break;case 35724:b=R.getParameter(R.SHADING_LANGUAGE_VERSION);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=td(b);break;default:return V(1280),0}return ed[a]=b},wa:function(a,b){return R.getUniformBlockIndex(T[a],F(b))},Q:function(a,b){b=F(b);var c=0;if("]"==
b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=dd[a]&&dd[a].le[b])&&0<=c&&c<a[0]?a[1]+c:-1},F:function(a){return R.isEnabled(a)},ea:function(a){R.linkProgram(T[a]);var b=T[a];a=dd[a]={le:{},Ad:0,Kc:-1,Lc:-1};for(var c=a.le,d=R.getProgramParameter(b,35718),e=0;e<d;++e){var f=R.getActiveUniform(b,e),k=f.name;a.Ad=Math.max(a.Ad,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var r=R.getUniformLocation(b,k);if(r){var p=gd(ad);c[k]=
[f.size,p];ad[p]=r;for(var u=1;u<f.size;++u)r=R.getUniformLocation(b,k+"["+u+"]"),p=gd(ad),ad[p]=r}}},Pa:function(a,b){3317==a&&(fd=b);R.pixelStorei(a,b)},Cb:function(a,b,c,d){R.renderbufferStorage(a,b,c,d)},da:function(a,b,c,d){R.scissor(a,b,c,d)},T:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?x[d+4*f>>2]:-1;e+=F(x[c+4*f>>2],0>k?void 0:k)}R.shaderSource(U[a],e)},q:function(a,b,c,d,e,f,k,r,p){S.nd?R.ud?R.texImage2D(a,b,c,d,e,f,k,r,p):0!=p?R.texImage2D(a,b,c,d,e,f,k,r,xd(r),p>>(yd[r]|0)):R.texImage2D(a,
b,c,d,e,f,k,r,null):R.texImage2D(a,b,c,d,e,f,k,r,p?wd(r,k,d,e,p):null)},X:function(a,b,c){R.texParameterf(a,b,c)},c:function(a,b,c){R.texParameteri(a,b,c)},aa:function(a,b){R.uniform1i(ad[a],b)},va:function(a,b,c){a=T[a];R.uniformBlockBinding(a,b,c)},Qa:function(a,b,c,d){if(S.nd)R.uniformMatrix4fv(ad[a],!!c,B,d>>2,16*b);else{if(256>=16*b)for(var e=id[16*b-1],f=0;f<16*b;f+=16)e[f]=B[d+4*f>>2],e[f+1]=B[d+(4*f+4)>>2],e[f+2]=B[d+(4*f+8)>>2],e[f+3]=B[d+(4*f+12)>>2],e[f+4]=B[d+(4*f+16)>>2],e[f+5]=B[d+(4*
f+20)>>2],e[f+6]=B[d+(4*f+24)>>2],e[f+7]=B[d+(4*f+28)>>2],e[f+8]=B[d+(4*f+32)>>2],e[f+9]=B[d+(4*f+36)>>2],e[f+10]=B[d+(4*f+40)>>2],e[f+11]=B[d+(4*f+44)>>2],e[f+12]=B[d+(4*f+48)>>2],e[f+13]=B[d+(4*f+52)>>2],e[f+14]=B[d+(4*f+56)>>2],e[f+15]=B[d+(4*f+60)>>2];else e=B.subarray(d>>2,d+64*b>>2);R.uniformMatrix4fv(ad[a],!!c,e)}},L:function(a){R.useProgram(T[a])},w:function(a,b,c,d,e,f){R.vertexAttribPointer(a,b,c,!!d,e,f)},l:function(a,b,c,d){R.viewport(a,b,c,d)},o:function(){},oa:function(a,b,c,d,e){var f;
for(f=0;f<X.length&&null!==X[f];f++);if(0<f)throw"glfwCreateWindow only supports one window at time currently";var k=f+1;if(0>=a||0>=b)k=0;else{d?ae():g.md(a,b);for(f=0;f<X.length&&null==X[f];f++);f==X.length&&(h.tc=g.createContext(h.canvas,!0,!0,{antialias:1<Ad[135181],depth:0<Ad[135173],stencil:0<Ad[135174],alpha:0<Ad[135172]}));h.tc?(a=new zd(k,a,b,c,e),k-1==X.length?X.push(a):X[k-1]=a,Y=a,k=a.id):k=0}return k},Xa:function(){throw"glfwCreateWindowSurface is not implemented.";},Wa:function(){},
ka:function(a){a:{if(a=W(a)){a.td&&re(a.td,a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}h.tc=void 0}a=void 0}return a},Za:function(){},db:function(){},ra:function(a,b,c){v(b,g.zc,"double");v(c,g.Ac,"double")},Sa:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.width,e=a.height;v(b,d,"i32");v(c,e,"i32")},jb:function(a,b){if(a=W(a)){switch(b){case 208897:a.ad[b]=g.Pc?212995:212993}return a.ad[b]}},gb:function(a,b){Nd();if((a=Z[a])&&a.axes)return v(b,a.ue,
"i32"),a.axes;v(b,0,"i32")},fb:function(a,b){Nd();if((a=Z[a])&&a.buttons)return v(b,a.ve,"i32"),a.buttons;v(b,0,"i32")},u:function(a,b){return(a=W(a))?a.keys[b]:0},Mb:function(a,b,c){v(b,0,"i32");v(c,0,"i32")},Ma:function(a){v(a,1,"i32");Dd||(Dd=Ea([1,0,0,0],"i32"));return Dd},K:function(a,b){return(a=W(a))?0<(a.buttons&1<<b):0},v:function(){return yc()/1E3-Ed},Gb:function(){return 0},ja:function(a,b){return(a=W(a))?a.attributes[b]:0},qa:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.x,e=a.y;v(b,d,"i32");
v(c,e,"i32")},N:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.width,e=a.height;v(b,d,"i32");v(c,e,"i32")},Ia:function(){if(X)return 1;Ed=yc()/1E3;Ad=Fd;X=[];Y=null;window.addEventListener("gamepadconnected",Md,!0);window.addEventListener("gamepaddisconnected",Od,!0);window.addEventListener("keydown",Pd,!0);window.addEventListener("keypress",Id,!0);window.addEventListener("keyup",Qd,!0);window.addEventListener("blur",Rd,!0);h.canvas.addEventListener("mousemove",Sd,!0);h.canvas.addEventListener("mousedown",
Yd,!0);h.canvas.addEventListener("mouseup",Zd,!0);h.canvas.addEventListener("wheel",$d,!0);h.canvas.addEventListener("mousewheel",$d,!0);h.canvas.addEventListener("mouseenter",Ud,!0);h.canvas.addEventListener("mouseleave",Vd,!0);h.canvas.addEventListener("drop",ee,!0);h.canvas.addEventListener("dragover",fe,!0);g.ge.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.je=Y.x,Y.ke=Y.y,Y.ie=Y.width,Y.he=Y.height,Y.x=Y.y=0,
Y.width=screen.width,Y.height=screen.height,Y.xd=!0):1==Y.xd?(Y.x=Y.je,Y.y=Y.ke,Y.width=Y.ie,Y.height=Y.he,Y.xd=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(g.md(Y.width,Y.height,!0),Y&&Y.Gc&&se(Y.Gc,Y.id,Y.width,Y.height),Y&&Y.Rd&&se(Y.Rd,Y.id,Y.width,Y.height))}});return 1},y:function(){},Jb:function(){},ha:function(a,b){if(a=W(a)){var c=a.Uc;a.Uc=b;b=c}else b=null;return b},eb:function(){},ib:function(){},xb:function(){},Kb:function(a,b){if(a=W(a)){var c=a.Xc;a.Xc=b;b=c}else b=null;
return b},Ja:function(a){var b=Bd;Bd=a;return b},hb:function(a,b,c){if(a=W(a))switch(b){case 208897:switch(c){case 212993:a.ad[b]=c;h.canvas.removeEventListener("click",ge,!0);h.canvas.exitPointerLock();break;case 212994:console.log("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented.");break;case 212995:a.ad[b]=c;h.canvas.addEventListener("click",ge,!0);h.canvas.requestPointerLock();break;default:console.log("glfwSetInputMode called with unknown value parameter value: "+c+".")}break;
case 208898:console.log("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented.");break;case 208899:console.log("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented.");break;default:console.log("glfwSetInputMode called with unknown mode parameter value: "+b+".")}},ma:function(a,b){if(a=W(a)){var c=a.cd;a.cd=b;b=c}else b=null;return b},cb:function(a){var b=Cd;Cd=a;return b},Ca:function(a,b){if(a=W(a)){var c=a.ed;a.ed=b;b=c}else b=null;return b},pa:function(a,b){if(a=
W(a)){var c=a.ld;a.ld=b;b=c}else b=null;return b},bb:function(a,b){if(a=W(a)){var c=a.td;a.td=b;b=c}else b=null;return b},V:function(a,b,c){if(a=W(a))a.x=b,a.y=c},ab:function(a,b){a=W(a);if(!a)return null;var c=a.oe;a.oe=b;return c},_a:function(a,b,c){if(a=W(a))Y.id==a.id&&(b==screen.width&&c==screen.height?ae():(g.exitFullscreen(),g.md(b,c),a.width=b,a.height=c)),a.Gc&&se(a.Gc,a.id,b,c)},na:function(a,b){if(a=W(a)){var c=a.Gc;a.Gc=b;b=c}else b=null;return b},Ya:function(a,b){if(a=W(a))a.title=F(b),
Y.id==a.id&&(document.title=a.title)},$a:function(){},ia:function(){},la:function(a){a=Math.abs(a);0==a?Ac(0,0):Ac(1,a)},Aa:function(){window.removeEventListener("gamepadconnected",Md,!0);window.removeEventListener("gamepaddisconnected",Od,!0);window.removeEventListener("keydown",Pd,!0);window.removeEventListener("keypress",Id,!0);window.removeEventListener("keyup",Qd,!0);window.removeEventListener("blur",Rd,!0);h.canvas.removeEventListener("mousemove",Sd,!0);h.canvas.removeEventListener("mousedown",
Yd,!0);h.canvas.removeEventListener("mouseup",Zd,!0);h.canvas.removeEventListener("wheel",$d,!0);h.canvas.removeEventListener("mousewheel",$d,!0);h.canvas.removeEventListener("mouseenter",Ud,!0);h.canvas.removeEventListener("mouseleave",Vd,!0);h.canvas.removeEventListener("drop",ee,!0);h.canvas.removeEventListener("dragover",fe,!0);h.canvas.width=h.canvas.height=1;Y=X=null},g:function(a,b){Ad[a]=b},memory:Ca,sb:function(){return 0},nb:function(a,b,c,d){return me(a,b,c,d)},table:Da,Ka:function(a){var b=
Date.now()/1E3|0;a&&(x[a>>2]=b);return b}},ue=function(){function a(a){h.asm=a.exports;cb("wasm-instantiate")}function b(b){a(b.instance)}function c(a){return hb().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){l("failed to asynchronously prepare wasm: "+a);q(a)})}var d={env:te,wasi_unstable:te};bb("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(ua||"function"!==
typeof WebAssembly.instantiateStreaming||db()||"function"!==typeof fetch)return c(b);fetch(eb,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){l("wasm streaming compile failed: "+a);l("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();h.asm=ue;
var ib=h.___wasm_call_ctors=function(){return h.asm.Nb.apply(null,arguments)},Fa=h._malloc=function(){return h.asm.Ob.apply(null,arguments)},de=h._free=function(){return h.asm.Pb.apply(null,arguments)};h.___errno_location=function(){return h.asm.Qb.apply(null,arguments)};h._main=function(){return h.asm.Rb.apply(null,arguments)};
var pe=h.__ZSt18uncaught_exceptionv=function(){return h.asm.Sb.apply(null,arguments)},La=h.stackAlloc=function(){return h.asm.Tb.apply(null,arguments)},re=h.dynCall_vi=function(){return h.asm.Ub.apply(null,arguments)},Jd=h.dynCall_vii=function(){return h.asm.Vb.apply(null,arguments)},se=h.dynCall_viii=function(){return h.asm.Wb.apply(null,arguments)},Xd=h.dynCall_viiii=function(){return h.asm.Xb.apply(null,arguments)},Rc=h.dynCall_iiii=function(){return h.asm.Yb.apply(null,arguments)},Td=h.dynCall_vidd=
function(){return h.asm.Zb.apply(null,arguments)},Ld=h.dynCall_viiiii=function(){return h.asm._b.apply(null,arguments)};h.dynCall_v=function(){return h.asm.$b.apply(null,arguments)};h.asm=ue;h.getMemory=function(a){if(Xa)var b=Fa(a);else b=x[26228],a=b+a+15&-16,a>w.length&&q(),x[26228]=a;return b};h.addRunDependency=bb;h.removeRunDependency=cb;h.FS_createFolder=nc;h.FS_createPath=oc;h.FS_createDataFile=qc;h.FS_createPreloadedFile=uc;h.FS_createLazyFile=tc;h.FS_createLink=rc;h.FS_createDevice=O;
h.FS_unlink=bc;h.calledRun=ve;var ve;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ab=function we(){ve||xe();ve||(ab=we)};
function xe(a){function b(){if(!ve&&(ve=!0,h.calledRun=!0,!C)){Xa=!0;h.noFSInit||lc||(lc=!0,kc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?O("/dev","stdin",h.stdin):ac("/dev/tty","/dev/stdin"),h.stdout?O("/dev","stdout",null,h.stdout):ac("/dev/tty","/dev/stdout"),h.stderr?O("/dev","stderr",null,h.stderr):ac("/dev/tty1","/dev/stderr"),ec("/dev/stdin","r"),ec("/dev/stdout","w"),ec("/dev/stderr","w"));Ra(Ta);Kb=!1;Ra(Ua);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(ye){var b=
a,d=h._main;b=b||[];var e=b.length+1,f=La(4*(e+1));x[f>>2]=Ka(da);for(var k=1;k<e;k++)x[(f>>2)+k]=Ka(b[k-1]);x[(f>>2)+e]=0;try{var r=d(e,f);qe(r,!0)}catch(p){p instanceof pa||("SimulateInfiniteLoop"==p?va=!0:((b=p)&&"object"===typeof p&&p.stack&&(b=[p,p.stack]),l("exception thrown: "+b),ea(1,p)))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)b=h.postRun.shift(),Wa.unshift(b);Ra(Wa)}}a=a||ca;if(!(0<Za)){if(h.preRun)for("function"==typeof h.preRun&&
(h.preRun=[h.preRun]);h.preRun.length;)Ya();Ra(Sa);0<Za||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=xe;function qe(a,b){if(!b||!va||0!==a){if(!va&&(C=!0,h.onExit))h.onExit(a);ea(a,new pa(a))}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ye=!0;h.noInitialRun&&(ye=!1);va=!0;xe();
